### ISSUE TITLE
Commenting forum topics from activity feed

### ISSUE THREAD

**Issue by tbermudas** [SocialEngine/phpv4-issues#104]
When a user comments a forum topic from activity feed (What's new) the comment is not added to the discussion.
With Blog post works.

**Comment by Anshuse** [comment]
Hi @tbermudas ,

We understand what you're trying to say here but it's not possible to synchronize forum posts with comments. This is because even if we add posts when a new comment is done, it won't be possible to do the vice-versa. This way, we would be able to provide just one way synchronization that would look more odd and misleading for users.

Best Regards,
Anshu
