### ISSUE TITLE
Old third-party modules subject to XSS Injection

### ISSUE THREAD

**Issue by happycoder1337** [SocialEngine/phpv4-issues#109]
many of the third-party plugins are way out dated and are subject to XSS injection.

**Comment by smazurov** [comment]
we can't help that.

**Comment by happycoder1337** [comment]
why include them if you cant help? 
I'm talking about flowplayer and flash charts, 
why do you guys include them if they poses a security risk?

**Comment by smazurov** [comment]
When you say 'modules' i assumed you meant 3rd party plugins offered by our 3rd party developers.  We've addressed XSS vulnerabilities in flowplayer (#56) and flash charts (#57) in their original reported issues. 

If you have any other specific vulnerabilities to report please do so, otherwise I would appreciate if you could use search and minimize duplicate issues.  We offer this channel on voluntary basis and by opening duplicate issues you effectively remove us from responding to others.

**Comment by happycoder1337** [comment]
sorry about this, 
I just think its important for these security risks to be fixed, since no fix on release 4.8.9
