### ISSUE TITLE
Default Notifications

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#121]
Any member of an admin level does not receive email notifications accept the appointed first super admin and their email respectively. This should be changed and expanded upon so whether a new post gets shared, a reply to a post or any admin activity regarding a post gets done to following recipients such as it has been deleted or updated, particularly useful for groups events and their content, this should be able to happen and be controlled in the default email notifications section. Additionally, members should be able to override this setting, but also make some settings sticky and configurable so the site is set up to where if a notification cannot be changed, members won't have the option to configure it within their settings.

**Comment by Anshuse** [comment]
Hello @Elshara ,

1) Regarding "Any member of an admin level does not receive email notifications accept the appointed":
All the emails, except the email of new user sign up, goes to both super admin and admin(s). If there is any specific email which is being sent to super-admin but not to the admin(s) then please let us know that particular email so that we can check it out at our end.

2) Regarding "default email notifications":
All the default email notifications that belongs to the core module and core plugins of SocialEngine, present in the "Settings" > "Notifications" section in the user end are configurable in the Admin Panel under "Admin" > "Settings" > "Default Notification Settings" section. If some of the default notifications that belongs to third party plugins, are present at user end but are not configurable in the Admin Panel then you may contact the developer of the plugin.

Best Regards,
Anshu

**Comment by Elshara** [comment]
Specifically I was referring to the user sign up email and the contact
us email. The contact us email should go to all admins same as the
user sign up.

**Comment by shivani2910** [comment]
@Elshara : We've already provided a setting ```"Contact Form Email"``` in the Admin > Settings > Mail Settings section of the site where you can enter an email address on which you would like to receive emails that are sent via contact form. If one doesn't enter any email address then we send such emails to super admin's email address. So, you can accordingly use this field to receive contact form emails.

**Comment by Elshara** [comment]
Okay.
