### ISSUE TITLE
Copy paste word text to activity feed

### ISSUE THREAD

**Issue by topikiagora** [SocialEngine/phpv4-issues#136]
When i copy a text from word or pdf and paste at activity feed to post it, the text is not appeared. Look at the screenshots.
![copy2](https://cloud.githubusercontent.com/assets/12969725/8481903/c011c144-20ee-11e5-84f3-49f5d93f12ca.png)
Thanks!

**Comment by Vaibhavagarwal0807** [comment]
Hi @topikiagora - It seems that this is not the SE bug, but is due to some other problem. May be because such content is first copied into your clipboard and may be other formatting got attached to the copied text. There are debatable reasons for this extra formatting or styling.

But, a quick fix to it is :

1. To paste without formatting to a browser (Firefox/Chrome at least): CTRL+SHIFT+V on Windows/Linux.

2. Under Mac OS X, you can Shift-Option-Cmd + V (to paste) without formatting or with the "current" format.

3. Paste to Notepad (or other text editor), and then copy from Notepad and paste again.

Hope this information help you.
