### ISSUE TITLE
Ability to edit status posts

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#143]
Currently, status posts made via the activity feed are not editable, meaning users have to delete and repost the status when making corrections. We want text-based status posts to be editable by users.

**Comment by meetgerry** [comment]
Lovely! You guys rock!

**Comment by keshavmd** [comment]
Appreciate the idea, much needed but at the same time do keep history of edited post/comments. 
There should be link named edited after the user profile in post/comment activity feed which while hovering mouse over it should reveal the past edited history, so that this feature does not get misused.

For more refer to facebook edit post option
Link : https://www.facebook.com/help/105443102880679?sr=1&query=edit%20comment&sid=2939A4Dj5mnpw451b

Detail:
How do I delete or edit a comment I posted?

To delete a comment:

Hover over the comment and click 
Select Delete...
Click Delete
To edit a comment:

Hover over the comment and click 
Select Edit...
Edit your comment
Press Enter or Return to post your updated comment, or Esc to cancel
When you edit a comment, you'll see a note under your comment showing the time it was edited. Anyone who can see your comment can see that it was edited and click the link to see what was changed.

I hope replying in this much detail will help Team to understand the project needs better

**Comment by SpiritWolfie** [comment]
This needs to work both ways, not just on the comments you post, but on responses as well, it would be pointless to include it just for the OP but not for any responses.

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
