### ISSUE TITLE
Better Social Login buttons on Login/signup page

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#163]
We're planning to display better and more attractive icons for Facebook and Twitter logins on the Login/Signup page.

**Comment by keshavmd** [comment]
Minor Suggestion can we also consider Google sign up button.
Also option to filter users based on Direct signup / facebook signup/ Twitter sign up/ google sign up.
And at the same time allowing a feature to migrate the registration to SE core by send a new password and prompting user to add password to the account for those users who have registered using these 3rd party social engine in case site owner decide to migrate all users registration to itself as main site.

Note: Mail id and other details will remain the same as at the time of signup.

And Can we improve the sign up form as well by adding validating the input as soon as user finish that particular field.
And keeping it interactive, fast  - Improved UI.

**Comment by smazurov** [comment]
Have you considered using Janrain for this? [Google Plus](https://rpxnow.com/docs/providers#googleplus) is available in the "Basic" package which is free.

**Comment by keshavmd** [comment]
Yes I have considered Jain rain, but problem with using 3rd party plugins is they do not support other 3rd party developers plugins and specially mobile apps.
It is the main reason behind my all major suggestions till day to SE PHP team, I am only sharing those problems which are needed in core part.
So if SE php itself provides sign up through FB/twitter/google+ than it is a by default feature.

Apart from this issue another one is migration issue: For those users who might have signed up using nay 3rd party API, but now admin decide to shift them to core, so can send them new link to their mail and can migrate by inputting new password.

And another one was validating input by ajax based, as soon as user enter data into fields during signup, it gets verified on the spot instead of validating entire sign up form.

**Comment by smazurov** [comment]
if 3rd party plugin doesn't support janrain, they wouldn't support google+ (at least initially). Its makes a lot more sense for the 3rd party plugin to provide support for janrain than another login method. 

Janrain actually has mobile app support, so I dont think thats a problem either. 

I don't quite understand the migration or ajax issues you're describing.

**Comment by keshavmd** [comment]
@smazurov  for Migration part:

Let's understand it this way,
USer1 registered via fb signup button
User2 registered via twitter signup button
User3 registered Directly

Case1: fb is not working, so user1 will not able to login, or fb is blocked via firewall in office or wifi router so again user1 wont be able to login.

SO in such cases can there be an option to send a password reset and signup migration link to the user for having him/her transferred from fb login to direct login.

**Comment by smazurov** [comment]
> Case1: fb is not working, so user1 will not able to login, or fb is blocked via firewall in office or wifi router so again user1 wont be able to login.

This is not true, you can request a password reset and then you will be able to log in with a password. We could make an improvement to "Change Password" area to not show "Old Password" in case of user registering with twitter/fb/janrain.

**Comment by Elshara** [comment]
:)
