### ISSUE TITLE
Default Layout Of Modules

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#172]
Default layout of some modules such as profile friends, followers following and popular members, as well as others, have something in common. Members sorted in the order of oldest first. This is a little boring and repetitive, one would think newest first would be much easier based on profile updates. Is this possible.

**Comment by shivani2910** [comment]
@Elshara The 2 widgets "Profile Followers" & "Profile Followings" come into picture when admin enables one way friendship setting on website, otherwise there is only "Profile Friends" widget that is displayed on Member Profile page out of these 3. "Popular Members" widget that you've mentioned is a different thing and is not necessary to be placed on member profile page. It can be placed on any page to display most popular users based on the views on their profile. So, these widgets can not be merged into one and serve different purposes. Apart from that, we also have a "Newest Members" widget that displays most recent signups on the website.

**Comment by Elshara** [comment]
True, I'm not talking about what the widgets do though, I'm referring
to how the contents inside them are displayed. Editing the display of
this as a content item is what I'm looking for.
