### ISSUE TITLE
Banned Words

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#188]
It would be nice to replace the word value of what words are being banned.

**Comment by Anshuse** [comment]
Hi @Elshara , We didn't understand your point here, it would be great if you can explain your query in a bit more detail (along with screenshot, if possible) so that get back to you accordingly. Thanks!

**Comment by Elshara** [comment]
In social engine, the sensored words feature is explained as the following.
Censored WordsEnter any words that you you want to censor on your
users' profiles as well as any plugins you have installed. These will
be replaced with asterisks (*), and will only affect new content.
Separate words by commas like word1, word2
I'm saying we should be able to replace how words appear.

**Comment by Anshuse** [comment]
Hi @Elshara , currently, when any word, that is included in your censored words list, is posted on site then it gets replaced with asterisks (*). Now, it seems that you want that Site-admins should have ability to change how these words should be displayed on site i.e site-admin should be able to use something else instead of asterisks (*). If so, then we're sorry but this is not possible using default settings of SocialEngine.

Thanks!

**Comment by Elshara** [comment]
Just figured it could help.
