### ISSUE TITLE
Group invite notifications are not being sent

### ISSUE THREAD

**Issue by chrisjacob23** [SocialEngine/phpv4-issues#191]
When I invite a user to join a group clicking on "Invite" link from left column links on Group Profile page, invitation notifications(both email and site notifications) are not received by that user. This issue is affecting the groups on website. Please resolve this.

**Comment by shivani2910** [comment]
Hi @chrisjacob23 You need to do a small change to fix this issue on your website:

***Fix***

In [application/modules/Group/controllers/MemberController.php](https://github.com/SocialEngine/phpv4/blob/develop/application/modules/Group/controllers/MemberController.php#L591) file, please search and replace below code (around line no. 591)

```php
sort($multiOptions);
```

with below mentioned new code:

```php
asort($multiOptions);
```

Also, we'll fix this in next release so that you don't not face this issue again in future. Please drop us a line in case of any queries.

Thanks

**Comment by Elshara** [comment]
This is a confirmed issue and it happens in newer and older group modules.

**Comment by smazurov** [comment]
Fixed in [4.8.10](http://blog.socialengine.com/2016/01/20/socialengine-php-4-8-10-is-released/)
