### ISSUE TITLE
Admin Cross Site Scrpting Vulnerability

### ISSUE THREAD

**Issue by BikersPost** [SocialEngine/phpv4-issues#193]
1) Hackers are able to join as regular members than XSS them selfs into Super Admin

2) Hackers are able to XSS script into General Settings - Head Scripts/Styles

3) Hackers are able to XSS script into Ads - Manage Ad Campaigns & VigLink

4) Hackers are able to XSS script into HTML Block

I'm sure there is a lot more that just what we have experienced in the last week

**Comment by smazurov** [comment]
can you send stepan@socialengine.com details on how 1) is done? This one needs to be fixed, the others are expected. As we offer admins unparalleled flexibility with SocialEngine, adding dangerous scripts is one of them.

**Comment by Elshara** [comment]
Permissions check should render them unable to touch such files. That should be a security requirement, permissions check on sensitive data folders and database queries ensuring only user level permissions signed in could access such things.
Having said that it isn't just hackers who could access such things. It is anyone who has open access to database calls to change the information in the first place so they get access to back door content. You'd think a simple access block would render that impossible from anything accept a script.

**Comment by BikersPost** [comment]
2 - 4 were done was done as non-membrer the same way 1 was done to make regular member a super admin

**Comment by Elshara** [comment]
Certainly is a security flaw to say the least! The more files social
engine loads on page view, the more vulnerabilities those files and
their sources become available.
I'm almost wondering if they could be blocked through a template but
if they can't access the site through a browser anyways it would
render template blocking useless.
I thought cloud flare had this kind of thing sorted out in advance. I guess not.

**Comment by BikersPost** [comment]
we initially enabled Incapsula but he was able to work around that because unless you restrict direct access to your website they can render Incapsula useless https://incapsula.zendesk.com/hc/en-us/articles/200627570-Restricting-direct-access-to-your-website-Incapsula-s-IP-addresses-

So it to me about 12hr to figure out how to only allow access to the site from Incapable. Once I figued that out we blocked his country (Jordan) which that must of pissed him because he sent the following email ""Hello fuck head, this time i swear my goal is not getting revenue from ads, now I'm gonna fuck up your website totally old grandpa, you will see..""

He spent most of the day trying to gain access which he was able to do so once and that is when he enabled Ad and created a new Ad Campaign which this was done threw a proxy sever because I could see his attempts being blocked from his Country. I received thread alerts from Incapsula for Cross Site Scripting but was still figuring my way around Incapsula and learned the default setting was Alert Only I have since changed that to Block and he hasn't been able to gain access since that was around 1pm Sat EST. I'm expecting to receive another message from him any time now :)

**Comment by smazurov** [comment]
I would highly recommend you remove this message as this just gives them information.  I've received your email and we'll discuss directly.

**Comment by Elshara** [comment]
You wouldn't believe how many hacking attempts I was subject to on
Ning. It's exactly those kind of arrogant people who actually look for
active websites to either ddos attack or try to earn money from if
enabled. I totally recommend saving his original ip if you remembered
to.
This is precisely why I switched over to cloud flare not because of
ips, but because if they try to dos attack the site it only goes
straight to the name server of cloud flare so they can't get in via
ip. I'm not sure if amazon is safe anymore either.
Social engine has .htaccess files listed everywhere. That should work
for blocking ips right from the core and you don't even need a third
party software, just place it in the root directory and he'll just get
a 403 forbidden message. Even if he uses a server or proxy, just make
a rule stating no proxies are allowed because of security reasons.

I wonder if he has access through enabling social engine cdn features.

**Comment by BikersPost** [comment]
we moved from ning to se a few years ago. we use to use cloud flare simply because we get a lot of spam from china, India etc so we used it to simply block those countries but recently they changed and now only offer that to their Enterprise customers.

**Comment by Elshara** [comment]
Yeah. I've been using a company called host iso for awhile now. Their
entire server and domain base is protected by cloud flare servers so
otherwise I'd still be on Ning, having tried other providers with
really bad results to say the least.
You know ever since 2013 I knew Ning was just at the end and you
wouldn't believe how right my intuition was and is. SE is a thousand
times better, I've also been dabbling in phpfox simply because it is
very interesting, though I have to admit their company is far from
stable now days and their best product stopped development in 2013 as
well, v3.8.
Having said that a platform is only as good as the server it is on.
There were times when I used to think a skype chat did just as well
because people could just grab contacts and organize things in real
time, but then you get the nay sayers who think social media is just
not brand worthy so in brings about the content creation aspect of it,
mainly archivable things members can do for a need to want to be
interest based on topics and community gathering through search and
public domains.
Spam bots and hackers have dominated a large part of the fear based
control requirement aspect of what would otherwise be a very good and
successful platform that has since become the internet. Yes, open for
everyone it may be, but it doesn't mean we have to put up with things
we aren't interested in and to be honest, that was why I left Ning
even though the truth is it as a platform worked for me, they wanted
to get rid of me for being too inquisitive about their practices and
deciding to ignore what they said and did things my way got more heart
break than satisfaction out of it, but you know what, I don't regret
it and it's their loss.
Never been a 3.0 supporter and their 2.0 has simply a power on the
server and that's it. Ning is otherwise dead to the world, outsourced
support, no update in a year and a half, people can't call anyone, a
disaster waiting to happen. All thanks to Glam media and associates.
I'm sure glad I never bought into the whole acquisition poster boy
scam. Social Engine is one of the many many rarities that make up a
decent population of the internet and I can't thank them enough for
being here.

**Comment by smazurov** [comment]
Since no further details were provided in over a year I am closing this
