### ISSUE TITLE
Static Or Dynamic Layouts

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#211]
Social Engine should offer ways to customize things in a global setting base allowing people to customize where things are accessed and how they get used. From its very core, social engine should be user friendly. For that to happen, we must be able to control whether things are dynamic, or static in nature. Whether we want things to globally be statically placed, or dynamically placed but using the same file to achieve many different things inside of it, or many files to do many different things independent of each other.

**Comment by shivani2910** [comment]
@Elshara In SocialEngine's admin panel, we've provided most of the configuration settings using which you can configure your website as per your requirements. Since, it's not much clear from your message that which more configurations do you feel are required to be implemented, we're closing this one.

**Comment by Elshara** [comment]
I understand. Sorry about that.
