### ISSUE TITLE
need a better picture tagging system

### ISSUE THREAD

**Issue by alex2211** [SocialEngine/phpv4-issues#218]
The current tagging system shows the tag marquee in the top left corner and you must reposition it and also resize it. I think the tagging marquee should show in the exact place you click and have fixed size. I also think they should allow to add generic tags to images.

**Comment by Elshara** [comment]
I agree. Tags should be an optional feature, alternative to categories.

**Comment by shivani2910** [comment]
Hi @alex2211,

Regarding your query, when you said "... tagging marquee should show in the exact place you click..", we're not sure that which "click" are you exactly talking about because in default "Albums" module, we just display an "Add Tag" link in the list of options on photo's main page clicking on which dislay a tag box inside the photo which works fine. So, it's not possible to click inside the photo to display the tag box because of which we've provided the option to re-position and re-size the tag box. Hope you get our point here.

Please drop us a line in case of any further queries.

Regards,
SocialEngine Support
