### ISSUE TITLE
Ineffective User Block System

### ISSUE THREAD

**Issue by wtoalabi** [SocialEngine/phpv4-issues#221]
From my understanding on how banning supposed to work (taking cue from facebook, etc), when a user deem another troublesome and clicks "Ban" on the troublesome user's profile, then automatically all contents, activities and contributuons of the banning member becomes hidden to the banned member. I have found the hard way that this is not the case with Social Engine...at least yet.
Instead what is currently available is that only the profile page becomes hidden.
It would be nice if the whole existence of the banning party becomes unavailable and hidden to the banned party.

**Comment by shivani2910** [comment]
Hi @wtoalabi, thanks for reaching out!
Yes, you're right. Blocking needs some improvements. We already have a plan to implement these improvements in future.

**Comment by Elshara** [comment]
How about a user recycle bin where everything they have posted they can still access but only to them if they decide to leave the community at that point it is their decision. This should work both ways, users should have some admin defined rights if any should they choose to do something with their contributions. Otherwise admins just do not give them such rights as settings.

**Comment by shivani2910** [comment]
@Elshara It seems that you're talking about user deletion process while the current discussion is going on regarding the user banning process being followed currently. Please file another issue if you want to report a problem / suggetsion other than this. Thanks.

**Comment by SpiritWolfie** [comment]
Thanks for linking me to this Shiv
I'm simply going to paste my statement from my issue over here, so that ways its all in one location

This has been a "Huge" issue for my community, Blocking does not work correctly like it should

If user A blocks User B, User B can not see their profile, -however- User b can still comment on user A's stuff etc..

The way it should work is, if user A blocks User b, User b should not be able to see their stuff.

I really look forward to seeing this resolved, please please let me know if I can do anything to assist in this matter.

Thanks for the update on that its planned to be addressed in a update, I just hope really soon, as this is a serious serious issue for any community thats blooming

**Comment by Elshara** [comment]
Love your name! Got a site I can check you out at?
I had no idea the blocking feature was so Inadequate.
Does this work if friendship settings are altered? I assume not since
it directly ignores privacy settings. The person who blocked the other
person from communicating should be able to control what the other
person can comment on or view through content settings.
Trouble is blocking them altogether doesn't reference or override such
settings. I assume they aren't even related, though they ought to be.

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
