### ISSUE TITLE
Deleted Members Infomation

### ISSUE THREAD

**Issue by wtoalabi** [SocialEngine/phpv4-issues#222]
When a member is deleted, his/her content will still be hanging around. For instance, if the user once contributed to a post via comments, his or her content will still be showing up even after she/he is deleted from the platform.
Worse still, the user's name will be replaced with "Deleted Member" in the full glare of the whole community.
Why cant deleted members just go quietly?

**Comment by smazurov** [comment]
this isn't so simple. If we did delete their content, a lot of conversations won't make sense, for example.  Whole threads will be gone, and if those threads were popular with the community, they will be more upset by them being gone than being attributed to "deleted member". 

There are certainly situations where you want the content gone, if you get a lot of spam from a single user and delete that member, for example, but in general, we choose to believe that content is more important than the user that contributed it.

**Comment by wtoalabi** [comment]
Hmn...your explanation surely makes a lot of sense...I didnt see it from that angle before!
However, considering the unwanted nuisances of spammers...can we have have a "Mute" option?
This way, instead of permanently deleting a member, one can mute the account. Meaning, his/her content will be available on the system but will not be shown until the admin "Unmute" the account.
This way, any user with questionable activities will be placed on probation period while the account is assessed by the admins.
Also, instead of "Deleted Member" maybe "Banned Member" will sound better...

**Comment by happycoder1337** [comment]
you meant disable an account, but thats too much to ask for since the disable button doesnt not work. and even if you disable the account, the account can still be reviewed and receive messages.

**Comment by smazurov** [comment]
> you meant disable an account, but thats too much to ask for since the disable button doesnt not work. and even if you disable the account, the account can still be reviewed and receive messages.

This isn't a helpful attitude. We provide this service for free and it is used only to communicate bugs and feature requests to us. I haven't seen the problem you're describing, but can you link to an open issue regarding this?

**Comment by happycoder1337** [comment]
Ok, when you use admin interface and goto members, try edit a member and disable its account. 
When you're done, click edit again, nothing changed.

**Comment by smazurov** [comment]
you as an admin can edit all accounts, thats not an issue.

**Comment by troydbertrand** [comment]
@smazurov I just duplicate the "issue" @happycoder1337 is having. Here's what he's saying...When you choose the "edit member" option and "uncheck" the "Enable" box and click the "Save Changes" button nothing actually happens. the changes appears to be save but then if you go back and "edit' that same member you'll find that the "Enable" box is still checked off.

Hope that helped.

TDB

**Comment by troydbertrand** [comment]
Ha! It Appears that you would also need to "uncheck" the other boxes ("approved" and "verified") as well @happycoder1337. Just did that and it worked.

TDB

**Comment by smazurov** [comment]
Awesome, thank you for clarifying and providing a fix.

We'll see if we can work in a bit of magic to uncheck the other 2 checkboxes when you uncheck enabled.

**Comment by Elshara** [comment]
Funny thing is re: original thread, I've experienced the exact opposite problem with the member deletion feature. It works exactly as it is supposed to, all their created groups, blogs, photos, music, videos and other items get erased along with comments so if anything we need an option to review who has left the community along with an option to reinstate them if their content is active. In other words, a content and or user recycle bin.

**Comment by Elshara** [comment]
Same should go for the deleted items feature. It should go towards a recycle bin, where you review all the content attached to a profile that should be removed or changed. This could be a sort of security system.

**Comment by Anshuse** [comment]
Hi @Elshara , As your query is not related to the subject discussed in this thread, so we suggest you to open a new issue regarding same.

**Comment by geekygurly** [comment]
This is a serious legal flaw with the new version of SE. 

If a member is deleted or removes there account.. with the exception of MAYBE the forum... their content LEGALLY needs to be removed also. All social networks work this way. SE3 worked this way... Conversations 'not making sense' is not really a good explanation as to why this legal implication change has happened. 

I also have a lot of spammers and there content of "donate money to their email address " is being left to still impact my members. I have zero way to remove the sometimes hundreds of messages that may have been sent before being caught. These floating messages also is filling up the server with zero way for a person to respond to them.  Please fix this or at LEAST give the option to "remove all content" or "leave all content" of deleted members.

**Comment by Elshara** [comment]
Did something recently change?
I have noticed since v4.8.12 a lot of increased spammer IP based
traffic has been occurring.

**Comment by smazurov** [comment]
We didn't change anything.

> If a member is deleted or removes there account.. with the exception of MAYBE the forum... their content LEGALLY needs to be removed also. 

Virtually all terms of service clauses include agreeing that anything user posts they give a license to the site to use forever, including after they decide to delete their account. 

To be clear, there is a bug here that we should fix, unrelated to deleted content discussion:

> When you choose the "edit member" option and "uncheck" the "Enable" box and click the "Save Changes" button nothing actually happens. the changes appears to be save but then if you go back and "edit' that same member you'll find that the "Enable" box is still checked off.

I know deleting members/content is something that can be handled in a variety of ways, and one thing we can do is enhance this in a future version. Right now it works how it works, so I highly suggest including relevant wording in your terms of service, so that you have legal right to keep the content of your users. 

Alternatively, I'm wondering if there is a plugin that modifies this to delete all associated content instead.

**Comment by amandablain** [comment]
> Virtually all terms of service clauses include agreeing that anything user posts they give a license to the site to use forever, including after they decide to delete their account.

This is not exactly true. Major social networks include clauses that state content may stay on a BACKUP server, while it is being deleted but comments, photos etc will and SHOULD be removed.  - 

https://www.facebook.com/help/224562897555674
"When you delete your account, people won't be able to see it on Facebook. It may take up to 90 days from the beginning of the deletion process to delete all of the things you've posted, like your photos, status updates or other data stored in backup systems. While we are deleting this information, it is inaccessible to other people using Facebook.
Some of the things you do on Facebook aren’t stored in your account. For example, a friend may still have messages from you even after you delete your account. That information remains after you delete your account."

But as you are aware.. when a spammer spams half of Facebook those "spam messages" are also removed completely from the server. Adding an option as a bare minimum that when an admin removes an account that 'all of their spam messages" are removed should be added. 

I have recently upgraded to SE4 from SE3 so am shocked this is not included and this change has happened with no mention of it anywhere.  I will code this in myself for the message function and am rather disappointed you have created potential legal and tons of floating spam on my site because of this over site.

**Comment by SpiritWolfie** [comment]
There should be a option to delete members stuff fully, or to keep it

if someone made it a point to post something illegal and you delete them, instead of having to manually go though every little thing to find it, it would be lovely to have a option to "Opt" To delete it in full. Most other social platforms provide a option to keep/or remove someones content from your site in full.

Think if a spam bot managed to get in and made countless posts on your wall, forums, blogs, polls etc, (which they can do, i've seen it) the staff would then have to find every little area (and believe me its not that easy) and delete it one by one.

@amandablain 
Has said this IS a legal matter as well

if you request your data to be removed, depending on where your hosting the stuff they are required to remove it, Lets take my website for example, allot of my users are into buying or drawing anthropomorphic chars, People will commission or draw, The moment anything is drawn it gets a basic IP right by USA Law that that item is legally theirs, Just because they upload it on my website does not mean that IP right is being transferred to me, nor can I legally claim I own it, (That would be illegal to do)

if that user decided to remove his account or want his account removed and requested his/her info be removed in full (including the art they commissioned/legally paid someone to draw for them) and I didn't do it? they could then slam me with a cease & desist/potential law suit/ DMCA take down notice Legally.....

Yes this is a legal matter as well, I've dealt with this stuff many times in the past.

**Comment by Elshara** [comment]
I agree here. Removing member content is necessary, legally so, on a
case by case basis. It isn't just a requested feature, it is a feature
that can get us into serious trouble as web admins if we are held
liable for it if it is found on our servers, should it be dealing with
content we have to take action on immediately. Such as illegal
pornography, slanderous behavior from other people who abuse members
and whose profiles must be removed from the website for abuse and
disruption. For spam bots whose goal is to scam members for money to
put sometimes very serious malware onto computers, computers we use as
admins to be the heart pulse of our communities on social engine, or
anywhere else.
If Facebook groups have this option, why doesn't paid platforms take
it seriously? It's not the customers fault you drag your feet when we
ask you for help, and not someone too desperate to not offer their
services for an over charge because someone in the development team is
missing in action.
Here is a perfect example of a need for this feature to be
implemented. Which is a simple member content check box, that connects
to the database to manage the content and the profiles of all site
members.
1. I sign up to a web platform like
http://community.onsocialengine.com for instance, and start making
friends with people there.
2. I would never do this, but for figurative and example purposes
only, imagine if you will, that after a week of me being there, I
private message everyone on my friends list with the following
message. I'm giving you my social engine client login details so you
can give a free copy of social engine to all your friends if they want
it.
3. Word spreads as I give the details of such a message to everyone on
my friends list. It goes viral, and it gets spread to everyone in the
community.
4. What do you do? Ban me for sending the message? Try to remove the
offensive material? Do you have the ability to do that with social
engine PHP if the cloud was not available? What would you do if you
were not able to manage that. Tell a third party developer to try to
delete all the private messages on the server with a specific subject
line in the database? Then you'd have to find a way of making sure a
license stored locally was unable to connect to website databases
somehow, which would prevent malicious use of piracy on social engine.
5. Assume I was banned for posting that. You wouldn't in social engine
PHP, be able to even begin to manage such a problem. Because the
functionality is not there that could easily be taken care of with a
simple member check box that allows you to view and manage offensive
material if necessary. Regardless of what state, user group or
permission base such an account happens to be in. left, deleted,
member, administrator, pending approval, unverified and so on. Imagine
when you banned the person, that all their content remained. And that
at the very heart of your own community, you are unable to manage it.
That is the kind of care and attention we need to fix this problem.
Keep the content if you wish, allow the member to choose what to keep
if they leave as they wish, but make it apparent to those of us who
are obviously looking for a way around such a problem, that you care
about not just what we build, but what we host and who joins us as a
part of us being a host to the ideas we bring forth as community
managers.

**Comment by poeticjustice** [comment]
I understand what @khushboo016 means regarding posts get confusing.

That said the other day I had a user posting all other his wall, in forums, and various of modules that he could post, on walls of others etc.
It was found to a employee of a company that I'm competing with who doesn't have the social aspect with their buisiness.

I logged in as this user and one by one deleted off his wall.

Then thought I'd just delete the user, deleted him then I found loads of posts still excisted in forums.

Problem then was , to other members it would appear I deleted this member to shut him up rather than resolve what was being said. As I rather resolving anything negative so users can see we are trying to help publicly, now it looks like I deleted this member and users don't know why I did.

I spent 3 hours cloning my site to then delete his entries on MySQL entries, just so I could test in a staging environment to make sure nothing went wrong, then redo it on the live server.

It would Be great when deleting a user, if a tick box option is present and says, do you want to delete all entries this user posted, with a warning saying past conversations may long make sense blah blah.

That would be awesome.

**Comment by amandablain** [comment]
I added this code in manually. I don't expect a response from the team here. They have decided its not a feature to code in even though its only several lines of code and users of their product constantly tell them otherwise and that it is needed for various real life and legal reasons.

The only issue is that it sometimes causes issues in a forum post if the deleted user posted something in the forum last. I needed to edit that code to manually check and edit with a blank spot instead of an error.  Otherwise.. no more spam and competitor and legal issues like everyone has mentioned. 

I can't stress enough how disappointed I am with the support team on this product and their complete lack of caring about the serious issues they create with their product. The lack of response to the very valid concerns that people raise here. "Get a developer to do it" is ridiculous when the core product is bugged and has serious design flaws.

**Comment by amandablain** [comment]
If you want to edit this yourself... tread carefully.. but the file you are looking for is application\modules\User\Plugin\Core.php the function is 21 onUserDeleteBefore - And you want to be adding in delete lines of code for everything that has been created. Many badly made plugins will also leave countless rows in your database so check them out too... 

Good luck.

**Comment by poeticjustice** [comment]
@amandablain thanks for the response it's very sad indeed, especially as all social engine developers REFUSE to edit core code and will only make plugins or themes.

If contacted the top known ones.
Social Engine Solutions are a great team and my goto developers because they have made me plugins which other developers said was impossible to do!

 But core! SE developers won't touch.

I can wok round some issues myself but not deleting users past data is a legal issue indeed, they can pay the government for like a freedom of information and what data I hold on them, and it could end up in legal dispute, that's why I had to put a clause in my terms so users had to contact me to removed, and one by one I manually remove everything! Soooo annoying

**Comment by smazurov** [comment]
>  as all social engine developers REFUSE to edit core code and will only make plugins or themes.
> But core! SE developers won't touch.

This is for good reason - they want to make sure you can upgrade to latest version without losing your modifications. The function in question is an extension point, if you take a look at `HelloWorld` module that I believe ships with your socialengine zip, you can see a `manifest.php` file that has this:

```php
  'hooks' => array(
    array(
      'event' => 'onUserDeleteBefore',
      'resource' => 'HelloWorld_Plugin_Core',
    ),
  ),
```
What that allows you to do is write some custom code that does the deleting that you want in your own module, creating a separate plugin that works independently of Core, retaining your ability to upgrade without any issues. 

We will be adding documentation in the future to better highlight on how to create your own modules and extend socialengine's functionality.

**Comment by amandablain** [comment]
you know @smazurov .. I'd accept that as an answer... If you created proper documentation on adding in code, editing code, creating custom pages, modules and plugins ... i'd be all for it. I have to go into dark parts of the internet to get any help for most things around social engine and that is a serious problem. 

There is no developers guide or help files beyond VERY VERY basic stuff. This guys blog from 2011 is the best resource and even he isn't complete on it all - https://jadb.wordpress.com/2011/01/17/socialengine-4-create-a-widget/ 

Half the 3rd party plugins i've coded are all made differently (and many very poorly) too.  If you don't want to fix  issues than work on creating help files that let coders fix them easier.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#11

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
