### ISSUE TITLE
User Activity Feed

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#224]
In SE 4.9 it was mentioned that there will be a way to adjust user notifications and search bar in mini menu. Is there a way to add a block for user activity feed updates? Search bar is a block onto itself, but in layout editor, it would be really nice to have a block for user updates as in recent notifications to put it on home page or something like it for member home view.

**Comment by shivani2910** [comment]
@Elshara, Since "Updates" link and Search bar are simply menu items, it's not possible to add them as widgets in Layout Editor. These are already a part of "Mini Menu" widget. And as we've already specified in 4.9's roadmap ( https://github.com/SocialEngine/phpv4-issues/issues/159 ) that you'll be able to re-position these also via menu editor.

**Comment by Elshara** [comment]
That makes sense. Thanks!
