### ISSUE TITLE
Paragraph Spacing

### ISSUE THREAD

**Issue by jbakuk** [SocialEngine/phpv4-issues#226]
I've been using Socialengine for over a year now and there has still been no fix of the paragraph spacing. This should not be an issue being something so standard and it would be fantastic if it was fixed in 4.9 as I get a lot complaints.

Spacing paragraphs requires pressing enter twice which leaves a huge space in the editor, I can use it that way as I'm used to it but site members end up with blogs etc. made up of one huge horrible chunk of text.

Great idea with the roadmap and the features within, the future looks bright for Socialengine.

**Comment by Elshara** [comment]
Plane and simple, social engine needs a new content editor. Something simple like raw html with basic functions would be just fine.

**Comment by jbakuk** [comment]
Agreed, I also have sites built on Wordpress, having to use the
Socialengine editor after using wordpress is awful. Surely it wouldn't be
much work to replace it.

Kind Regards

Jamie Baker

**Comment by pulsatemedia** [comment]
This seems to happen with the third party plugins too, so I can only guess that this is an issue stemming from TinyMCE, or rather however it has been implemented in SE?

Wordpress used TinyMCE also. I recall having similar issues with it in WP many years ago, but it seems to have been resolved on that platform.

**Comment by Elshara** [comment]
Tinymce hasn't been updated in years on Social Engine. In fact, social
engine has no plans to update it what so ever. No third party plugin
can interface with it directly as it is built into the core of the
system and I'm not skilled enough to mess with that aspect of it. You
cannot change anything about the editor in social engine.

**Comment by Elshara** [comment]
You cannot just comment out the editor because it breaks the whole site.

**Comment by Anshuse** [comment]
Hi All, thanks for your feedback! We're reporting this issue in our internal bug tracker and we'll see if we can find any better text-editor in near future. Thanks!

**Comment by Elshara** [comment]
Thank you! This would be so much better!
Even if tinymce was updated to the latest version there's so many
alternatives that are free to implement out there that are stable.
Even just raw html editor would be awesome for pasting codes. Never
mind with bb codes that and mark down this, there's html5
specifications
Google looks up to for sure. But, getting rid of php codes and
replacing the framework with something purely html reliant perhaps
with a few formatting buttons and a wyciwyg overhead like what Ning
has would definitely make this a lot better.
I do have some suggestions for this request you can look in to.
http://ckeditor.com/
http://nicedit.com/
http://tinymce.moxiecode.com/
http://developer.yahoo.com/yui/editor/
http://markitup.jaysalvat.com/home/
http://freetextbox.com/
http://cheeaun.github.com/mooeditable/
http://www.openwebware.com/
http://www.solmetra.com/en/disp.php/en_products/en_spaw/en_spaw_intro
http://jhtmlarea.codeplex.com/
For demos and downloads of these editors and to learn more click here.
http://www.1stwebdesigner.com/10-best-wysiwyg-text-and-html-editors-for-your-next-project/
Yes, there's others not from the list above and I'll share them here.
List 2.
http://redactorjs.com/
http://xing.github.com/wysihtml5/
http://jejacks0n.github.com/mercury/
http://www.scriptiny.com/2010/02/javascript-wysiwyg-editor/
http://elrte.org/
http://aloha-editor.org/
http://premiumsoftware.net/cleditor/
http://jhollingworth.github.com/bootstrap-wysihtml5/
http://jqframework.com/jqrte/
http://maqetta.org/
Demos, information and downloads are available from this link.
http://www.sitepoint.com/html5-wysiwyg/
List 3.
Unfortunately I'm not able to get the source links because the website
is incripting them but you can read about them here, demo and
downloads are available also.
http://www.jqueryrain.com/demo/jquery-wysiwyg-editor/
Other editors I've found try here.
https://www.froala.com/wysiwyg-editor
http://bestonlinehtmleditor.com/
http://quilljs.com/
This isn't an editor, but a great tool for online use.
http://textmechanic.com/
Try those links see what you think. I'm sure there's something that
works with functionality in mind.
I'll look around see if I can find some others.

**Comment by jbakuk** [comment]
Wow that's some list, good work Elshara.

SocialEngine it would be great if you could fix this for 4.9, it can't be
much work to implement and the customer satisfaction would far out weigh
the task. What are the chances?

Kind Regards

Jamie Baker

**Comment by Elshara** [comment]
Thanks. I have the funny feeling I know you from Ning.
Here's what I'll suggest. Try the demo links of the ones I gave you in
the source of the 3 lists I put down. If you like it, all you have to
do is download the source code and replace the editor see if it works
well. That job is for social engine. All the people leaving comments
like myself have to do is demo the editor in a new browser, see how
well you like using it and whether advanced functions work well on it.
Come on we need to try it out first hand although we can't save posts
to see how well they preview. If the editor has a preview function,
even better.

**Comment by Elshara** [comment]
I wish there was a way for us to swap out, switch or update such components as stand alone applications.

**Comment by jbakuk** [comment]
You do indeed Elshara, I guessed it was you with the name being unique. I
didn't want to clog the thread up with unrelated conversation though, hope
your well, feel free to email jamie@darkwhitedesign. com

Kind Regards

Jamie Baker

**Comment by Elshara** [comment]
Awesome!
