### ISSUE TITLE
Loading profile does not auto load Info Tab

### ISSUE THREAD

**Issue by swishemart** [SocialEngine/phpv4-issues#23]
When clicking a member profile the info tab used to load.  In 4.8.7 the info tab is not auto loaded and has t be clicked to be viewed.

**Comment by shivani2910** [comment]
Hi @swishemart, 

Sorry for the delay in responding to you. We would like to tell you that we've not done any such work in 4.8.7 that may cause this issue. We request you to go to Admin > Layout > Layout Editor > "Member profile Page" section of your site and make sure that "Info" tab is placed at the top inside the tab container. If not, then please drag and drop it at the top of the tab container and save changes. We hope your problem will be resolved doing so.

Also, we're glad to tell you that we've released SocialEngine PHP 4.8.8 recently: http://blog.socialengine.com/2015/03/23/socialengine-php-4-8-8-released/ and fixed many issues that came due to specific settings and 3rd party modules after our last release 4.8.7. So, you may upgrade your website to 4.8.8. For details on upgrading, you may refer to this article:
http://support.socialengine.com/php/customer/portal/articles/1666869-performing-upgrades

If you face any issues, please feel free to connect to our support team by filing a support ticket from your account's dashboard.

Thanks & Regards,
Shivani
