### ISSUE TITLE
Ability to Change Profile Type After Sign Up

### ISSUE THREAD

**Issue by BikersPost** [SocialEngine/phpv4-issues#243]
We offer two different profile types ie: Individual and Organizations. Each with two very different set of profile questions. Once in awhile a member will join and select the wrong profile type and the only option for them is to delete their account and start over. It would be great if they where able to simply change their profile type after singing up instead.

**Comment by troydbertrand** [comment]
I ran into the same problem but found out that member profile type can be switched via the MySQL database. I'd appreciate it if SocialEngine made changing member types easier.

You can change profile types by running the following database query: Replace "the ID of the profile type you'll like to use" and "Old Profile ID" with actual values.

UPDATE `engine4_user_fields_values` SET `value` = 'the ID of the profile type you'll like to use' WHERE `engine4_user_fields_values`.`item_id` =Old Profile ID AND `engine4_user_fields_values`.`value` =1 LIMIT 1 ; 

PS: BikersPost is a legend. It's the first major network that I know of to migrate from Ning to SocialEngine. We'd love to have Kris on Ex Creators (excreators.com/community)

TDB
ExCreators.com

**Comment by shivani2910** [comment]
Hi @BikersPost, currently there is no way to update profile type after user has logged-in on site. This is because we ask user to fill in his profile information as per the profile type selected during signup.

If you want to change the profile type of a particular user, you can do this manually by running a sql query as mentioned by Troy in above response. I would just like to clearly define the parameters involved:

UPDATE ```engine4_user_fields_values``` SET ```value``` = 'the ID of the new profile type you'd like to use' WHERE ```engine4_user_fields_values.item_id``` =User ID of the member AND ```engine4_user_fields_values.value``` =Old Profile Type's ID LIMIT 1 ;

For ex, if you want to change the profile type of super admin(whose item_id is 1) from "1" (Regular member) to another type whose ID is "4" as per table ```engine4_user_fields_options``` then you would need to run below query in database:

UPDATE ```engine4_user_fields_values``` SET ```value``` = '4' WHERE ```engine4_user_fields_values.item_id``` =1 AND ```engine4_user_fields_values.value``` =1 LIMIT 1 ;

Hope that helps!

Thanks

**Comment by Elshara** [comment]
This should be as easy as either one of two ways. Subscription based or admin editable in control panel. If profile information is changed, it should automatically import existing tables like first name or last name if available until the user updates their profile again. This is a feature I thought already existed within social engine, I guess not.

**Comment by Elshara** [comment]
Another way this could be implemented is if profile types were integrated into member levels. That I know can be changed in the members edit section of member management. There may be a plugin to do that on social engine. There is I just found this.
http://www.socialengine.com/customize/se4/mod-page?mod_id=247
Try creating member levels with the same name as the profile type then install this see if it helps. There should be a way to isolate or reverse the process through this plugins code if you edit their member level, it should change their profile type.

**Comment by Elshara** [comment]
If you just want their profile questions to be changed then all you would have to do is use a temporary subscription and link it to the profile type of the member you want to change. Presumably using subscriptions you should be able to mediate the member profile without having to enter the database directly there has to be a way for it to be carried over. Cross profile type linking should be mediated through subscriptions. If not then the whole idea of a subscription and profile type relationship kind of interferes with each other, unless subscriptions are more geared towards member levels. In which case profile types are ignored altogether leaving only one solution. A plugin or way to cross reference profile types with member levels, or get rid of member levels altogether. Either way linking the two shouldn't be that hard if a member level could be dedicated to one profile type and it could automatically make the transfer.

**Comment by troydbertrand** [comment]
@smazurov, @shivani2910 : This issue should have been given the "Enhancement" label and should be strongly considered as a candidate for release in v4.9. Issues such as this may seem small and restricted to being a pet peeve of the minority but a lot more people than you think get frustrated over the inability to change a member's profile type post signup. 

For one thing, people make mistakes at signup but the bigger problem arises when I member has outgrown the profile type chosen at signup.  Let's take a look at [Ex Creators](http://excreators.com/community?utm_source=GitHub_GitHub&utm_medium=GitHub&utm_campaign=Comments) for example. There are a few profile types available at signup but we'll only take a look at two; "Platform Newbie" - This type is chosen by members who have no experience with social web platforms. "X-Creator" - Chosen by members who've had experience with at least two social web platforms.  

A member signing up as a "Platform Newbie" has the potential to become an "X-Creator" over time...maybe in as little as a few months. I'd like to be able to change a member's profile type without having to run database queries. This is merely an inconvenience for me but for others it could mean spending money the may not have to achieve something simple.

Please consider reopening this matter.

Best Regards
TDB
[Ex Creators](http://excreators.com/community?utm_source=GitHub_GitHub&utm_medium=GitHub&utm_campaign=Comments)

**Comment by Elshara** [comment]
Truth is, ability is already there. Subscription packages offer this
functionality but if we could find a way to cut out pay pal from the
mix, we'd have it. I made a suggestion of a member level promotion
system not too long ago to target spam bots. Though unrelated, profile
types themselves could cause significant decreases in this activity
simply because we could set one up relating to member levels so people
could be given access to more development discussions based on their
level of what their profile type is by aligning profile types with
member levels. A plugin exists already to be able to do this, however
the feature isn't an official one. I say this because user groups
define what people have access to, just reading peoples profiles won't
change this, but integrating it with what they have access to by
having them have separate profiles altogether but still remaining
apart of the same network, could. This could prove very useful in
member to member communications as well.

**Comment by SpiritWolfie** [comment]
is there any way to do this on a mass scale, I had no idea you couldn't change profile types after I started creating a custom profile, and now everyone using my custom profile type can't edit their about me section...

**Comment by Elshara** [comment]
Create the sections for both profile types with similar questions so
that they can do this. Be sure to make both profile types unique if it
matters that one is different from the other depending on what you
want users to select.
