### ISSUE TITLE
Styled Mails

### ISSUE THREAD

**Issue by wtoalabi** [SocialEngine/phpv4-issues#249]
The greatest challenge facing any owner a social community out there is retention.
Its one thing for people to sign up and hang around for a couple of days...but ow do you convert the same to ready made, continuous user of the platform.
That is the nadir...the holy grail.
But to help in achieving this, I believe there is a need to add more style and finesse to the mails going out.
I mean the default normal mails like Notifications, updates, etc.
Every of the major guys out there are doing it.
I find it difficult to believe that SE comes out that bland and boring.
Can we please do something about it.
And no, there are no third party plugin offering this.
Thanks!

**Comment by troydbertrand** [comment]
I think you guys should explore your SocialEngine installation a little more and make use of the vast and detailed documentation found in the knowledgebase. 

"Every of the major guys out there are doing it.
I find it difficult to believe that SE comes out that bland and boring.
Can we please do something about it."

Yes you can do something about it and it doesn't require installing a plugin. All you need to do is add some basic HTML to your mail template.

This is what my outgoing mails look like: http://excreators.com/community/public/admin/Syled-Mails.png

I'm not done styling my templates just yet but this is a good start...at least it is to me.

TDB
excreators.com

**Comment by wtoalabi** [comment]
Thanks!

But will you be kind to share where to look?

I cant seem to find it...that was why I asked.

Thanks again!

**Comment by troydbertrand** [comment]
My fault for not sharing the link. Here it is: 
http://support.socialengine.com/php/customer/portal/articles/1639902-admin-panel---settings-%3E-mail-templates?b_id=4311

SocialEngine Support site seems to be experiencing some server issues so you'll need to try again later. 

You should take a look at this forum post over on Ex Creators - "Getting Started With SocialEngine PHP". It provides you with an organized list of the steps I recommend taking after installing SocialEngine PHP. 
http://excreators.com/community/forums/topic/16/getting-started-with-social-engine-php

Regards
TDB

**Comment by troydbertrand** [comment]
I should mention this...My first may be a little bit misleading. SocialEngine doesn't actually provide you with instructions on how to go about getting your mail template to "look like mine". If you don't know how to do this I can provide you with guidance. 
http://excreators.com/community/

TDB
excreators.com

**Comment by wtoalabi** [comment]
I will.
Thanks!

**Comment by Elshara** [comment]
Re: styling of mails, content updates should appear in existing member updates mails but instead they are just given the link to view the update. In which case this will need to be a structural change not a template change. In some cases, the emails are so basic it is just a notification with a link to view what has actually been said. No content updates are available.
For example. This is what a friend request email looks like. No images, nothing.
Hello receiver,

Sender has approved you as a friend. Please click the following link to sign in:
Followed by a link to the receivers profile.
Shouldn't it say something along the lines of.
Hello receiver,

Sender has approved you as a friend. To access your friends list, click the link below
http://examplenetwork.com/friendslist
Visit network name at http://www.examplenetwork.com
To control which emails you receive on Network Name, click here. http://www.examplenetwork.com/settings/emails
Something to that equivalent would make it a lot more readable. Every other content email is the same whether it is about new personal messages, someone liking a post you liked, someone commenting on a post you commented on, or someone liking or commenting on a post you have shared. They all give the link to the content item, rather than just explaining more about the post.
It would be nice if new comment emails contains the contents of the comments and the likes emails contains something more than just a link since you cannot really view who likes your post on the site, all you have is an email, and you do not get emails notifying you if someone else likes your post, unless you are the posts creator. An email stating someone likes a post you like would make this go away, but even then, you should be able to receive some form of email text notifications.
