### ISSUE TITLE
Line breaks in comments 4.8.9

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#252]
This is in response to the closed issue: 
- https://github.com/SocialEngine/phpv4-issues/issues/40

here's a pic to show
- http://postimg.org/image/i6zz26qjt/

While this issue is almost fully resolved, (it works if your the person making the post) but does not do line breaks if you are responding to a post. 

any way to quickly fix this so it works on reply's as well?

**Comment by shivani2910** [comment]
Hi @SpiritWolfie, we've checked this issue at your end but unable to reproduce this. Also, this is not a known issue and line breaks seem to be working fine in comments. Please find attached screenshots.

![comment1](https://cloud.githubusercontent.com/assets/7815961/9324856/a05e9ff2-45ab-11e5-9b76-c2dbb82c24df.png)
![comment2](https://cloud.githubusercontent.com/assets/7815961/9324858/a169ce6c-45ab-11e5-9b06-d2a41ae4ae9c.png)

Since this issue has not been reproduced or reported by other client, it seems to be something specific to your installation. If you want our team to look deeper into this problem at your end, you may file a support ticket. Thanks.
