### ISSUE TITLE
Comment, Like And Share Not Working On Activiy Feed 

### ISSUE THREAD

**Issue by javatech20** [SocialEngine/phpv4-issues#26]
On version 4.8.8  the activity feed is not showing the "Like, Comment And Share" options at the bottom of status posts to users who didn't post the status update. The "Like, Comment And Share" options are shown to the status update poster in the activity feed but not shown to other users in the activity feed. This bug we noticed after we upgraded to Socialengine 4.8.8.

**Comment by shivani2910** [comment]
Hi @javatech20 ,

This is not a known issue in SoicialEngine PHP 4.8.8. Also, it has not been faced or reported by our other clients. But since you're facing this issue on your installation, our team will need to look into it deeper to find out the cause. So, we suggest you to contact our support team and they will assist you accordingly.

Best Regards,
Shivani
