### ISSUE TITLE
Facebook & Twitter registration button on registration page

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#263]
I wonder why am I not seeing the Facebook & Twitter registration buttons on the registration page? I only see them on the Login page of the site?

Is it that I am doing something wrong or SE team does not think that these button should be there on the registration page?

Please advice!

**Comment by shivani2910** [comment]
Hi @meetgerry We do not display Facebook and Twitter login buttons on  signup page because that's not required. We simply display them on login page and if user do not have an account on SocialEngine site corresponding to his Facebook/Twitter account then we redirect him to signup page with some information pre-filled on signup form. Hope you get our point here. Thanks.

**Comment by meetgerry** [comment]
Thanks Shivani.

I seriously do not understand your logic, may be I am that lame in understanding.

Any new user would first click on REGISTER button and not the LOGIN button. And when he clicks on the REGISTER button he is taken to the registration page and there he only has the option to register using the builtin signup process.

What if the user actually would prefer to register using Facebook or Twitter? How would he know that he should click on the login button and go to the login page to play around there till he is redirected to whatever?

**Comment by meetgerry** [comment]
And please do not close issues till this understood and agreed by both sides as either resolved or flagged not an issue.

**Comment by Elshara** [comment]
I never use those functions. It's not that they don't work, but it's too confusing for users even if enabled to know what to click on if they know they already are registered.
