### ISSUE TITLE
Notification email Digests

### ISSUE THREAD

**Issue by pulsatemedia** [SocialEngine/phpv4-issues#264]
Enhancement rather than a bug.

While we have the ability to set notification defaults for our users, and they also can change their notifications settings, striking a balance between them getting the notifications and pounding their mail inbox is a struggle. Especially for new members of your community. You need to inform them of activity, but also not abuse the trust you have given them with their email address.

We need our users to be engages and updated of course. They need to know if content has been liked, shared, commented on etc etc, but an email for each one is excessive.

I'd like to suggest that updates for community member be communicated in email digests. Set to daily or weekly. This way they see all of their activity, without getting email message after email message.

Hire Experts' newsletter plugin does this to some extent, however I am talking more about many of the items that would appear in the mini menu. Likes, comments etc etc.

I believe this would be a significant enhancement for user experience.

**Comment by Anshuse** [comment]
Hi @pulsatemedia , Please be noted that Email Notifications are action based i.e email notifications get sent to site members on the basis of action performed by them on site. Now, if you want to alter the way in which email notification should be sent to site members then you may customize the code at your end as per your requirements. Thanks!

**Comment by pulsatemedia** [comment]
From your response, the breakdown in communication here is concerning. I think I demonstrated an understanding of why users get email notifications based on their actions on the site. That is exactly the problem I described. Currently there is a 1:1 ratio of notification:email message

It's intrusive and excessive. The user still needs to be informed of their community activity, however these notifications need to be in the relationship of Multiple notifications > Single summary email

I am aware of how customization can be done and their purpose. I am also aware of how that often breaks upgrade paths and causes issues further down the line.
 
Notifications are a core part of a social networks/online communities and from an outside point of view a core part of the socialengine product functionality

If this cannot be considered, I would be interested to hear the rationale behind that point of view.

**Comment by Anshuse** [comment]
Hi @pulsatemedia , We understand your concern here and we're sorry as we don't have any plan to implement this feature in our core module but we're forwarding your suggestion to our team and will take required action after internal discussion on this. Thanks!

**Comment by Elshara** [comment]
Yep we need this feature. Email digests are a good way to keep email costs down if paying for an off site email server. Even if members received one email per week with all the members of your site taken into consideration, it would drastically lower the resources used for server communication. A lot of times we get server complaints because there are too many emails flooding their service and we just don't have the funds to keep an updated email server going. Even on a site with 200 plus members on it there are bound to be unstable email floods especially because of the high server usage social engine uses. Cloud services are lower quality and higher to maintain both cost wise and resource wise as they rely on one system of networks to be constantly working normally, not just one server instance.
