### ISSUE TITLE
Facebook & Twitter registration button on registration page (Recreated because this ticket was closed without solution)

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#265]
Ref reply by Shivani: Hi @meetgerry We do not display Facebook and Twitter login buttons on signup page because that's not required. We simply display them on login page and if user do not have an account on SocialEngine site corresponding to his Facebook/Twitter account then we redirect him to signup page with some information pre-filled on signup form. Hope you get our point here. Thanks.
# 

Thanks Shivani.

I seriously do not understand your logic, may be I am that lame in understanding.

Any new user would first click on REGISTER button and not the LOGIN button. And when he clicks on the REGISTER button he is taken to the registration page and there he only has the option to register using the builtin signup process.

What if the user actually would prefer to register using Facebook or Twitter? How would he know that he should click on the login button and go to the login page to play around there till he is redirected to whatever?

And please do not close issues till the issue is understood and agreed by both sides as either resolved or flagged as not an issue.

**Comment by pulsatemedia** [comment]
Users do not like to fill out forms, that is the point meetgerry is trying to make. The registration form is a friction point for signup.
Manual entry is never desirable. Some signups fail because of small typos in email address for example. They assume your site is "broken" and don't come back.
A signup with facebook icon would help increase trust/authenticity as well as streamlining the sign up process.

I can't speak for the amount of work that would be invloved to implement it. But from a user experience standpoint signing up for a website and or service via facebook, google or twitter has become the norm.

https://www.google.com/search?q=signup+with+facebook&espv=2&biw=1345&bih=852&site=webhp&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMIp5_bkr3JxwIVBE-SCh0lWwyU

**Comment by meetgerry** [comment]
This is the second issue created with the same flaw highlighted. Previous ticket was blindly closed with some illogical answer. Shivani meant that registration though social channels are not required, instead we only need to have social logins buttons on the login page.

I do not understand why will anyone think of even clicking on login button if he is a new user and has not registered.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#13

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
