### ISSUE TITLE
Theme/plugin compatability

### ISSUE THREAD

**Issue by dave1966uk** [SocialEngine/phpv4-issues#274]
Hi

Perhaps it is just me or my bad luck but I seem to find a theme I really like and then find that certain plugins/addons don't display correctly, or vice-versa.  I contact the theme producer who says it is the addon producers fault for spraying CSS all over the place. I contact the addon provider and am told the theme designer is not following the guidelines.  Some theme developers will modify the theme for free but they want admin access (tried this once and another part of the site went wrong), whilst others want to charge for fixing a problem that "isn't theirs".  For me as a site owner it is costing me time and money purchasing various plugins and themes just hoping they might work together. It is at a point where I will have to decide whether to continue with SocialEngine as patience is wearing thin.  I have had to just raise two tickets, one with a theme creator and own with a plugin provider asking whose CSS is making part of the site unreadable.

Please can a theme structure be created that can be carried to the addons without the addon providers feeling the need to use their own CSS which may have unforseen problems.

David

**Comment by meetgerry** [comment]
David, you are not the only victim here. There are thousands who are left helpless. SocialEngine does not control any third party plugins even though they allow them to sell their untested plugins using their addon section. SocialEngine says that they are coming up with some new marketplace that exercises control on third party modules. Though the third party developers are unreliable, you still can go with SocialEngine with the core features.

**Comment by alimoosavi15** [comment]
The issue happens when a plugin uses the css class names from core plugins in PARTS of their code. They copy PARTS of SE code ( CSS class names or DOM elements ) into their plugins to shorten the development time thus the visual issues happen. for example in a news feed plugin, the plugin developer uses SE class names for the comments parts and their own class names for the input box so it will have the styles from 3rd party theme for the comments part and plugin developer's styles for the input section!

Plugin developers should either use ALL the DOM structure from SE ( Not practical ) or write their own DOM with their own CSS class names for everything so their plugin won't have mixed styling.

When they mix the css class names from SE with their own css class names in their code, it gets messy. Me as a theme developer can't do anything about it but plugin developers can write their code without the shortcuts. It will take them more time but this is the solution.

This issue is not for SocialEngine alone, it happens in most CMSes.

**Comment by SpiritWolfie** [comment]
I know this old and out dated but could anyone perhaps shed some light on this for me

en4.core.runonce.add(function() { en4.advancedactivity.bindEditFeed(1963, { lang: { 'Post Something...': 'Post Something...' }, allowEmptyWithoutAttachment: 0 }); });
en4.core.runonce.add(function() { var plugin = new Composer.Plugin.Aaftag({ enabled:true, suggestOptions : { 'url' : en4.core.baseUrl+'advancedactivity/friends/suggest-tag/includeSelf/1', 'postData' : { 'format' : 'json', 'subject' : en4.core.subject.guid }, 'maxChoices':'10' }, 'suggestProto' : 'request.json' }); document.retrieve('editComposeInstance1963').addPlugin(plugin); plugin.mapTags([]); document.retrieve('editComposeInstance1963').setHighlighterContent(); });

We get this when trying to switch from midnight to Slipstream, Allot of my users like slipstream because midnight is to dark, but it seems to throw this into the wall posts anytime anyone posts and is only visible by the user making the post.

**Comment by DonnaScriptTechs** [comment]
As this relates to third party issues, we'll close it for now and will have a look at this for our Certified Marketplace that should open soon.

**Comment by Elshara** [comment]
Awesome!
