### ISSUE TITLE
Improve How Profile Photos Are Uploaded

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#303]
In social engine, it is not possible to reupload something that has already been posted. For example, if a member uploads a profile picture, and they do not like it, their uploaded profile picture is already live until they upload a new one. This means any photos they upload before the new one are still on the server and over time, these can add up causing increased loads on the server and database. IF this is true for photo uploads, I expect failed music and video uploads work similarly.

**Comment by Anshuse** [comment]
Hi @Elshara , we didn't exactly understand your point here. In SocialEngine, if a user doesn't like his/her current profile picture then he/she can delete it and upload a new profile picture. Can you please let us know what exactly is your doubt/point here.

**Comment by Elshara** [comment]
Yes. The current profile picture has a unique id that isn't maintained
when another one is uploaded.

**Comment by Anshuse** [comment]
@Elshara , it seems that Albums module is not enabled on your site and when any user uploads a profile picture during the sign up process but later on if user changes his profile picture then the photo uploaded at the very first place (i.e. during the sign up process) doesn't get saved anywhere and is not available to be set as a profile picture again. This is because when any profile picture is uploaded then that picture gets saved in the Albums and if Albums module is not enabled then picture will not be saved anywhere. That is the reason we have provided Albums module in our starter package also.
Thanks!
