### ISSUE TITLE
Alter Database Fields To Automatically Resize

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#311]
It would be very useful for a plugin manager for example to manage database fields as well as enabling and disabling a plugin. For example, if you use a third party product for some time but decide to disable it, all of its pages still come up in layout editor along with their menus and as such it adds extra queries to the database. Additionally, if content gets removed or deleted, it still remains an item in the database meaning failed uploads, removed profiles and content still have a permanent space in the database even though they cannot be recovered. It would be nice to recover backup fields in this way but they should be stored in a completely different table. All plugins or a core setting should control what gets backed up into the database so it keeps data entries nice and orderly.

**Comment by Anshuse** [comment]
Hi @Elshara , 

Regarding "content":
When any content is deleted from the site then entry of that content gets deleted from the database as well. And, when user gets deleted from site then content that belongs to that user also gets deleted from the site and corresponding entries of that user's content gets deleted from the database too. If this is not the case at your end then there's must be some issue on your site.

Regarding "Plugins":
When any plugin is disabled then their widgets don't get removed from the Layout Editor because it requires a large number of complex queries for system to find out which all widgets of that plugin are placed on which page and then delete it. That will eventually affect the performance of site. So basically, when a plugin is disabled then widgets don't get removed from the Layout Editor and their image remain over there and if you delete or remove these widgets then it will have no effect on the system.

Thanks!

**Comment by Elshara** [comment]
Ah. That was what I was hoping was the case the exact opposite of what
you have described that it would use the database to clean up a
missing plugins layout because they can't be deleted or edited if the
plugin is disabled. Took me a long time to figure that one out. You
have to reinstall a plugin just to remove a widget you don't like then
remove it from all sub entries and sub sub entries from the database
including the pages, the cron jobs if they have them, it's a really
messy business. I was hoping for the reverse of content, that if you
wanted to restore content you could do so from the database. I mean
the files still remain on the server if it is photos but the database
it's gone for ever, its stupid to have to back up a database just to
try to add back what may have been lost manually I mean how do you
know if a member is wanting to leave. I think members should require
approval to just remove their accounts and content one day.

**Comment by Elshara** [comment]
I think people should be able to set how they want database entries to
be managed by social engine, manually or otherwise.
