### ISSUE TITLE
Make Licensing Easier

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#327]
Social engine doesn't currently the ability to manage licenses in a convenient way.
For one thing, the license key is displayed every single time you look at the dashboard. It displays to all admins, it makes nulled software possible by figuring out how licensing works using a global algorythm and is generally an outdated idea.
What's worse is that all plugins currently if they are required to have a license, using a core plugin just to validate a licensed product each and every time the plugin is called. This wastes so many resources it isn't funny. What would replace all that, would be a dedicated license manager for social engine.
This would be in place of all the third party core plugins so that the actual plugins would run a lot smoother and faster on the site. Younet, social engine addons, ceofox and a host of other companies require core plugins who's primary function is to maintain a license. Social engine itself doesn't have a secure way to verify licenses either, which makes a license manager more of a necessity particularly when it comes to random key protection.
The license manager could support more than just licenses. It would be able to support database queries and their handling, the ability to monitor statistics in an easier way using cron jobs, the ability to ensure each plugin is integrated with social engine access terminals such as the comments, admin features and other areas, as well as make loading of essential files a priority like all css and javascripts merdged into one as an optional feature so that all html is not using file after file to verify item contents.
The license manager would be a maintenance area designed for social engine to improve the way things appear on the site which would include things like a database editor, cache manager, statistics monitor, directory protector, sitemap to database converter and other tools that make social engine function fast, efficient and safe.

**Comment by Elshara** [comment]
Using the license manager, it could even be possible for someone to connect to socialengine.com to verify client id so that when ever a new update of social engine or other plugins that require a license or some kind of payment verification are available, they will be ready for automatic download without having to upgrade packages and waste time with ftp info. It would all be saved in this one plugin.

**Comment by playmusician** [comment]
Great points Elshara. Hope they can impliment it.
Im a newbie at SE, and just developing my portal - playmusician.me.
I have used all SEAO (Social Engine Add Ons ) Plugins. 

Would like to stay in touch as I am struggling with their plugins due to their lack of timely Customer Support. 
Thanks & Keep up the good work!

**Comment by Elshara** [comment]
I find them a little confusing two.

**Comment by meetgerry** [comment]
I second Elshara

**Comment by Elshara** [comment]
Thank you. <3

**Comment by smazurov** [comment]
We've certainly been thinking about this as well. Does communicating with SocialEngine.com to validate a license something you guys are ok with? We would not do it constantly, but once in a while (once a day, likely). Any other resources (such as software that does it well) would be helpful for us to look at as well.

**Comment by Elshara** [comment]
The problem with a licensed product, is that people hack it. You lose
money and you more importantly, lose a customer who would otherwise
have bought a stable, more secure, product. Money is taken seriously
in a lot of companies. Microsoft most notably, refuses to give updates
to people at least they did in windows 7, if no valid license was
detected. Social Engine could work similarly.
I'd be perfectly fine if a license check happened once a day. This
could also mean not just licensing would be checked on
socialengine.com, but updates as well. They could install
automatically if a new update or upgrade is found via ftp, and then
developers could simply ensure if their products contain a core, that
their updates are fully licensed by email verification of their
products.
Lets stop piracy in its tracks. Sites like socialenginehelp.com and
socialengineforum.com among others are very used to hackers, crackers
and people who complain about paying for software. Unfortunately, this
means software developers don't get the money they charge for to
further development of said products. Now I have no problem with
people asking for support on fan forum sites, but when it comes to a
risk of violating developer and company terms, particularly where
malware is involved, well I'd say a valid license would solve
everything by making sure it has an associated email and regularly
updated password adjacent to it.
BTW, the reason why piracy exists is because people can't afford
current pricing. Lowing it would mean more customers pay more money
for social engine and all of its updates. I'd say a pricing change
would help also with verification of licensed products. Temporary
licenses would ensure people who paid the product get updates, and
recurring fees for a license ensures free support and therefore
invalidates current license so if a hacker got a copy of social
engine, its license would only be associated with one domain and one
email so before the installation could even begin, there'd be a
temporary license check. This is similar to how the trial software
works, but instead of having files expire after a month, they would
simply renew with a different temporary license. Additionally, such
licensing could be made as a cloud license, meaning other developers
could sell their products through a cloud marketplace all covered by a
repaying license and then an affiliate program could be based on sails
through that, to give to them and vice versa every time a product is
bought through them or social engine.
Just a thought.

**Comment by rwetzlmayr** [comment]
> Does communicating with SocialEngine.com to validate a license something you guys are ok with?

I'd rather not.

**Comment by smazurov** [comment]
Those are fair points. I'm not certain if there is any alternatives.

**Comment by gsf00001** [comment]
For the most part, I'm with Elshara on this (thank you for creating this post).
- I have no issue with contacting SE Servers 1x/day to verify all of my licenses and flag the appropriate parties of any violations (notice I said flag - I don't want my site shut down since a 'violation' may actually not be one.  Much better than 150+ Plugins checking constantly throughout the day, and then occasionally erroring out if there's an issue.
- I would prefer to not have updates automatically applied (this could be optional - much like Microsoft and many other vendors do).  I simply prefer to backup and test prior to implementing updates.
- I would like to be notified of updates, or at least have a page (like some SE Devs include) that lists what's new for ALL licensed Plugins
- I agree/disagree with the issue of 'can't afford current pricing'.  'Afford' is a relative term.  Yes, all of the Plugins I've purchased adds up to a lot (to me), but each and every one of them is worth many times over what I paid for them (both in benefit/functional value and obviously actual hours required to custom dev them).  Although I do understand that lower prices should equate to more Admins purchasing software.

==>"This is a typical anti-pattern which punishes honest license holders while pirated copies will certainly be "nulled" in the blink of an eye and save the dishonest users from this annoyance."
We honest license holders are already being punished - the anti-pattern is constant resource usage due to Plugin key validations (among other things).  If SE comes up with a way to prevent nulling Plugins, allows us honest Admins to use our purchased/licensed software in an easier and/or more efficient way, and prevents pirates from stealing software then I'm all for it.

**Comment by Elshara** [comment]
What you are talking about would need to require a core update to
check whether or not a plugin has a license check. If one does, and is
delivered via an optional cloud update, then it could be safe to say
in order to install any plugin client area information, username and
password would need to be entered before the associated domain name
and license could go through with completion. This would eliminate the
need for any plugin to have its own core for licensing purposes and
would allow commercial and any other trusted safe social engine
developers who make sure their products are up to date to be able to
make updates to the plugin on a cloud server. That way it takes less
server load off the database of the local server to connect and make
api calls to the actual license server to ensure if any false
positives are encountered, they are reported to the license holder and
to the software developer for further investigation.
having cloud updates would ensure plugins can be installed, removed
and purchased with ease and securely able to provide updates without
much fuss if you want automatic updates to happen via task scheduler.
You could do this by providing ftp information for example in the
package plugin manager perhaps as a new global setting to ensure your
server supports automatic updates. It would also be very useful for
developers to test plugins so having an admin only access mode for
those plugins would make sense in this way. Automatic tracking of
payment would ensure plugins get up to date as soon as the update is
available, rather than having to manually upload files each and every
time. Automatic database synchronization would prevent people from
manually going into the database and uploading an older version of the
plugin which may or may not be nulled making it virtually impossible
to null it because if any database columns were changed or updated, it
would have to be done through the package manager because there would
be a regular core dependency check within the task scheduler to make
sure perhaps once a day, all systems are running smoothly and
efficiently.
Legally it should be able to check whether or not a plugin is licensed
or not by verifying email and domain information via plugin
dependencies. This wouldn't be a violation of privacy if you have
nothing to worry about and you paid in full what you are required to
if a plugin is not free, most are not and if a third party could check
to make sure the payment was not fraud. Most third parties would have
to do is update their license check information to social engine cloud
license server for all domains making it ideal for this purpose.
The only secure way to prevent a null instance of a plugin running on
an existing domain is to ensure its dependencies connect to a third
party server where information on active instances for live and local
sites can be reviewed. Technically it would be possible to include
localhost instances as well if you are in communication with the
developer of the plugin about offline versions of the software, but
you'd have to update your IP address to be able to do that. Or have
admin only mode enabled for such a purpose if on a live server.
The current license information is so easily nulled at the moment
because all that is currently required to install social engine to
start with, is a set of numbers and letters. Essentially, a hash based
password that isn't even encrypted which means anyone can override it
because of whatever mathematical based equation required to test it
against the software itself, because it is only a localized
installation. This includes but isn't limited to trial copies as any
information can be overridden via database queries and local files
respectively. This is the case for any software package installed and
is not limited to social engine. Therefore a lot of piracy happens
because of how the data can be accessed because all the dependencies
are local and unique to every installation.
This is why so many third party developers seem to have trouble with
their software being cracked all the time and this includes non
website related purchased products. To overcome it, an internet
connection is required. In this day and age, especially if running a
web server, failure to provide inaccurate information can be easily
traced and tracked for any offending party involved. All that is
required is third party managed system updates where in order to
upgrade to something, it has to be done remotely through a secure
secondary server interface. Once it's uploaded, because any dependency
check has already been passed, within reason, you can make any
customization you want. Keep in mind however some dependencies must be
file based so that overriding database queries can't just take offline
license checks.
Everything done on the web is a mathematical priority whereby anyone
who wants to hack a server must first be able to connect to it and
establish a common leak in requirements for anything to be able to
run. For propriety information to be secure, it must be stored
securely. Updates work in the same manner. A hacker can only work with
what a hacker has access to, so if that means encrypting social engine
software and plugins to require updates to a remote server to ensure
information is up to date, then so be it. Paid open source products
never work, because open source is not secure and is usually a
marketing scheme free software providers try to lure people into
buying because paid software providers usually are too successful at
not wanting their clients to believe they are Incompetent at keeping
up to date with features and other web related maintenance. For both
coders and website visitors alike, we admins do a lot to maintain our
privacy online and having a licensed secure way to provide updates and
receive updates in such a way that it means we are better off because
nobody can get access to our information, the better. I say this
because any security leaks are temporary meaning systematic updates
automatically ensures access codes are only valid as a secondary
password system found in a licensed client area of any domain to have
support people ask for it if needed to do customizations based on
other requirements plugins don't otherwise provide.

**Comment by poeticjustice** [comment]
I dont know if i like the idea of social engine checking each day with SE to check the licence.

What if SE site has error 500 as last week I noticed.

What if they are updating their site like they previously did.

What if Social Engine went under and shut up shop.

Would this all mean the site goes down also because it cant validate each day

**Comment by gsf00001** [comment]
@poeticjustice I don't like the idea of SE checking each day, but I'm open to options.  What I don't like (or trust) is 3rd-Party Devs doing this, and the performance, security, and other risks involved.  I trust SE to be the 'police' here, rather than dozens of 3rd-Party Devs.  

To resolve some other items you mentioned could be as simple as when your site checks, if it doesn't find SE (for whatever reason - their site errors, closed shop, etc.) then nothing happens.  In addition, the outcome of whatever is checked for validation should simply be reports/notifications NOT actually shutting your site down or shutting down access to your Plugins.  Just like reporting members on your site to you as Site-ADMIN which you then look into and control, something similar could be done for licensing.  Any solution to meet all objectives will be a compromise somewhere and not be 'perfect'.  What I'm hoping for is something better than what occurs now, is less risky (in many ways), and eliminates the constant performance hit to my site.

**Comment by gsf00001** [comment]
Another method for monitoring offending sites is a point-based system.  Since there are many valid reasons why a legitimate site may not 'validate' properly, total points could be what raises the red flag on offenders.  Here's a concept (just spit-balling here based on past software applications; open to suggestions):
- License check proves license is INVALID = X points added to VALIDATION1 License total (i.e. 'bad' points)
- License check doesn't prove anything (doesn't reach licensing server, etc.) = X points added to VALIDATION2 License total (i.e. 'neutral' points)
- License check validates legitimate license = X points added to VALIDATION3 License total (i.e. 'good' points)

These 3 data-point totals should provide SE and 3rd-Party Devs with useful info to determine who they should look into (again - no automatic shut offs, just who's most likely 'good' vs. 'bad' as far as valid licenses go).  Devs can decide on their own which VALIDATIONS and total points they wish to monitor.  We Site-ADMINS can also monitor this and if something doesn't make sense (eg. a legitimate license that is repeatedly flagging as VALIDATION1), we can address it before it turns into a problem.

There's obviously more 'policing' to this to control which Plugins should no longer be licensed and if/when they are changed to valid licenses, but the above is just a starting point.

**Comment by Elshara** [comment]
I've been thinking about this idea two recently ... and one of the
things which comes to mind is the possibility of an unity system.
Official license holders of any product relating to social engine,
requiring a paid plug in, should require a safety check and
compatibility check prior to being attached to your social engine
license. Third party developers wishing to sell in the social engine
marketplace, will have to tie their products to a social engine
license in order for it to be activated. Which eliminates the
possibility of domains being the source of the approval technique of
all developers, wishing to enforce payment authentication.
This would eliminate server calls altogether, and in exchange, for
receiving a performance boost, everything is done on social engine
server side, utilizing their cloud platform, off our servers, and
essentially away from our hands. Social Engine would only have to then
make one call to the server, in order to verify a specific set of ID
instructions based on the identity of the license holder. As in, cloud
API access to be able to proceed with the installation of the product,
but then make no more calls on the behalf, assuming things such as the
unique license key, ID and email of the client match. If such
information is not up to date, and, if say, at each new version
upgrade, social engine updates your license, then upon the
installation of new files, before it is applied, the license check
would ensure actively current details of such remain intact, up to
date, and upon verification email instructions sent to the license
holder, you could be able to approve any license request manually upon
its request within, say, a 60 second window or so. Defined by you in
the admin section, of core settings perhaps. As such, only when
upgrading packages, you would be required to show your license when
dealing with the package manager, as it would also mean you are
dealing with a license manager as well.
If social engine servers decided to not function for what ever reason,
then you could simply override the license check with a core database
override. Seeming as how you were able to download it in the first
place, should the license already be active at the time of your
download, a database override would just auto assume since you have
the files, the check already went through. If the database stage of
the installation could not be attained, then perhaps a file edit would
suffice in a similar manner. If any pirated software was found in such
a state, then the instances of social engine operating illegally could
be tracked if the server becomes operational again should it ever
fail, using an api call which could be triggered upon signing in to
the server. It wouldn't query the server the software is on, however
it could ask for a verification number of the license from the server
itself, which could update itself every 30 seconds or so using a
randomly generated number, informing the client that server side
verification is in progress. The number would be attached to an ever
changing license key, already configured using a specific email
address. At which point, verifying access to the email address will
let you download a single copy of the software. In order to prevent
malicious use of the email address verification, you'd have to be
physically using the same computer to access both the social engine
server and the server of the domain you wish to license, and should
any other requests be present for other domains, it simply would fail.
IP validation would be easy to implement in such a way.

**Comment by poeticjustice** [comment]
Hi all

I feel completely dumb on this one as alot to take in and reading has blown my mind but im blaming the man flu.

But currently how does the licencing work?

For Social Engine.

And for 3rd party Plugins.
----

Do they check the licence each day? and if social engine server is down or if the 3rd party servers are down, will this cause plugins to not work?

**Comment by Elshara** [comment]
I think the third party plugins each have their own license deal.
Social Engine has their own as well.

**Comment by gsf00001** [comment]
From my experience:
- SE doesn't seem to check anything (i.e. my License field in SE Account still shows license with no domain listed)
- Some 3rd-Party Devs require a license (5-6 of those I use) and make repeated checks to be sure you're valid, some Devs (2 I use)  don't do anything (not even their own core).

**Comment by Elshara** [comment]
Depends who is money hungry I suspect.

**Comment by gsf00001** [comment]
Or who is justly concerned about getting paid for their honest hard work, or other factors too.  I don't feel a business expecting to be paid for their work is being money hungry - they're just trying to protect themselves agains the illegal Users.

There's always been 2 sides (honest vs. dishonest/cheap Users) to licensing of anything, and honest, paying people typically pay (either in extra $$ or time or added hassle or whatever) for those that steal it.  If the licensing and policing of it was 'better' (subjective term), everyone would win (except for the pirates of course - and they shouldn't win anyway).

**Comment by gsf00001** [comment]
(is this Issue related to #151, i.e. should they be merged or are they completely different?)

**Comment by Elshara** [comment]
Maybe.

**Comment by gsf00001** [comment]
Yay !

Thank you :)

If done properly, this should help everyone tremendously (well, except the thieves of course).  The operative word here is properly (but I have faith).

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#18

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
