### ISSUE TITLE
Newsfeed

### ISSUE THREAD

**Issue by Voxitt** [SocialEngine/phpv4-issues#337]
Hello, the newsfeed on my socialengine site is not working properly. Not all the stories posted by my users are being feature on it. I'd be grateful for any advice or assistance.

**Comment by shivani2910** [comment]
Hi @Voxitt, thanks for reaching out!
Please make sure that you've enabled the corresponding feeds to be displayed on Member Home Page (Main Feed) from Admin > Settings > Activity Feed Settings > Types > Display field section.
If those feeds are not enabled, please enable them and then check this issue at your end.

If you still face any issues, please file a support ticket so that our support team can look into this accordingly.

Thanks & Regards,
Shivani
