### ISSUE TITLE
Temp ban

### ISSUE THREAD

**Issue by qoutas** [SocialEngine/phpv4-issues#339]
It would be useful to add temporary account bans, instead of only deleting the account.
Admins or moderators should be able to set a time frame for the member account to be automatically unbanned after the period. Something like from Member level to Banned Level for a certain amount of time, then revert it back to the original member level.

**Comment by eugene-wh** [comment]
In case you are looking for that functionality to be enabled asap - check our plugin Moderators toolbox. 
http://webhive.com.ua/store/product.php?id_product=44
It offers temporary ban as a feature

**Comment by Anshuse** [comment]
Hi @qoutas , If admin wants to temporarily block any member then he can disapprove the member from "Admin" > "Manage" > "Members" section but in this case, admin will need to manually approve the member at required time.

Also, we do have plan to implement a feature in our core module in near future where user himself will be able to block/deactivate his account.

Thanks!

**Comment by Elshara** [comment]
Temporary bans could be set up on the dependence of a cron job.

**Comment by eugene-wh** [comment]
@Elshara Admins or moderators won't be able to set cron jobs. That feature won't be usable unless it's easy to use.

**Comment by Elshara** [comment]
I understand.
But something automated has to come from somewhere, and task scheduler
isn't really a good way to schedule something. I mean the social
engine events plugin makes an event disappear 24 hours before it
actually happens on the day, so having said that, cron jobs to me seem
most reliable for this sort of thing. Which is why i suggested it.
