### ISSUE TITLE
Resend Activation Email By Admin

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#342]
There is no option to resend activation email when users report that they did not receive activation email.

**Comment by Anshuse** [comment]
Hello @meetgerry , Currently if email verification is enabled on site and user tries to login to his account without verifying his email then he gets a message like "This account still requires either email verification. Click here to resend the email." to get verification email again.

Thanks!

**Comment by meetgerry** [comment]
As per your suggestion, only when a user attempts to login he sees the message. But what I am referring to is that admin should have an option to tick on the emails that are not verified or approved and resend a reminder for email activation.

**Comment by Anshuse** [comment]
@meetgerry , we've added your suggestion at our end for our internal team discussion.

Thanks!

**Comment by Elshara** [comment]
I'd also like to see this as well. Why can't it just be set to where someone has to click an email to be verified when they enter their email address before setting up a profile. That way half accounts which aren't  verified will automatically be deleted before they are recognized as an official profile id.

**Comment by NaughtyToWild** [comment]
Me too, I think its very important for growing the community. As specially if there is issues with members not receiving there verification email. I have wanted this for ages. Please let me know if this happens.

Thank you

**Comment by Elshara** [comment]
Wow I love your user name!
It would be very nice to import member data and export member data to
and from social engine.

**Comment by NaughtyToWild** [comment]
Thanks Elshara, Its actually my business name lol.
I agree import & export would be great. If anyone ever gets the code or the socialengine updates the resend verification email in admin please let me know.

**Comment by Elshara** [comment]
Hey we can all dream the dream.
It's always nice to have more features, even if they never happen.
With a name like that your business must be thriving! Too bad we
didn't have a directory like Ning used to. All you have to do over
there is look at someone's profile to see what kind of site they run
and join it if you like it. I think that's how the directory started,
then they discontinued it when new management came in. Sad really. I
have such high hopes for this platform, but I feel like we're in
limbo.
I find that home family grown companies tend to do best. After all
many businesses project to this kind of life style in some way. For
businesses that don't, they're hardly ever seen which at least they
contribute sometimes here to, but I feel like projecting too much to
them causes a rift within our social clientele.
Fairness all round makes a business strive to be the best it can be,
in my opinion. The second a company puts money over people, it makes
it very hard to keep the family feel alive. That's why I've been
contributing so much to this place, I wish it to be the best it can be
and support people like you where I can in the same manner, even
social engine as a company. An interest we all share. You, we, I make
it fun together.
Elshara Silverheart.
Cosmic Nation.
http://starseeds.co

**Comment by NaughtyToWild** [comment]
True True, I have been working on my website for about a year now trying to get it working all good. I think I fell in the trap of trying to add to much to the website which has dragged on when I should have been marketing to the public. I'm almost ready within the next week or two to start marketing the website. I seen you signed up to my site, I'll add you as a friend and pm you

**Comment by NaughtyToWild** [comment]
Also I have allot of members that haven't verified there email, It has been reported to me a few time that they never received an email even after checking spam folder. However some members do get the email and verify it. I just changed my mail settings to SMTP yesterday instead of the built-in mail() function. So maybe this will make a difference. Does anyone have any ideas how to ensure clients receive the verification and how I can get a new verification email sent to the members that haven't verified?

Thank you

**Comment by Elshara** [comment]
Mine showed up in spam. I signed up to support you. Nice site I've got
some ideas for it. I'll pm you there as to not attract the moderators
to ban me from git hub for being too off topic lol.

**Comment by alimoosavi15** [comment]
When email verification is enabled in admin panel, they'll receive verification email without requesting it manually and they can request to receive it again. If your users are not getting the verification email, please use SMTP instead of mail(). You can configure that in Settings -> Email Settings. It's a bit spammy for the admin to send a reminder to users when they can request it themselves and this won't useful in large communities with a lot of users. Maybe an auto reminder to get sent out after a period of time would be a better solution. I will add the auto reminder feature for verification in the tracker.

PS. Please keep the communications related to the issue so the development team can understand the issue easily. For other conversations, you can use http://community.onsocialengine.com

**Comment by NaughtySocial** [comment]
Alimoosavi, I had users sign up and the email was going to spam and at one stage I am unsure they received the emails. I have the issue fixed now but I could use this feature to resend the email so it would land in the members inbox now I have it fixed

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#20

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
