### ISSUE TITLE
Profile pictures loading sideways

### ISSUE THREAD

**Issue by mitcholi** [SocialEngine/phpv4-issues#346]
This was supposed to be fixed in the latest release. I have upgraded and still experiencing this. I was told to pay $50 thinking they would resolve this issue. They keep telling me they can't recreate this but yet everyone on my team can recreate this issue. I'm not sure if anyone here can help. But we invested a lot of money into this platform and at this point we are very dissatisfied withe the support of the product.

**Comment by Anshuse** [comment]
Hello @mitcholi , 

As we've mentioned in the support ticket that we've checked this issue in all the Android devices available in our office but we're not able to reproduce this issue at our end. As you asked, we've checked this issue in Android version 5.1.1 but we're not able to reproduce the issue in that version as well. We've already sent you multiple videos but as you can see that issue is not getting reproduced at our end. If you think that there's any way to reproduce this at our end then please let us know. 

We can coordinate on the same issue in your opened support ticket.

Thanks!
