### ISSUE TITLE
Lets Have a Plain Text Editor

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#365]
This would be nice to have where you wish to be able to copy and paste existing code into a social engine powered post without formatting changes taking effect. I'm tired of using tinymce for everything. The same goes for flash based uploads, as they don't work on mobile. Having a simple button to browse for files and a plain text editor would fix this. Formatting posts could be as simple as editing existing html. An editor similar to what we have now on github is perfect. A code editor would be ideal for this.

**Comment by Elshara** [comment]
I feel that additionally, the options for allowing members to use a global text editor would make things much more ideal rather than have it be module and then member level based on top of it.

**Comment by smazurov** [comment]
Flash based uploads do not trigger on the phone - we have special code in place to detect flash, and only use flash based upload in case it is enabled. Otherwise, it will use regular browser upload.

Having an option to change your editor would be a good one, but its not currently feasable. Depending on the effort required to address #278, it is something we might investigate.

**Comment by Elshara** [comment]
I do think it's worth it.
