### ISSUE TITLE
Quality check for modules and integrations

### ISSUE THREAD

**Issue by gabelul** [SocialEngine/phpv4-issues#372]
Hello,

I would like to know why do you allow so called companies that make SE modules to post them on your site if they don't work properly ? Why do you allow them to market their non working product using Social Engine brand ?

I'm talking about CometChat , after a week of getting nowhere with their support because their module breaks socialengine functionality i had enough . 

They provide the worst support ever , as a software developer myself i would be ashamed to do what they do. Beside the fact they sell a broken product, all the do is just wasting time and don't do anything to get the problems sorted. 

For example , their integration module breaks social engine forum mod (that's all i tested so far as i didn't had the patience to test everything ) . I tested it on my site where i have other plugins and also tested it on a fresh install where i only have the forum module and theirs.

 I just don't get it , if you value your product why don't you do quality checks and make sure all the developers have their modules working with the basic SE modules , is that to much to ask ?

I'm waiting to hear back from you on this matter.

**Comment by smazurov** [comment]
Its a catch 22, if we don't allow everything then developers will complain that we unfairly single them out. We do take reports of incompatibilities seriously and encourage you to leave a review on the relevant mod. Github issues are meant to discus the product itself and does not serve as a platform for discussion about 3rd party plugins. You can do that over on our community site at https://community.onsocialengine.com.

**Comment by gabelul** [comment]
Well i'll post there as well so people at least know but i would have to disagree with you on the unfairly thing . You prefer to have end users who complain about bad modules or developers complaining that there modules don't make it on the site because they don't comply with the standards ?  From your reply i have the sensation it's the last one and that's really bad , like really really bad.

If it was me , i would prefer to have 5 good developers doing proper modules then 100 doing stuff that breaks my script . Think about it ;)

**Comment by smazurov** [comment]
Naturally, as users leave their reviews on bad modules they will sink to the bottom and make those developers lose business. Its worked well so far. Only when we get involved do things become a lot more negative on both sides and nobody benefits.

**Comment by gabelul** [comment]
I'm very surprised you say that to be honest . Wonder what would happen if Shopify for example would allow anyone to submit an app to their market just because they are afraid some developers will start complaining . Do you really think a good developer would complain ? No he wouldn't that's for sure . I can come with a dozen more examples where a company that releases a paid product and has a developer community makes sure that their clients are not cheated in any way or another by bad developers . 

We do pay money for Social Engine , it's not open source like WordPress or others and what you`re saying here is that we are test subjects for anyone that wants to make a quick buck and sell something to your clients. After all if you promote them on your site you vouch for them.

How did this worked well ? because people didn't complain to you directly ? Try and do a google for some of the developers and you`ll see how people complain about the quality of the plugins and they end up blaming Social Engine.

At least what you can do (didn't see that ) make a sticky announcement that the modules are not tested or endorsed by you so people who want to buy them won't end up thinking well if it's on their site it must be good .

**Comment by gabelul** [comment]
Just did a quick check and seems that even for submitting to wordpress they need to pass a quality check https://wordpress.org/plugins/add/ (remember wordpress is free )

**Comment by smazurov** [comment]
We have plans of implementing a similar system soon. [This](http://blog.socialengine.com/2014/07/14/socialengine-marketplace-mvp-feedback-request/) blog post has a bit more detail. We also have rules in place for developers before we approve their mods, but much like in case of Wordpress once its in the system, best way to enforce it is by letting others know in a review. Certified marketplace will have much more stringent rules that will be enforced on continued basis. In other words even if original version passes review, we will remove any software that fails to match our expectations. 

Additionally, you're comparing a 10 person company (regardless of cost of the product) to a company with thousands of employees and literally the most popular software in the world. Thats simply not fair.

**Comment by gabelul** [comment]
I saw that blog post some time ago, even though it's almost 2 years old i hope that will get implemented soon because that will make end users as myself feel more secure when they decides to buy a module that is advertised on your website. You have to see things from our perspective as well and why this is annoying . 

I'm not asking for a 3rd party plugin to work with another 3rd party plugin , what i want is that a plugin to be compatible with your core modules . In my case for example if cometchat wasn't advertised on your website , even though they would've said on their website it works with SE, i wouldn't had bought it  and would've bought one that i see on your site ( the developer of the script i bought ) . 

Right now i just wasted 400 on their script because i was told it works with a script for which i paid 699 . And i won't add the rest of the plugins i bought so i can get the functions i need. That's not the problem here , i'm ok with the fact that you have to pay if you want to have a quality product. 

I do understand your point of view when it comes to the developer , they are a great addition to a community as they add new features to the script , features which you don't have to add therefore they both save you time and attract new customers as they can see what SE with extra modules can do. But this doesn't mean you just have to give them a free hand just because some might get upset because their product don't meet the requirements therefore not making it to the market.

I'm a software developer myself but i wouldn't ever put up with this , if someone would make an extension to my software that doesn't meet the minimum requirements i wouldn't allow them to promote their extension on my website.

I'm not comparing a 10 person company with a big one , that was just an example to see that a free product can do it , why can't a paid product do it ? You are trying to find yourself an excuse and unfortunately i can't find acceptable . I can come with examples from other small companies just like yours (~10) that do check the 3rd party extensions before allowing them to be sold to their customers.

I tested their integration with both 4.8.9 and 4.8.10 on a fresh install just with your forum module and their module and had the same problem (2 different servers) . I see that 4.8.9 was released on June 22, 2015 , so from then till now their integration with your script was not working . How can i get access to releases before 4.8.9 as out of curiosity i would like to see what version of SE works with their module.

**Comment by alimoosavi15** [comment]
It's not a free hand. Developers promote SocialEngine, help it's customers and help growing the platform and the community.

CometChat is not a SocialEngine developer. It's a universal chat application and they implemented that application with many other platforms, including SocialEngine. There are lots of SocialEngine sites using their plugin so I'm sure if there is a problem, they'll fix it in their next version. If not then something else is wrong. Perhaps your modifications are causing the issue or there is a conflict between other 3rd party plugins in your site.

You're making a broad statement about all SE developers. Top SocialEngine developers provide a good product support and they always keep their products compatible with latest SE releases. 

Hopefully we'll see the new marketplace soon! Top developers are actually in support of more restrictions.

**Comment by gabelul** [comment]
Ali you are repeating what i said . And yes , smazurov already confirmed it's a free hand look at hist first reply where he said if they don't do it devs will get upset .

I would like do disagree with you , they are listed as developers on SocilEngine site , you can see that here http://www.socialengine.com/customize/se4/developer?dev_id=3492 . I have the impression you didn't read all i said or if you did read everything , didn't understand much from it . 

Not here to bash or blame any developer , but it seems like you are taking their side a bit here and that gets me back from where we started . How can you say IF there is a problem and that maybe my site modifications are causing this ? Again you demonstrate you didn't read what i said and you just say things.

Here it goes again : i have tested their integration on my site that has the modifications and also tested it on a fresh install of SocialEngine that only has the forum module from social engine and i get THE SAME ERROR ! Also tested with both version of SocialEngine , the current update and the last version that was released last summer and i it has THE SAME PROBLEM? Is that clear enough now ?  Can try to explain again if you still don't get it ;) 

I see you are a SE dev but try to read things and understand them in the future (don' want to be rude but i don't like when people try to talk just so they talk). 

All I'm saying is that they need to have a better quality check of the modifications, I'm not trying to bash any dev here , i bought most of the SE plugins out there and while some have a few issues ( nothing major) they do work . 

I do hope to see the new marketplace live soon and so maybe we`ll get rid of the so called developers.

**Comment by meetgerry** [comment]
I had terrible experience with specific developers like Younetco who develop incompatible module or modules that breaks your SE site down.

Its been very unfortunate that SE core team hardly has taken any measures. Its a known fact why 90% of the SE customers or buyers run away from SE after a short period of time. The SE core team has been telling since the last 1 year that they are coming up with a marketplace, but so far they are not even in the capacity to even release a responsive theme which has been going around for over a year now.

**Comment by Elshara** [comment]
I generally don't buy from people who don't give two fucks about what they develop because all they want is money for it. It's no wonder sites like socialenginehelp.com socialengineforum.com etc exist to null everything under the son because developers charge too much, for something we already have. Think about it. Advanced this advanced that, its reselling existing code under the core updates of company x.
Comet chat actually has been a developer I've been working heavily with to put some semblance of order and care into something they develop. I've been on their case for a few months now and they've actually been helpful in cleaning up their apps and such. you should take another look at them. Just because they come from India doesn't mean they're all bad. They made a ton of social engine updates in their latest module. I'm speaking from a user stand point, it's better a lot better than what it was and with countless suggestions I've put to their team, they'll be improving it.
As for you net and other developers, all I've got to say is I don't believe in their company values what so ever and I support anyone who nulls their crap because quite honestly they aren't bringing much new stuff to the table. They're not good at support because they're rebranding a module that we already have, and charging twice as much for it I think it's wrong and its gouging peoples pockets honestly. Just because they can make advanced module and reconfigure how a module operates shouldn't give them the go ahead to sell code they probably borrowed from social engine anyways. I know that sounds harsh but I'm all for supporting developers with unique quality, not ones who have frequent bug errors and fail to provide good customer support. I'm someone who firmly believes you shouldn't have to complain to a developer because a part of their code doesn't work on your site, for them to immediately fix it but not update their website files with the fix they make for many websites. I don't care if support is free or not. I've caught comet chat doing this and I flipped out on them so now they are making it much better.
Developers shouldn't hide their business by requiring support for things other end users can't reproduce on their end. It's bad business practice and usually involves sending more money to people who shouldn't use it as an excuse to live off it based on the need to update users with the files they keep hidden on their hard drive so they can keep track of what sites people visit or whatever they do. I know a lot of core plugins connect remotely to other servers and they say its for licensing reasons but you know what, I find that a privacy invasion and quite honestly if they don't provide unique modules to sacrifice that, I don't believe that through the requirement of their core product, they should be allowed to get away with it.
What I'm saying is if I wanted to as a developer, sell a product to someone using social engine as a code base, reproduce and augment existing code webliggo developed, sell it for a price higher than what webliggo sells it for, require a core to keep it functional, that periodically sends server information and data to a remote server for the developer, then after purchase, receive a product file name that doesn't install correctly for me to then have to require user access details to client websites to remove the faulty files and remove the faulty database queries to install fresh properly working data, it's a shady business practice under the umbrella  of a third party add on, it's more than just a case of buyer beware. A lot of companies have terms like this operating as social engine add ons and it's part of the reason why I'm a core product user. In cases where the core files are not being updated, and I have to use third party add ons, then I do so because social engine thinks it's the experties of another company, not several companies making a few extra dollars out of people because of something they could easily show social engine how to do, considering they're borrowing much of code that is made from a disclosed code base anyways. It's also a fact that bugs sometimes are intentional to force people to pay for support. I just don't think it should be that variable as a responsible software add on provider.
Sorry for the rant. I support social engine as a company a thousand times over any add on for this reason.

**Comment by andzimmer** [comment]
@Elshara do you ever work? you're always ranting here. just search your name in google. you're ranting everywhere. there are even complaints about you ranting and driving people crazy. this is github. this is not a place for rants. just because you see a commenting box doesn't mean you can rant 24/7 there!

**Comment by Elshara** [comment]
You're right. It is git hub. It's called community participation.
Without me around social engine wouldn't be what it is today. Excuse
me for caring.

**Comment by andzimmer** [comment]
@Elshara This is a place to report bugs, this is not a forum and it's called phpv4-issues, not phpv4-rants. As far as I know you haven't contributed anything to SocialEngine. I've been reading your comments. They're all nothing but rants and stories. You haven't helped anyone, you haven't developed anything for SocialEngine, you're badmouthing the developers who are contributing, you're spamming and now you're supporting piracy. You can't even spell SocialEngine correctly. Maybe you should stop "caring".

**Comment by Elshara** [comment]
And I've not seen you really contribute much either. All you've done
is rant about how I'm not improving anything, whereas I'm not really
coming at this from a developer stand point, and nobody here is. We're
raising issues for developers to look at from user points of view, and
sometimes they are simple issues. Other times they are suggestions.
I work not always in code improvements. I look at user functionality.
How come user x can't do y functionality. Or why can this issue be
duplicated via x set up but not y set up. Not everything is a
developers problem and sometimes we need someone else to see it and
point it out. Note I'm not trying to suggest this place is just for
problems to be shared, it's more than that.
There are a number of factors that come into play when not only
creating issues, but taking the terminology to apply it to things
developers use to continue a good product and make it better. Not
everything is something we agree on. In every sense of the phrase,
there are pesimists, which is what you are, optomists which is what I
am and realists which is what social engine is. Not everything
reported, in fact a lot of what I do report is user suggestions for
developers to work on. Perhaps people are tired of hearing the same
boring complaints about existing user functionality and bug reports,
or maybe they find interest in it. I don't live in the office building
the developers of Social Engine does but one thing I can tell you is
that new ideas go a lot further than ideas which never get addressed
to begin with. To put this in perspective, coders are in business
because it's people like you and I who trust their work to take
everyone to a better point in life, or at least people who enjoy what
we all wish for in our company. Social Engine takes our ideas and
votes on it as a company, but they have to start somewhere. Just like
we do. Some people would prefer to higher a custom developer, others
use scripts. It isn't as if stack overflow is ideal for talking about
social engine because they are a programming community focused on
providing solutions for developers of companies to integrate
applications in to real time functionality. The point is, as I've said
before, without us working together here, Social Engine wouldn't be
the same as it is with us all in agreement of what each and every one
of us brings to the table. Together, we try to find issues we are
facing independently and if a common ground is reached, there is a
place to talk about it. That's here. Git Hub primarily is not just a
place to post issues and yell at people who you think is not doing
anything up to your specifications around here. You want answers, here
they are.
1. To get to know me, my business is posted on my Git Hub profile. I
updated it because you decided to question who I am. You want to see
my work, I won't spam you with the link, go find it if you like to
read.
2. Though this discussion should be taken off Git Hub, it's honestly a
place of non judgment and personal common sense. Each of us has the
right to form our own opinion. Piracy as you so strongly put it, is
not a bad thing if everyone is able to work together to support a
common goal, which not everyone in the industry does but I respect the
people who do. Everything is not always about how much money you make.
If there's anything you can learn from life, it's that in the work
place, care should be taken into what you build, not how much you make
off the things you build. Everyone comes together for a reason, if
that means people who have had a history of forming outside
communities around a company, person or place of interest and who may
wish to share that love freely, then it is their right to do so.
3. Every contribution I have made has been tested by a professional
support person working as a go between for Social Engine and its
client base to form an objective opinion about situations we bring to
the table for improvement and sometimes investigation. Should this be
an issue you wish to personally address with them, I myself recommend
the suggestion of starting your own thread about this issue so that it
can be resolved mutually. Otherwise, we're all responsible if not
developing adults working to have our communities and online websites
function as we would like to have them built. Some people developers
included are better at this than others, some I may not care for as a
part of their business may not be something I agree with, but that's
no reason to slander them for doing what they do. They're doing no
actual harm it isn't as if they wish us it either way.
4. You bring up a very valid point. The nature of business is to
collect feedback. Some may be isolated cases, others may be common
grounds. How ever in places where such goals meet, such as git hub,
there are cases where some ideas clash. I have reason to believe this
is one of those cases. I don't fault you for being angry at some of
the things I may suggest. I am aware of the fact that you don't see me
as someone valuable enough worth contributing here. I wish you to know
that I don't view you in a similar way, I respect you for what you
have to say.
My intention is to be able to be useful. It may not be in a way
everyone can understand, but I am not one to bad mouth people for who
they are. I wish everyone could be honest about things we like about
each other and didn't have to bring up negative points to throw in
someones face. Ideally if there's something I could improve on, I'd be
interested to hear it. I've got the feeling you would like me to
disappear completely. Because my interests are in helping this
platform grow, I don't think it's in neither one of our best interests
for me to step down just yet from the boards, however what you aren't
saying I'll take into consideration. I'll be happy to provide better
clarification on what constitutes in my opinion, a good issue to
report. I feel it relevant to state I don't work well on an approval
basis, but rather on a suggestion basis for optimum performance. I
work on the principles that everyone matters equally, but favoritism
and corruption are issues I am used to combating all too well and I
try to prevent them if I see it happening to things I personally
invest in to care about. You may find a difference in why you care
about a platform we share as opposed to my view, which is to be
expected. However that being said, I am taking my leave of this issue
in good faith on the basis of an understanding between us there will
be no future problems in respective clients working together to bring
a company deserving of our investment a worth while place to consider
on our own time.
Thank you for sharing your thoughts they are well received.

**Comment by smazurov** [comment]
I had to remove quite a few posts from this thread. To reiterate, this should only be used as a way to report issues and offer suggestions to the core product, being SE PHP. Maintaining a healthy developer eco-system, while important, should not be discussed here. Best place to do it is on community.onsocialengine.com. 

Thanks.
