### ISSUE TITLE
Token error when publishing blogs

### ISSUE THREAD

**Issue by maxx24** [SocialEngine/phpv4-issues#373]
Why do I get this error message when publishing blogs:
_token
No token was provided to match against_

I click on post entry a second time and there is no issue. This is annoying I am sure for my members

**Comment by pacodrums** [comment]
Hi. I would also like to know that this error is due. It is something that I too often happens in my 2 sites SE.

**Comment by Anshuse** [comment]
Hello @maxx24 and @pacodrums , we've resolved this in 4.8.10, you can check the same from http://blog.socialengine.com/2016/01/20/socialengine-php-4-8-10-is-released/ 

Also, this was not an issue. Token expiry time for blog was set to 5 minutes so when members stay on the blogs page for more than 5 minutes then token gets expired because of which they get token expired message. Now we've increased the expiry time in 4.8.10 so we suggest you to please upgrade your site to latest version.

**Comment by maxx24** [comment]
Thanks for the information. I did do the upgrade. However, since upgrading, I have also installed a new plug-in for advanced blogs.  Is there an area within the cpanel files that I can go in and make the adjustment of the time limit myself?
