### ISSUE TITLE
Phrases not translated

### ISSUE THREAD

**Issue by Burno317** [SocialEngine/phpv4-issues#376]
Hello SocialEngine,

Following my report to Shivani, I have noticed sentences that can’t be translated and should be fixed in your next updates as it is minor:

1) “Save Photo” when the admin request a profile image during signup, the "Save Photo" button can't be translated.

2) “Missing captcha fields” in Google recapcha

“3) Your changes has been saved.” like saving data  after vewing a member account in the admin panel.

Thank you to let me know what you intend to do.

Regards

**Comment by Anshuse** [comment]
Hi @Burno317 ,

1. “Save Photo” : This phrase already exists in the /application/languages/en/user.csv file so, please check the same at your end.

2.  “Missing captcha fields” : We have added this missing phrase in the list of Translation issues and will add in our module in near future release.

3. "Your changes has been saved.": There's no such phrase being used in core module, instead "Your changes have been used" is being used and this phrase already exists in /application/languages/en/user.csv file. If you have found "Your changes has been saved." being displayed in any section of your site then please let us know the URL of page so, we can look into it.

Thanks!

**Comment by Burno317** [comment]
Hi Anshuse,

Thank you very much for your responses, I appreciate it.

1) You are correct, “Save Photo” is part of the “/application/languages/en/user.csv file en/user.csv” file , the problem is tht even translated or modified it always remains in English, please test it on your side.

2) Thank you.

3) "Your changes has been saved." it exists in the admin and core, just go in “/admin/user/manage”, on the right side, click the “Edit” link on any member, then click the “save button” of the pop-up window, then you will see briefly the sentence "Your changes has been saved."

Thank you again for your  concerns and dedicated support time.

Have  a great day.

Regards
Bruno

**Comment by Tomislav20** [comment]
Hi all,

2. Thank you for inserting that phrase.

3. I'm using SE 4.8.6. and it gives me this message: Your changes have been saved.
, but it is already inserted into language.

![admin changes saved](https://cloud.githubusercontent.com/assets/12753666/14658938/fa34a0e6-0697-11e6-8767-24cecacca707.jpg)

Regards
Tomislav

**Comment by Burno317** [comment]
Hi Tomislav20,

It was a good idea to have added a sreenshot in your post.

3) Yes it is already inserted in the language file, but the translatation does not work, the core and the file containing that sentence needs to be fixed in order for the translation to be applied and be visible as all the rest of the translated text.

Regards
Bruno

P.S; I am using SEPHP version 4.8.10.

**Comment by Khushboo016** [comment]
Hello @Tomislav20 , @Burno317 ,

Regarding "1) You are correct, “Save Photo” is part of the “/application/languages/en/user.csv file en/user.csv” file ":
This issue is not appearing at our end as the phrase "Save Photo" is translated as shown in the attached screenshot. So, we suggest you to recheck this at your end and if you still face the same issue, then we suggest you to open a support ticket for this at https://www.socialengine.com/client/ticket/create or you can also email us at support@socialengine.com .
![phrase_changed](https://cloud.githubusercontent.com/assets/18209340/15043967/01d1cbb8-12ef-11e6-87cf-4939a5cc3d4a.png)


Regarding "3) "Your changes has been saved." it exists in the admin and core, just go in “/adm":
The phrase present in the core module is "Your changes has been saved" instead of "Your changes has been saved". And to make it translatable, please make below changes in the file /application/modules/User/controllers/AdminManageController.php : 
Search for the code: 

``` 
'messages' => array('Your changes have been saved.')
```
and replace it with: 
``` 
'messages' => array(Zend_Registry::get('Zend_Translate')->_('Your changes have been saved.')) 
```
And we've also added this issue in the list of Translation issues and will add in our module in near future release.

Thanks!
