### ISSUE TITLE
Cannot add layout to Group Photo View page

### ISSUE THREAD

**Issue by CLG-Brainstorm** [SocialEngine/phpv4-issues#383]
I need to add widgets to the Group Photo View page so have created a new page in Layout Editor and added the controller reference in engine4_core_pages.name of "group_photo_view", with provides="subject=group_photo" but it is not triggering the page layout (rendering only the Content block), even if I force the layout rendering with $this->_helper->content->setEnabled(); in the Group_PhotoController.

The layout works fine with Album View Photo but not Group photo, any ideas?

**Comment by nizhnyk** [comment]
I recall having the same issue and it turned out to be the tagging feature on the page that caused it. Try to temporarily remove this code from group photo view tpl:
`'tagListElement' : ....
      'existingTags' : .....
      'suggestParam' :.....
      'guid' : .....
      'enableCreate' : .....
      'enableDelete' : .....   });`

If that is what your problem was, I just took albums view page as a reference to make it work in groups and events.

**Comment by CLG-Brainstorm** [comment]
Awesome, thanks!  I've managed to trace the problem to any occurence of the `$this->action(...)` method in the view.tpl

**Comment by Elshara** [comment]
Or just add a new page for this under layout editor in next release.
