### ISSUE TITLE
Bug When Column Is Changed In Layout Editor

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#386]
When ever a column layout is changed, after saving changes, you have to reload the page if you want to change the columns again which means losing the work you have partially made if you don't like how it looks. This is problematic for sites which have a lot of plugins to sort through via third party providers if you are looking for something to be quickly changed because switching to a column layout destroys the widgets currently configured there. If you want them to reappear, you have to do this page by page adding them back manually.

**Comment by Khushboo016** [comment]
Hi @Elshara , If a change is made in the Page Layout from "Layout Editor" section and the number of columns are changed, then yes, some of the widgets previously configured are lost, but at the same time these are retained to an extent, for example if there are three columns in Page Layout and then it is changed to have one column only, in this case the widgets of the center column are moved to the newly created single & wide column and vice-versa. Widgets that were placed in left and right column are lost in this case because it's not possible to place those widgets in the single new column as that would distort the layout of the page. But we've still forwarded this suggestion to our internal feature tracker, so that we can discuss and try making an improvement regarding this feature in our future releases. 

Thanks again!
