### ISSUE TITLE
Finding Inactive Users

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#390]
There are times when monitoring a site for its performance involves being able to tell active members, from people who make a profile but do little with it. It isn't just a storage fee we pay for, it is the ability for members to communicate with each other. If a profile gets a lot of attention, this is a good sign it is wanted. But if the owner of that profile is special and doesn't show up to respond to it, it would not be noticed because the inactive users of the forum are buried by the active ones.
What social engine needs in this case, is to tell inactive members from active ones by any relative time period, break that down into how much they have contributed and tie it altogether as a statistic so that it is displayed when ever a users profile is called as an optional feature. This would give both admins and members the ability to engage with an inactive user, hoping they get the notification and respond to a sign of life. this usually works quite well in cases where they are waiting for something to happen, but don't always realize where it would come from. By doing this, it will be a good insight into how members spend their time on a social engine site, and what can be done to improve their time spent there as previously inactive users  either become active or remain dormant. In some cases, it is a good idea to remove them from the system if all they do is create a profile and never do anything with it, even though they have taken the first step to hopefully expressing enough interest in the site to want to at some point. As time is a constraint for a lot of people, it is also a good idea to know inactive users by their time spent online overall, to get a feel for how the site is maintained in their absence if they are active during their free time on it.

**Comment by SpiritWolfie** [comment]
This can be summed up by 

It would be nice if their was a way to sort by inactive accounts (accounts that have not logged in, or posted anything in X amount of time)

I have to agree that this is a feature we could really use!

Thank you for your time~

**Comment by Khushboo016** [comment]
Hi @Elshara , @SpiritWolfie , Currently the only way to monitor a member's activity is to see his Login History from "Admin" > "Spam & Banning Tools" section. Entries can be sorted there on the basis of Timestamp, so it can be found which members have not become active for a longer time period and admin can take required action for those members whether remind them for being active or to remove them from the database.

But at the same time, we will surely discuss and forward your suggestions to our team for future releases, so that there can be a reminder option present for automatically reminding the inactive members who have not become active for a specified time period.
