### ISSUE TITLE
Bug When Viewing Updates Related To Post Replies

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#391]
This has been particularly noticeable within the last update. When you view a notification, it tells you by linking to the post either in the word like or comment, what someone has done. The problem I'm seeing particularly in the latest release however, 4.8.10 is that the posts that are being linked, have no record of the person responding at all. Additionally, this problem is very bad when it comes to people responding from the activity feed. Posts won't show there if followed by from notifications, nor are they being added to the activity feed once they are made. The activity feed is not showing anyone who likes comments even when clicking on the number of people who like the item. I'd say this is related to activity feed problems mostly, but it is very noticeable when you get notifications stating, someone has commented on a post you like or a post you commented on, yet when viewing the post no matter what it is, that activity isn't showing up.

**Comment by Anshuse** [comment]
Hi @Elshara , as we have mentioned in your another thread #395 : It seems that you are talking about the Forum Notifications and if so, then currently the Forum notifications don't create the links accurately. For eg. for the notification :  ![notification](https://cloud.githubusercontent.com/assets/11085507/13311795/6e103c2a-dbb7-11e5-9c6f-f890dbac5de5.png), "posted" link forms a link for the "Topic" instead of specific post ID and "forum topic" link creates a link for the "Forum" instead of the "Topic" itself. If you're referring to such Forum notifications then we would like to inform you that this issue is already in our list and we have plan to resolve this issue in near future release. 

Thanks!

**Comment by Elshara** [comment]
That's cool! I forgot I made similar post about it.

**Comment by smazurov** [comment]
This has been addressed in [4.8.11](http://blog.socialengine.com/2016/05/26/socialengine-php-4-8-11-is-released/)
