### ISSUE TITLE
Bug When Viewing Displayed Photos

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#395]
Photos often appear as links on social engine sites as they are shared, rather than direct images. This needs to be addressed if it is simply an html post problem when having to embed photos, rather than share them graphically on a page.

**Comment by Anshuse** [comment]
Hi @Elshara , It would be great if you could explain your query along with the screenshot. Thanks!

**Comment by Elshara** [comment]
Screen shot is impossible to do since all the posts are very alike, I
wouldn't be able to pin point an exact area.
To put this in simple terms when discussions are mentioned, the
activity feed fails to link the correct area when following a link to
a notification about a post. It works great for activity feed posts
and comments, however the same post is mentioned when two
notifications are received when someone comments on a post you have
liked and commented on instead of one post informing the person who is
notified that someone has simply replied to something you have posted
in. Suffice it to say, the activity feed cannot link forum posts
correctly in notifications.

**Comment by Anshuse** [comment]
Hello @Elshara , It seems that you are talking about the Forum Notifications and if so, then currently the Forum notifications don't create the links accurately. For eg. for the notification :  ![notification](https://cloud.githubusercontent.com/assets/11085507/13311795/6e103c2a-dbb7-11e5-9c6f-f890dbac5de5.png), "posted" link forms a link for the "Topic" instead of specific post ID and "forum topic" link creates a link for the "Forum" instead of the "Topic" itself. If you're referring to such Forum notifications then we would like to inform you that this issue is already in our list and we have plan to resolve this issue in near future release. 

Thanks!

**Comment by Elshara** [comment]
That's precisely what I'm referring to bud.

**Comment by Anshuse** [comment]
Hi @Elshara , we'll consider this issue in the thread #391 so, we're closing this one.
