### ISSUE TITLE
Remove Character Restriction When Assigning HTML Tags To Posts

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#397]
The html field in social engine for assigning custom tags is too short. The area appears in several different places. It must have no restriction to allow custom code to post. One such area that was in social engine long ago but has since been removed is the ability to post html in profile fields. I think we should have this added back, as well as the ability to set html in status updates.

**Comment by Anshuse** [comment]
Hello @Elshara , It seems that you're talking about removing "Allow HTML tags" field (that we have provided in the "Member Level" setting of each plugin) and allowing all the HTML tags by default. If so, then we would like to you that we have provided this field so that site admin can control which HTML tags should be allowed on his site. If we will by default allow all HTML tags then site admin will not be able to control the allowed tags on his site.

Regarding "post html in profile fields. I think we should have this added back, as well as the ability to:
We've noted down your suggestion in our suggestion tracker for internal team discussion on this.

Thanks!

**Comment by Elshara** [comment]
Awesome! Thank you!

**Comment by Elshara** [comment]
What I'm talking about when it comes to character restrictions, is the
ability to remove the character restriction, the amount of characters
you can post in the actual admin area when copying tags you want on
your site to be allowed. That field is limited to so many characters
so not all the tags you copy get saved there when you place them in
that box, therefore limiting what tags you can allow based on that
restriction of text characters.
I feel a solution for this would b to create a check box allowing
admins to control what tags are allowed or blocked where ever html is
allowed. This way the tag field itself could be used to specify what
you want and don't want.
