### ISSUE TITLE
Membership profile displaying inaccurately

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#410]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Change anyones role (say change someone to moderator or admin)
2. …Check user profile
3. …N/A

What happens?
-------------
… Member Type: Regular Member (it doesn't change on the profile)

What were you expecting to happen?
----------------------------------
… For the membertype area to display the correct roles, such as Mods/Admins Super admins or any role you create

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

``` No.
Paste Log Here
```

Any other comments?
-------------------
… one of the third party social engine forums had a code fix for it but I can't find it

What versions of software are you using?
----------------------------------------
**Operating System:** … Linux - Meets the SE requirements out of box.

**SocialEngine PHP Version:** … Latest

**Comment by SpiritWolfie** [comment]
If anyone has the code fix for this and can pass it to me I'd greatly appreciate it!

**Comment by Anshuse** [comment]
Hi @SpiritWolfie, It seems that you got confused between "Profile / Member Type" and "Member Level". We would like to tell you that the setting that is provided in the Admin panel is to change the "Member Level" and option that is displayed on the user's profile page is "Profile / Member Type".  Member Level and Profile/Member Type are two different options. Member Level can be changed at anytime from the Admin Panel but Profile / Member Type can never be changed once it's selected by the user during the signup process.

Thus, If you will make any changes in the Member Level from the Admin panel then it will have no effect on the Profile Type (that is displayed at the user's profile page).


Thanks!

**Comment by Elshara** [comment]
I think what you want to do is replace the profile type data with member level data in that field. I know its confusing.

**Comment by SpiritWolfie** [comment]
@Elshara 

The real issue is theres no way to honestly know who the staff are on social engine, there needs to be some sort of Staff tagging feature implemented, it really shock me that there is no way to honestly know who the staff are.

**Comment by Elshara** [comment]
I know. That's what I'm saying. The code in the widget profileinfo.tpl
file allowing to display member level or profile type needs to be
updated. So that instead of profile type, it shows member level. That
way it will display who is a staff member on their profile. Also, one
could theoretically reduplicate the members modules so that you could
browse by just admins.

**Comment by DonnaScriptTechs** [comment]
@SpiritWolfie would you please submit a feature request for the option to choose to display membership level or membership type or both on the profile if you still want this feature? We can then see how many would be interested in this.

**Comment by shivani2910** [comment]
@Elshara @SpiritWolfie in the Member Info block on the Member Profile Page, we use the word "Member Type" to refer to the "Profile Type" of a member. This sometimes creates an ambiguity to clients between Member Level and Profile Type of a member. So, we're already fixing this in 4.9 by changing the word `Member Type` to `Profile Type`.

As far as displaying member level is concerned, we are not planning to do that because member's level is something more meaningful for admin and just derives which features on website would be available to people belonging to that level. Also, a member never chooses his member level himself, he just chooses his profile type (member level is accordingly assigned to him at back-end based on the profile type he chooses during signup).

So, it makes sense to only display profile type on member's profile page on front end.  If you have to display things like who is a staff member on their profile, you should create profile types with such names.

Thanks
