### ISSUE TITLE
Option to disable error logs and clear temporary folders

### ISSUE THREAD

**Issue by Hostiso** [SocialEngine/phpv4-issues#422]
We have 2 suggestions for SE:
- Add option to completely disable error logs, as these logs even with task manger set to clear them can grow very large and in case problems with task manager logs never deleted and get even up to 50+ GB this is really un-necessary and can use up space.
- We also recommend if possible to add option to clear temporary and public/temporary folders, they are never get clered and over time with any SE community they just use space.

That is all from us.

**Comment by Elshara** [comment]
I agree with you about the public folder, but then where should files be stored? What about introducing a cache folder for all files not required for updates like photos and other folders necessary for the temporary folder to exist to upload files to in the first place?
Also, space requirements for error logs shouldn't be an issue. The logs can be cleared manually per user requirements. The problem is, nobody is notified if a log exists especially for actions that repeat themselves via task scheduler.

**Comment by Elshara** [comment]
I see three possible solutions for this issue however they all involve either the task scheduler running extra jobs, or a cron job especially designed to monitor the performance of excess files. Not to mention .htaccess overrides.
1. The most applicable solution would be to clear the job cue. That means when someone's finished posting, whatever they've posted be it a file, something in the database or both, gets saved to a folder called archives. That is the essential data only written via the social engine software directory itself unless specified otherwise via some sort of third party api. In order to maintain the folder, a .htaccess file would have to be created to make sure the folder permissions for the entire social engine directory remain specifically set to function at various permission levels for the structure to autorepair itself. Also, a cron job or task scheduler setting would need to be applied to regularly make sure the clear job task is run successfully, reporting any failures into a task scheduler specific error log, cleared once viewed.
2. The unpopular solution would be to create a cache directory for all essential files to be loaded from. All files currently in existence and their file types would be recorded in the main .htaccess file, to make website loading of both database queries and resources quicker. The only problem I see with this solution is that the temporary and public directories per this request would remain intact. Also the file structure wouldn't need to be changed. I'm not sure if one can change it as per the requirements of zend data structure. this would be the easier of the two to set up in this regard.
3. remove zend components from the data templates completely allowing essential data to load much faster. Each file would have a function, not to encrypt or be used objectively, but to be decoded subjectively as it is needed therefore minimizing resource usage and maximizing user performance. The down side, an entirely new file structure and database system would need to be in place for all existing modules. However, making modular updates would be a breeze if only one core module existed allowing for this to be possible.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#22

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
