### ISSUE TITLE
Problem With Field Editor In Classifieds Plugin

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#428]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to classifieds plugin under admin control panel.
2. … Go to classified questions. Add a new one with a multiline text input.
3. … Go to the network side and click create a new classified. Post new listing.

What happens?
-------------
… Tinymce editor shows up to replace the multiline text editor breaking the text. The tinymce editor should only appear for the description field. By the way, the title and description portions of the classified listing are not listed in the questions area, they should be.

What were you expecting to happen?
----------------------------------
… The tinymce editor show up for just description or as an optional field type.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… This problem makes the field type multiline not work.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.10

**Comment by Khushboo016** [comment]
Hello @Elshara ,

Regarding "Tinymce editor shows up to replace the multiline text editor breaking the text. ":
It would be great if you can add a screenshot showing this issue, so that we can assist you better.

Regarding "By the way, the title and description portions of the classified listing are not listed in the questions area, they should be.":
There are not separate Classified Questions present by default for Classified's title and description, but the Classified Question "Search Classifieds" is present by default and whenever the classifieds are searched based on this question, then the search performed takes into account Classified's description and Classified's title. So, there seems no need to have separate questions for description and title.

Thanks!

**Comment by Elshara** [comment]
I've taken two screen shots. The create page in the members area and
the questions page in the admin area.

**Comment by Khushboo016** [comment]
Hi @Elshara , please share those screenshots with us.

**Comment by Elshara** [comment]
![layout](https://cloud.githubusercontent.com/assets/12810222/15747254/c7226ef4-288e-11e6-9327-0a6b6e094137.png)
![admin](https://cloud.githubusercontent.com/assets/12810222/15747275/dacf12c2-288e-11e6-8a5a-922757848400.png)

**Comment by Elshara** [comment]
![admin](https://cloud.githubusercontent.com/assets/12810222/15747303/fb3e0e1e-288e-11e6-8aff-180d20a0ecb0.png)
![layout](https://cloud.githubusercontent.com/assets/12810222/15747323/0f144b06-288f-11e6-9aeb-050024ce95d7.png)

**Comment by smazurov** [comment]
multi-line input currently adds a tiny-mce editor, the idea is multi-line inputs are used to further describe things, not for a specific "pay now" functionality. Ability to add html field for things like a paypal button would be a good addition.

**Comment by Elshara** [comment]
I agree. The problem is the multi line field doesn't appear as it is
replaced with the tinymce editor.

**Comment by Khushboo016** [comment]
Hi @Elshara , As Stepan have already mentioned "Ability to add html field for things like a paypal button would be a good addition.", so, we've added this feature in our internal feature tracker and am closing this issue for now, whenever we'll work on features improvement, we'll reopen this issue.

Thanks!
