### ISSUE TITLE
Add ability to Organize plugin menu

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#443]
(You may want to consider doing a suggestion area?)

What i'd like to see is the ability to re-organize the plugin menu, for example if I want to keep all my SEAO plugins together I can move them near one and another, vs having it put in some random order based on how you install them, This will allow us to quickly access what we need in a more timely fashion.

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , Whenever new plugins are enabled on the site, these keep on adding in the list of Plugins based on the order in which these are enabled on the site. So, we suggest that if you want to change the order of the plugins, you can set the order as per your requirement accessing the database of your site. Access the table `engine4_core_menuitems` and change the values in the column `order` accordingly for all the plugins available. For the plugins which you want to show near or adjacent to one another, set their order values also in the same fashion, like if you want to show plugin A and plugin B near to one another, then if you set the order of A as 500, so to make plugin B appear next to plugin A, you can set the order of plugin B as 501.

Hope that helps, Thanks!

**Comment by SpiritWolfie** [comment]
@Khushboo016 you guys should really consider making a document or something with these little tweaks! thank you for this, this is very very helpful cause even if I install them in order they still get out of order some how!

It's still a feature to consider for the future though! for those of us who like to keep things tidy/neat

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , we are already maintaining documents for implementation of such tweaks and tricks and we have plans for release of those documents as tutorials & articles for clients' help.

Thanks!

**Comment by SpiritWolfie** [comment]
@Khushboo016  That's great to hear! any date on when you might release this stuff?

Off topic but I have another question
1)Is there anyway to set the update thing to clear out after X amount or perhaps provide a Clear option for users who want to clear the update log?
2) Any way to adjust the amount that shows up in the update feed?

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , We are sorry but we can't provide you any fix date for the release.

Regarding "Off topic but I have another question":
We are sorry, but we do not understand your query here, so please explain these points again in a bit more detail.

Thanks!

**Comment by Elshara** [comment]
Actually this isn't true. When you install a plugin, it assigns a random ID so it could appear anywhere in the list and the list does appear quite often at random. The list reverts to the previous layout when ever a plugin is enabled or disabled because it has to update the list itself. An alphabetical list would make this slightly more reliable however the plugin list in my opinion should actually be also accessible via package manager directly. this would make it a lot easier to manage. A lot of plugins don't have front end controls so having to access admin menus all the time to do something simple can be a little confusing, especially in the case of plugins and their own secondary menus. Like the activity feed item settings page and the spam banning tools page for example. To make it more confusing, the mail templates page can be duplicated via the language manager page. plugins need a better file structure for both management and accessibility. Providing an admin layout and menu editor would solve this.

**Comment by SpiritWolfie** [comment]
@Khushboo016 

User A Comments on User's B's stuff, This creates a notice in the "Update menu" at the top of the screen..

I am wondering if there is any-way to adjust how much that can show and any way to enable users the ability to clear that list.

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , There is already an option "Mark All Read" available under the menu-item "Updates" clicking on which all the listed updates are marked as read and the number of updates turns out to be zero. 

Thanks!

**Comment by SpiritWolfie** [comment]
@Khushboo016 

I think you mis-understood me

When marking it as read it does not clear the update menu of whats in it (nor is there any way to clear the actual update page itself)

The other question was, was there any way to adjust the amount that is shown in that drop down update menu.

**Comment by Elshara** [comment]
Mark as read doesn't always work in the first place if the website is
experiencing high traffic, the command won't register no matter how
many times you select the option to do so.
There's no current possible way to create drop down menu for updates.
It's currently all module based for groups, events, friend requests,
comment and like notifications and if comet chat is installed, you
don't get updates on new messages because the database queries never
properly succeed if you use comet chat to send and receive messages.
It takes one bad database query to make the whole thing not work as it
should.
Mark as read is rarely consistent. Drop down menus would make it
easier to view the type of activity you've received if multiple
modules or module updates have occurred involving separate actions
either by user profile, profile action or third party user profiles
and their actions on things either you follow or they follow you
about.

**Comment by poeticjustice** [comment]
This would be great, i hate that they are so random, dont really like editing the mysql myself

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , We have added your suggestion at our end for internal team discussion, but for now you can do customization at your end to achieve this feature.

Thanks!

**Comment by eugene-wh** [comment]
@poeticjustice Daniel, in case you can't wait for this feature to be added - consider our plugin Custom Menu http://www.socialengine.com/customize/se4/mod-page?mod_id=1180

You can add dropdown menus easily or even make sticky menus

**Comment by poeticjustice** [comment]
Hi @eugene-wh 

Its regarding the default plugins arrangement in SE, but thanks

**Comment by Elshara** [comment]
To my understanding you can't reorder anything in the admin control
panel as per your needs.

**Comment by eugene-wh** [comment]
@Elshara you are right, my bad. Actually, I'll check if we can add this as a feature for the plugin. At least some drag and drop sorting will be a good idea. Not sure about grouping elements, but we will check.

**Comment by Elshara** [comment]
Sounds like a plan. If you offered a database clean up tool to get rid
of extra data base ID's no longer in use or a plugin uninstaller that
would be awesome! I'd buy it.

**Comment by DonnaScriptTechs** [comment]
@Khushboo016 can we update this for the client please? What is our status on this?

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie, @DonnaScriptTechs, We are implementing the feature to organize plugins alphabetically in version 4.9.

Thanks!

**Comment by SpiritWolfie** [comment]
@Khushboo016 

Be nice if we can also simply drag and drop their positions just in-case , I.E I'd like to keep social engine addons, with social engine addons, and not have like Hire experts or something in between them.

**Comment by gsf00001** [comment]
@Khushboo016 RE: "we are implementing... alphabetically"
It would be great if SE could require Devs to include their name (or abbrev) at the beginning of their Plugin name.  Some Devs do this, others don't (those that don't makes it difficult to find a plugin or more importantly differentiate from similarly named plugins).  The Alpha option will be more beneficial if Devs use a consistent name/abbrev.  Just my thought.

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
I'd like to point out I also support drag and drop interface for admin
menus, including package or plugin manager.
