### ISSUE TITLE
When sending messages via the Social engine, letters are getting lost.

### ISSUE THREAD

**Issue by Yunod** [SocialEngine/phpv4-issues#446]
The problem appeared after upgrading SE to SE 4.8.11 version 
Our plugin sends 100 mails to users through task system. Everything is displayed correctly and no errors are appearing.

sendSystemRaw claims that the letter was sent, but the letter did not reach the addressee.

If you reconfigure the system to send messages through the third-party systems (Sendgrid, Mailchimp), then letters are being sent correctly. The only problem is sending mail through Social Engine.
If you manually, one by one call sendSystemRaw function the letters are sending correctly.

Unfortunately, we are unable to figure out the reason.

$mail = Engine_Api::_()->getApi('mail', 'core');
$mail->sendSystemRaw($email, 'notification', $params);

----------------------------------------
**Operating System: Debian

**SocialEngine PHP Version:SE 4.8.11

**Comment by Khushboo016** [comment]
Hi @Yunod , As we have not done any work in our release 4.8.11 related to the mail sending function, so this issue does not seems to be related to the script of SocialEngine. There are below two ways in which mails can be sent from SE site:
1. When email queue is enabled: In this case if mails are sent in bulk from site, then sometimes some mails may stuck in between and are not received at the receiver's end.

2. Always send mails immediately: In this case if mails are sent in bulk from the site, then sometimes mails are lost in between and are never received at the receiver's end.

So, we suggest you that if you usually need to send mails in bulk on your site, then you should consider the third-party systems Sendgrid or Mailchimp etc, so that mails may get sent via SMTP server and the successful delivery of all mails sent from your site can be ensured .

Thanks!

**Comment by Elshara** [comment]
There's a fix for this. Try adding a verification record so you can track the log of each mail being sent.

**Comment by smazurov** [comment]
we already have a record. This is an email delivery issue, not an SE issue. More evidence is needed to indicate otherwise.

**Comment by Elshara** [comment]
Although I agree with you, I think server delivery in general has a
huge part to play in the emails people receive. I'm actually going to
suggest this is a task scheduler issue because if the task scheduler
settings aren't run frequently enough, as in only one concurrent
process has to be haulted because others are in progress say if the
background mailer process is paused, that can also delay if not stop
the processing of emails entirely. If the process fails, such emails
don't get sent so it's good to have a server capable of processing a
higher concurrent process request load at once so that emails and
other tasks get managed on time.
I therefore ask to be able to control the amount of seconds each job
the task scheduler is run individually to improve performance so that
other tasks can be run at a set time or peak intervals during the
night, so that when regular email sending resumes, or when other tasks
are taxing on the system, other tasks can run freely during their time
without issue. A job cue setting to manage when a task runs and for
how long individually would make this no longer an issue no matter if
someone is using an smtp server of php mailer to send emails.
OF course it's also always good practice to make sure you are sending
from a verified domain so the emails connect properly from the server
they are sending from to the desired recipient.
