### ISSUE TITLE
Accepting friend requests returns token error

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#454]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Accept a friends request, (not sure if on mobile - fullsite or what wasn't given the full details to this)
2. …
3. …

What happens?
-------------
… Get a Token error but still lets you befriend said person (This is after installing the friend fix from staff member on git hub from SE)

What were you expecting to happen?
----------------------------------
… not to get a token error

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using? Latest 
----------------------------------------
**Operating System:** …

**SocialEngine PHP Version:** … Latest
![1467227100](https://cloud.githubusercontent.com/assets/9712738/16477655/4c58b8a2-3e48-11e6-8371-6e33c6a17cb1.png)

**Comment by shivani2910** [comment]
@SpiritWolfie thanks for reaching out. We've checked and noticed that this issue has not appeared due to the patch provided by us. Token error is coming without applying the patch too.

This happens when user right clicks on Accept Friend Request link appearing on another user's profile while user is supposed to simply click on that link and form would have opened in a pop-up on the same page, which works fine. But we've still forwarded this issue to our team so that they can investigate and fix this in next version.

Thanks & Regards,
Shivani

**Comment by SpiritWolfie** [comment]
@shivani2910 

Thank you, it honestly shouldn't matter if someone opens that window up in a new window or not, it should still work properly (allot and I mean allot of people like to use the open buttons in new windows feature to keep from losing the pages they are on etc, I myself and every room-mate I have does this)

So having a fix for this would be amazing. Thank you <3

**Comment by smazurov** [comment]
Fixed in [4.8.12](http://blog.socialengine.com/2016/07/07/socialengine-php-4-8-12-is-here/)
