### ISSUE TITLE
Add animated GIF support

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#455]
Website's and website software in general for about 30 years has naturally supported .gif images

For whatever reason gif profile avatars don't work, is there some kind of code in place/setting that has stopped this? and if so is there any way I could enable this as its a highly requested feature in my community to have animated thumbnails/and avatar pics

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , We would like to tell you that we have not worked on this feature in our latest release, so, there should not be any change/issue possible regarding working of .gif images in SocialEngine and these images should work as these used to work before on SE. .gif Images can be uploaded as profile pic or as an upload to an album in SocialEngine but .gif images having animation effects are not supported in SE, but we have plans to make .gif images fully compatible with SE in our future releases.

Thanks!

**Comment by SpiritWolfie** [comment]
@Khushboo016 

I'm aware gif images can be uploaded as a profile pic, the issue is they don't animante, it's good to see you plan to include this (i'm not sure why this was coded to be ignored in SE to begin with) animated support has been a natural thing in almost all websites and you kinda have to put code in the software to 'not support it' 

Until this is released is there a line or something I can change to allow thumbnails profile images to be animated?

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , The feature to support animated GIFs is already included in our plans for our future release 4.9.0 as you can also see from https://github.com/SocialEngine/phpv4-issues/issues/165 that this feature has been added to 4.9.0 milestone. 

Regarding "Until this is released is there a line or something I can ":
Unfortunately we cannot provide you any code customization to achieve this feature on your site until we implement this in our module, because to make this feature happen, our development team will need to work on the whole module and edit the source code at several places, so that wherever there is image supported in SE, animation would also be supported.

Thanks!

**Comment by Elshara** [comment]
I didn't know that .gif images weren't supported.

**Comment by leandrotavaresrocha** [comment]
When we will have a support to gif? Gif are really popular and Facebook, Twitter and your concorrents (PHPFox) have support.

**Comment by pacodrums** [comment]
Please do not take more, it is a necessary function today

**Comment by Elshara** [comment]
Dolphin by boonex also has support for this.

**Comment by JonSimon93** [comment]
GIFs are the best, this will be great addition 💃

**Comment by Elshara** [comment]
Yeah I agree.

**Comment by Elshara** [comment]
:)
