### ISSUE TITLE
Profile question links

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#468]
Step 1, Add profile question with the Multi text insert box
Step 2, Throw a URL of any kind in there
Step 3, Copy URL and paste said url into notepad or pad of choice

Results:
It doesn't copy and paste correctly
if you add link, its not clickable

Expectations: I expect the platform to not be adding random dashes and stuff into things that's put into that field, I also would expect it to make links clickable

Why?: if you want to have a multi field for linking to profiles such as steam profiles etc this would be useful instead of having to manually grab the url, Grabbing url manually is also pointless with this bug randomly inserting Chars.

Fresh install of 4.8.12

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , I've checked this issue, links added to a field of type multi-line text input are not clickable. We'll look into this issue to resolve this.

Thanks!

**Comment by SpiritWolfie** [comment]
@Khushboo016 it's not just that, if you do post the URL in there and copy and paste it into say a notepad you will also notice it creates random dashes.

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , Please replace the content of the file /application/modules/Fields/View/Helper/FieldTextarea.php present on the server of your site with the content provided at the below link: https://gist.githubusercontent.com/Khushboo016/c84aec978e7a5b4a5d54318058bb5ef0/raw/e472f81a2ecf284df014c5c3d9872246e3b23c95/FieldTextarea.php 

This would resolve this issue related to URLs, and we cannot update the content of the mentioned file in our source code of SE because of some security issues.

Thanks!

**Comment by SpiritWolfie** [comment]
@Khushboo016 so the thing you provided me has security issues? what kind

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , We meant that the changes that we have provided to you to make the links clickable would allow to have clickable links everywhere on the site wherever there is a text-field or text-area provided and this is not something that every site admin would like to have on his site, so that's the reason we cannot perform the said changes in our module.

Hope you understand our point here, Thanks!

**Comment by Elshara** [comment]
Experiencing same issue here.

**Comment by Elshara** [comment]
The fix doesn't work.

**Comment by Elshara** [comment]
I don't know why the dashes even exist. Edit the file described above and change the number 10 to a very high number and save changes. Links work properly but it's only a temporary fix.

**Comment by Khushboo016** [comment]
Hi @Elshara , Regarding the issue related to random dashes, I have replied to your similar query in the issue https://github.com/SocialEngine/phpv4-issues/issues/475, so please reply there.

Thanks!

**Comment by Elshara** [comment]
Okay

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#25

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
