### ISSUE TITLE
Add ability to individually post to different networks

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#477]
@smazurov 

if there is a way I can make this so on my end , Please for the love of anything holy advise me how to do this, This would resolve allot of issues my community is having 

As it stands, from what I can see, there is only the ability to send messages to 'all networks' and not just certain ones your apart of

Having the ability to make posts directly to different network's is how it should have been designed to begin with....(so only people in these networks can see the posts) the current way it is designed kinda makes the whole network thing silly and pointless if you can't choose which networks to post to vs all networks getting the post.

I.E (in example)
Lets say I'm apart of 3 networks, Anime, Games, Computers
As network currently stands if I make a post to 'Anime' All 3 networks would see the post
I should have the ability to choose to post to Anime only, so only anime people see it.

By not having this implemented it makes networks completely useless and pointless, there would be no point in joining different networks if all networks can see anything you post on a network feed.

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , There are third party Advanced Activity Feed based plugins available for SocialEngine which offer such kind of advanced features and many levels of privacy can be set for the posts made, so you can refer to those plugins from http://www.socialengine.com/customize/se4/plugins section of our site. 

Thanks!

**Comment by Elshara** [comment]
Networks don't really function that well to begin with. I never use them. To filter network posts you would have to first create in default social engine core plugin the ability to choose who sees your post, which isn't a social engine supported feature. It would be easier to redesign networks so that people could only post to a certain network in general, rather than having all the networks you belong to act as a custom category of site user. I can see the need for it but social engine doesn't have this functionality and probably never will. Networks are designed to bring people together, what you're talking about would be a group more likely that people could post in that just acts like a network but people can join or leave it separately. Integrations of networks and groups work well if people join only one network. But the more networks they join, it isn't as if you can prevent them from doing so and the same goes for groups, it effects the entire site, not based on user specific data. Social engine isn't a responsive social platform. If it were, profile types would act in place of networks.

**Comment by Elshara** [comment]
I think also networks are designed as such to allow people who only are a part of those networks to see what people post. So say for example you make a post to your example network, anime. People who are a part of that network see it, but people who aren't, don't. Networks automatically filter out people who can't see it from people who can. For people to be able to post specifically to a network, they'd have to edit their privacy settings to do so, so that if you only wanted to see posts belonging to certain networks, you choose what network you want to view and then post there.

**Comment by Elshara** [comment]
What you could also do is make posts friends only. That way if you have one way friendships set up, if you aren't a mutual friend of someone, then you don't see that persons posts at all. You can't of course post to a group of people without creating the group first, so being able to have social engine add the ability to connect certain friends to a network would make this a possibility.
