### ISSUE TITLE
Fix Role Admin/Super Admin

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#478]
As it stands, Admin/Super admins aren't really that, No matter the options you choose or the power you give, there are a few things that SHOULD BE HERE

Site staff should be able to see all feeds, even if someone has their profile set to friends only, or posting to networks we're not apart of, The whole point of staff of a "Social website" is to ensure your website rules are being followed, and nothing illegal is being done or said using your website, 

For a website that runs 14+ (Community's) it is federal law we police our websites (yes really, in the USA anyways), we are unable to do this if we can't see what some people are saying 

to put simply, there needs to be a setting where the site owners can give certain roles the ability to 'see' all posts made on any activity feed etc.

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , In SE Super Admins and Admins can view every other member's profile no matters what privacy settings have been done by the member, so there is no need of any such setting where the site owners can give certain roles the ability to 'see' all posts made on any activity feed etc. Please explain your query again if we misunderstood it.

Thanks!

**Comment by SpiritWolfie** [comment]
@Khushboo016 

Please re-read

That has nothing to do with what I'm talking about, I'm not talking about profiles.

**Comment by SpiritWolfie** [comment]
The Activity feed (The wall you post things on) If set to public (-everyone-) If say User A sets their profile to friends only, Staff can not view it, Same if they post in a group and set the group to private 

Even using the default settings (SE Freshly installed) Staff can not see "All feeds", This is bad very bad.. Period, doesn't matter if your site is 14+ or 18+ 

Staff are appointed "Staff positions " to enforce rules, you can't do this if people are posting potential illegal content that staff can not see, because social engine restricts staff from seeing all feeds.

I don't know any other piece of social networking software on the planet that does it this way (That I've used anyways) this choice makes sense if its a moderator but I'm talking Admins/Superadmins (Website owner) Sure we could check the Mysql most likely for this info but that is allot of extra effort that should be viewable on the feed 'period'

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , I understood your point here and have added this suggestion at our end for internal team discussion regarding its implementation in future releases.

Thanks!

**Comment by eugene-wh** [comment]
@SpiritWolfie we might consider adding this as a feature for our Moderator Toolbox plugin. So moderators (+admins) will see all data regardless of visibility settings

**Comment by SpiritWolfie** [comment]
@eugene-wh 

I firmly believe you shouldn't need to pay for features that should be built into the Engine to begin with, No idea who thought it'd be a good idea to have a administration design without the ability to administrate.....

I don't mean to sound rude, but I'm sick of spending money to buy plugins to extend Features that should exist out of the box, (I have a programmer building me a custom platform so I can get off SE)

**Comment by eugene-wh** [comment]
I agree with you about administration features. We have built this plugin as we needed a way to efficiently manage users - it is impossible to filter users in SE when you have a lot of results. When some clients had 10K spam bots signed up - it was a headache to clean up from the standard admin panel.

But I kindly disagree about other features - the core itself should be clean, fast and minimalistic. So you can extend it to fit different community needs. It's far from perfect right now, but still better than anything else available on the market (out of box).

**Comment by SpiritWolfie** [comment]
@eugene-wh 
I think I'd prefer Oxwall or such at this point

Out of the box allot of SE Features don't work as they should or intended, I can break a fresh install of SE in about 5mins flat just using the admin panel... 

Se has much to be desired for a active use community, Blocking doesn't work and this has been one of the largest complaints for my community

SE makes it very difficult for normal programmers to deal with the code as well, you need a specialized coder at a insane cost to do anything small or medium size, certian things that should take a few moments to fix takes Hours with SE, I know because I've had a few programmer friends who do high end coding for a living look at the code and most refuse to touch it including my company's in-house coder

I disagree with your statement , while I agree it should be clean and minimalistic, that is no excuse for features being designed 1 way, or -partially working- 

Their is so much wrong with SE and I'm not tryint to be mean here but myself and my entire community can't wait until our custom platform is done, I've invested over 10 grand into SE (including plugins and fixes) and nothing still wants to work right or how it should. I'm done investing into a platform where the plugin people barely speak English etc, or you have to paypal dispute them because they falsely advertise something.

**Comment by eugene-wh** [comment]
> I can break a fresh install of SE in about 5mins flat just using the admin panel...

Could you provide some details? I'm interested as a developer.

> Se has much to be desired for a active use community, Blocking doesn't work and this has been one of the largest complaints for my community

That's true, we had to add that on our own as well.

> SE makes it very difficult for normal programmers to deal with the code as well

That's the cost of using Zend Framework. I do remember SE v.3 which was clean php + smarty + some libraries. It was really easy to modify, but also it was quite a challenge to maintain for big communities.

**Comment by SpiritWolfie** [comment]
@eugene-wh 

I'd be happy to assist, I've actually made offers to the team of SE before as I've been testing a professional tester for years, I've worked along side of Linden labs, Riot games, Blizzard ent as a beta tester etc...

Do you have a email address or something I can reach you out as a conversation isn't really meant for Github.

**Comment by Elshara** [comment]
To add to this, admins and super admins should have more front end controls to edit things on the fly such as groups. And there's no way to change the owner of a group or manage a group as an admin role, you have to actually be the groups creator just to get that feature and as a super admin, it's frustrating to have to delete groups that have bad posts in because say if you want to edit something on a group member or event profile, you can't do that unless you log in as that user which is very insecure and having to do mod tasks in the control panel should be a last resort. Period.
I'm glad you brought this up. Zend framework should be updated as a major priority bTW. The longer it stays dormant, the more likely I'm tempted to develop an export script for SE and move to a custom built platform myself. Zend might make modular functionality easy, but it also means developers can take advantage of core features lacking in a script that needs them.
If you want me to vote for you in the CMS critics awards, make plans to fix up Zend.
Yes SE is expensive. Especially since its most famous rival could sell a script for $99.00 and you get much more privacy settings out of the deal. Yes some customization options are crappy with PHPfox etc but even Boonex has the ability to update Dolphin for MSQL queries that get fixed up. SE can break just by adding a wrong syntax character in a .tpl file. I think that's something to worry about as a security risk for sure.
So major in your face security risks ought to get solved because they are more than a little obvious to the typical social engine admin. When you have to use a plugin to get core functionality out of something SE doesn't have, you then rely on more developers to update their software which is another security risk. This is because it leaves vulnerabilities open to more advanced users as the data gets accessed and recirculated. This means core updates to security and allowing core functionality to have better admin access is essential in this regard. For instance, uninstalling a package. What a bloody head ache. Yet another security risk. Most members don't know admins have to log in as them to make something as simple as a spelling error if you care about it to a profile. Security risk. The one thing social engine does well is put up third party guest posts on their blog. it's always nice to see that in the dashboard, at least that's one thing you update on a by weekly basis.
Other social software has security implementations two, but its because people like us who notice them get talking as a group that they get fixed. The more disfunctional a software is for any user, the more likely someone will not use it because of ease of use issues. Which relate to matters of security if not fixed.

**Comment by SpiritWolfie** [comment]
@eugene-wh 

You haven't gotten back to me with any info so we can talk about these issues

Do you wish for me to give you the details? I just don't think posting it here on git hub is right as this is meant for issues not generalized talking.

**Comment by eugene-wh** [comment]
Why not post it as a separate bug report? I mean if you can break clean SE after few actions from admin panel - it's definitely a problem. I was under the impression you are talking about a specific bug.

**Comment by Khushboo016** [comment]
Hi @Elshara , 

Regarding " it's frustrating to have to delete groups that have bad posts in because say if ":
Admin can delete any post posted by others in a group without log in as the user who created the post, so there is no need of deletion of the group in case someone makes bad posts. 

Regarding Zend framework, we would like to tell you that we have plans for upgrading Zend and PHP in our future releases.

Importantly, it would be great @Elshara , if you can make points of all the queries or issues while reporting an issue, so that we can get it fast and better. 

Thanks!

**Comment by Elshara** [comment]
I'll do that. Thanks for the reply!

**Comment by SpiritWolfie** [comment]
@eugene-wh 

Please read this - 
https://excreators.com/community/forums/topic/130/thinking-about-se-stop-read-this

Sorry for the late late late response, I was in Iowa for half a month visiting..

It's not just a 'specif bug' it is multiple bugs, Social engine has way to much to be desired in general and I even wrote about it on ex-creators on what allot of the issues are, and how i've felt trying to relay this info to SE, 90% of the time they closed my tickets telling me its my install, even know we've followed their instructions to a T, set it up 'in house server box' that we had physical access too, allot of my suggestions are ether ignored or simply closed, a good chunk of my bug reports in the past was closed pre-maturely even know I was able to prove the problem with countless screenshots showing how to 'reproduce it' 

this is why I offered to talk to you more directly vs here, I can show you allot of problems and also tell you what SE desperately needs, as I run a active community, Not sure how many SE people actually run a active community that actively posts and that has a few different needs, but I do, and Social engine with all the plugins I bought isn't doing what I need it to do

start with a example

bug 1: some silly coder on the SE team decided they'd be super cleaver and design blocking to work 'profile based only' and at that one -way- only, I have never NEVER seen any software/website with blocking since the year 2000 do it this way EVER, why blocking was not designed correctly (To actually BLOCK Someone - thats the whole point of blocking- still has me mind boggled how this got past Q&A Testing and why it was allowed to released this way

bug 2: under profile questions, add a profile question called Species, then try to list X amount of species, that part will start wigging out and acting oddly after you hit x amount..

Missing Feature that should be in the core (None plugins) vers of SE
Blocking

The ability to actually freaken Administrate, Administration is virtually none existence in SE without being forced to use database tables for the info you need, The entire ADMIN section needs a complete utter redesign, some things that should be here and we shouldn't have to PAY FOR - Temp suspension, Logging (<------------------------) , Better Abuse report system, The ability to see deleted comments/posts/pictures/blogs etc..., The ability to set something to 18+ and actually have a warning pop up, better Power given, as I've seen its pointless to have moderators, because it requires way to many things to be adjusted just to give them power of any kind, you have to go into every little plugin, every little addon and adjust their power, Their should be a way to globalize this across the board period.... Banning/Spam needs a redesign as the way its designed to much info is missing it does not provide the info you need to report abusive people,

While I want to help SE, I feel SE Doesn't want help from those of us who actually truly use it, i've gotten into arguments with some of the folks because as per usual I get told "hire a developer, or you don't know what your doing" I feel as if these people haven't actually used SE with a active community with needs.

Take SE to any actually programmer, not a "SE Devoloper" but a programmer, they will refuse to even touch the code because how badly most of the code has been designed and the way they go about things, I have a coder on my team for my website and he said things that take like 3 mins to fix for most websites, takes like almost 30mins to a hour because of the way SE decided to go about it.. and this coder works for Oracle (Java company)

now if a developer such as your self wants me to talk to you about things you can add to your plugins that would help people like me who have different needs, I'd be interested in spending my time showing you the things that could be approved on , what needs to exist etc, and I'm sure you would have a ton of boosted sells because of allot of what I talk about is also stuff other SE owners need as well, I have multiple SE owners on my skype list and we've spoken about features we need as website owners.

in return for my time I would ask for a copy of both the toolbox plugin and the plugin you design using my years of experience to help fix (That would be my cost for the help)

**Comment by DonnaScriptTechs** [comment]
@Khushboo016 please update this report with our progress on this topic. Our client wants to know our status. Thank you.

**Comment by DonnaScriptTechs** [comment]
@smazurov or @shivani2910 can you please check this as well? The SuperAdmin user is unable to see the status updates made by members that have their privacy at Only Me or Friends Only. This could end up being a security issue and/or cause litigation if things are posted that are "adult only" or that are illegal in some areas. I've not tried an Admin user as the SuperAdmin should see everything posted on a site.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

This "IS" a security issue, there is no 'end up' to it, if someone posts something illegal using a friends only profile, staff can't see it so we can't deal with it, I am a super admin and I can not see things posted on a private profile as well as admin or moderator, here's what it affects

Lets say someone uploads CP to my website using this feature... I have 72hours or less to remove it and report it to the FBI, by Federal law, local law and cybertiplines requirements, and Hosting law, if not I can personally face legal action.... This is a security and LEGAL issue and should be fixed ASAP.
Private profiles
Profiles set to friends only

Also if a profile is set to private or friends only, users can not block those profiles as well. but this issue should be a different complaint..

Thank you for looking into this personally!

**Comment by DonnaScriptTechs** [comment]
This is fixed for our 4.9.3 version once we release it.
