### ISSUE TITLE
Polls Need Some Work

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#480]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?
1. … Polls cut off answers.
2. … You cannot edit a polls answers.
3. … Polls that post do not show the ability to see who has voted.
## What happens?

… Polls cut off answer options at a certain amount of characters. There is no way to change this. Polls also prevent you from editing a poll under manage polls apart from privacy. Polls additionally do not allow you to control how many answers a poll can have or whether or not they can be attached to an existing site post. When viewing a poll, you cannot see who voted if they choose not to write a comment.
## What were you expecting to happen?

… All of the above to be possible with polls. Essential for community feedback.
## Any logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```
## Any other comments?

… I can't use polls effectively to gather feedback required to engage members in site updates.
## What versions of software are you using?

**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.12

**Comment by Khushboo016** [comment]
Hi @Elshara ,

Regarding 1.
If the answers are longer than the predefined length possible, then it trims off the extra text. We have added this issue in our internal bug tracker and will resolve this in our future releases.

Regarding 2.
There is no option provided to edit polls keeping in mind that if the creator of the poll edits the description of the poll or edits the options/answers to the poll after someone has voted on the poll, then if the modification is such that it changes the meaning of the answers or of the description of the poll itself, then there would be no significance of the already done votes. This is because the votes are done based on the meaning of the question and answers to that question and there would be no significance of votes that is the results would be misleading, if the meaning of the poll or of the answers to poll changes after vote has been done. 

Regarding 3.
As we said in your another issue https://github.com/SocialEngine/phpv4-issues/issues/432 that we have added this feature at our end for internal team discussion.

Thanks!

**Comment by Elshara** [comment]
But if nobody has voted yet and you wanted to change something like
cut off text in one of the answers before someone has voted it should
be possible to do that.

**Comment by Khushboo016** [comment]
Hi @Elshara , We've added this suggestion at our end and will discuss it with our team.

Thanks!

**Comment by DonnaScriptTechs** [comment]
Issue 2 is already fixed for 4.9.0.

We will keep this open for issue 1.

**Comment by DonnaScriptTechs** [comment]
marking a bug as we mentioned it was one and it is still an issue in 4.9.2

**Comment by DonnaScriptTechs** [comment]
This is fixed for our 4.9.3 version once we release it.
