### ISSUE TITLE
Security Flaw: Email is being passed in URL 

### ISSUE THREAD

**Issue by dreamgeekcoder** [SocialEngine/phpv4-issues#493]
Verification emails pass the **actual** Email into the URL.  This is a known security flaw that causes issues with sites like Google Adsense, Norton Safe Sites and many others.
## What are the steps to reproduce this issue?
1. … Create an account
2. … Click Verification Email
3. … Url that is sent to the website will look like this - http://www.SocialEngineSite.com/signup/verify/email/redacted@example.com/verify/hjd4323526e9c23234ffvf840bc7d3f5
## What happens?

… Passing Personally Identifiable Information PII to a URL is a serious no no to Google and many other online publishers. As well as ripe for phishing abuse. Url can be sniffed, cached, and exploited in many ways.  It never should be passed in the URL.  You can read more about how this violates Google Adsense here - https://support.google.com/adsense/answer/6156630
## What were you expecting to happen?

… This should be using a USERID or other piece of not personal information like email in the URL
## Any logs, error output, etc?

http://www.SocialEngineSite.com/signup/verify/email/redacted@example.com/verify/hjd4323526e9c23234ffvf840bc7d3f5 
## Any other comments?

… I hope this can be address ASAP as this is a serious security flaw.
## What versions of software are you using?

**Operating System:** …

**SocialEngine PHP Version:** …

**Comment by amandablain** [comment]
After once again being informed by support that this is MY issue - "This isn’t a bug in the platform. It can be categorized as a compatibility issue with Google Adsense TOS. I suggest submitting a feature request in our tracker and our development team will consider implementing your suggestion in future releases. however, I don’t think the suggestion will be implemented within 30 days so you might need to hire a developer to make the changes for you."

Ridiculous.

I looked into the code myself and fixed it in roughly 15 minutes. The support for this platform is horrible and I regret every day that I chose this platform. 

The fix for this is to edit the email that is not required in any way to be there since it uses the User ID in the database anyway... Edit  -
    /application/modules/User/Plugin/Signup/Account.php
change line 246 -    'email' => $user->user_id,
and

/application/modules/User/controllers/SignupController.php
line 165 - $user = $userTable->fetchRow($userTable->select()->where('user_id = ?', $email));

All done.

**Comment by eugene-wh** [comment]
@amandablain great job!

Support is pretty hard to get through to actual developers sometimes. They get a lot of feature requests (sometimes ridiculous), but this is definitely not an excuse to avoid reviewing every request (especially well reported with links to Google Adsense TOS).

From my personal experience - a lot of communities skip email confirmation emails. This step breaks the signup experience, but doesn't stop spam bots unfortunately.

**Comment by Elshara** [comment]
The same problem is found with invite links.
As well as contact form messages.

**Comment by DonnaScriptTechs** [comment]
I apologize for this not being seen sooner. I've reported it to our internal bug tracker. Thank you for your report.

**Comment by DonnaScriptTechs** [comment]
@dreamgeekcoder or anyone else, if you feel that your support issue is not being taken care of properly, would you please ask in the ticket to be sent to a supervisor? Either Kyle, or Donna (me) if Kyle is not available, will look at the ticket. We want our clients to be satisfied with answers, within our support terms of course. Issues like this should get more consideration.

**Comment by Elshara** [comment]
I applaud your efforts here. I think it's an awesome idea.

**Comment by dreamgeekcoder** [comment]
@DonnaScriptTechs I'm not even sure how that is possible. I've written supported and posted in here many times but the response is always its my issue and no one else has reported it. I'm pretty frustrated with social engine at this point because I'm not asking for vanity requests or new features but reporting CORE bug's that are constantly dismissed. Its pretty frustrating.

This bug alone I mentioned here is enough to cause insane amount of losses, hacking and major vulnerabilities to anyone with a SE site and the Social engine product and your team just dismissed it. Twice. I wrote internal support first about it before PUBLICLY POSTING A SECURITY VULNERABILITY like they asked me to do here.  No one touched it for 8 months. You seem to be trying to fix support up so I would seriously suggest having a look at why stuff like this keeps happening.

**Comment by DonnaScriptTechs** [comment]
We are improving the process. Feedback like this does help us to improve. Any time you feel that your reports are not being taken seriously, you can also use the contact us form and contact sales where Kyle will see it first. If you get an answer from someone else, you can ask for him directly or ask for a manager, which will also get to him. If that doesn't work, feel free to grab me on the community in my pm. I might not answer right away, depending on the time you ping me in my pm but I will answer when I'm on.

**Comment by Elshara** [comment]
Thing is, live chat or live call is basically the only way to ensure
you are heard. In order to make known your feelings, you have to
essentially except its a 50% chance whatever you say is taken
seriously. But to be repeatedly ignored is not okay and it has to be
addressed.
I admire your courage here dream geek coder. But you need to realize
things are much better now than they once were. I wish I could be of
better help but as a person in the same position as you here, it's a
matter of chain of command.
We're kind of like the people who bridge the final result and its
creators with the creation we make possible. But our tools, have to
come from a source, we have few interaction with in order to have the
means to make possible our wish to flourish as we desire it to be as
such. So improving how we interact with such people, should be a
priority and that means taking the good with the bad for all things.
But a common process of reaching out to people, must be something
anyone can freely access.
I can personally attest for Donna being available on her community
site for such to be possible. It may take some time, but chain of
command, starts with someone in the lead. She recently, has made this
happen. I do believe a better, brighter future awaits us.

**Comment by DonnaScriptTechs** [comment]
This is fixed for our 4.9.2 when it is released. If you still see an issue after you try 4.9.2, please submit a new issue. Thank you!
