### ISSUE TITLE
Editing a post not working, text blank

### ISSUE THREAD

**Issue by CostaWomen** [SocialEngine/phpv4-issues#494]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

When I write a post in groups and then tick to edit it, a blank box comes up.  See attached 
![screen shot 2016-09-16 at 14 08 50](https://cloud.githubusercontent.com/assets/22214479/18633626/7b3ca820-7e7d-11e6-9fd5-31aa8a123265.jpeg)

What are the steps to reproduce this issue?
-------------------------------------------
1. type a post in groups
2. click to edit post
3. the post comes up blank

What happens?
-------------

No text shows to edit

What were you expecting to happen?
----------------------------------

To be able to edit the text

Any logs, error output, etc?
----------------------------
No
```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
Safari 9.1.2.

**SocialEngine PHP Version:**
4.8.12

**Comment by Khushboo016** [comment]
Hi @CostaWomen , I tested this issue on my localhost and it is not reproducing there as shown in the attached screenshot the text is visible in the "Edit Post" box for editing. 
![working_fine](https://cloud.githubusercontent.com/assets/18209340/18699375/b0d82e6a-7fee-11e6-8fc3-2b82eae4e212.png)


So, this issue seems to be related to your specific installation, so we suggest you to open a support ticket at https://www.socialengine.com/client/ticket/create or email us at support@socialengine.com along with your site details, so that we can check the issue.

Thanks!
