### ISSUE TITLE
My site running too slow, How to resolve?

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#503]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?
1. … Crezilla.com
2. …
3. …

What happens?
My Website running too slow even at this point of time where hardly 2-3 users are present?
What could be the issue and how to resolve?

What were you expecting to happen?
It should load faster than this.
## Any logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```
## Any other comments?

…
## What versions of software are you using?

**Operating System:** … centsos

**SocialEngine PHP Version:** … 4.8.8

**Comment by Khushboo016** [comment]
Hi @rkrathor , If you feel that your site performance is not good then to increase the speed of your site, we would like to suggest you that:

1) Please install APC cache on your site. Please ask your hosting company about this. After enabling the APC cache on your site the page load speed will increase. Also, we suggest you to raise the apc.shm_size directive to 128MB. This needs to be done to avoid high fragmentation, which reduces the performance of APC.

A bit of warning, on some unix/linux servers, you may need to manually raise the value of the kernel.shmmax resource in order to allow APC to allocate 128M of memory. To do this, make the following change:

kernel.shmmax = 134217728

Also, please find below article for APC cache and other speed optimizations:
http://support.socialengine.com/questions/200/SocialEngine-Performance-and-Speed-Enhancement-Tips

2) Also, we suggest you to use MaxCDN Feature at your site for media, css and javascripts etc.
Using this, you can store content externally and this will increase the speed of your site.

Please find below SocialEngine.com URL for its set-up instructions:
http://support.socialengine.com/questions/188/How-to-use-the-CDN-Storage-Feature

3) Also, we would suggest you to enable ""Translation Performance"" setting in the Admin Panel - Settings > Performance & Caching section of your site. Please find below tutorial for this section:
http://support.socialengine.com/questions/182/Admin-Panel-Settings-Performance-Caching

4) Also, you can install third party plugin ""Minify"" on your site,  it will help your website run faster by removing unnecessary white space and comments, reducing HTTP requests and JS/CSS bandwidth etc. You can find this plugin from http://www.socialengine.com/customize/se4/plugins section of your site.
We hope this will help your site to gain a better speed.

Thanks!

**Comment by iborisovBG** [comment]
All system need to use longpolling + to be ajax based (this will up the speed of the engine) but there is a lot of work and may will be more easy to write a new engine
