### ISSUE TITLE
Sent message listing not coming correctly.

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#506]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?
1. … Go to My Messages, Compose new message and send to more than 1 people.
2. … Now go to outbox you will see your photo instead for to whom you have sent messages , second it will show no of people you send message instead of person's name.
3. … You can see the difference if you send message to single person.
## What happens?

Information doesn't come correctly after sending message to more than one people.
## What were you expecting to happen?

It should come with photo , name, message title and description instead of photo of person who send message and no of people message have been sent.
## Any logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```
## Any other comments?

…
## What versions of software are you using?

**Operating System:** … centos/ windows.

**SocialEngine PHP Version:** … 4.8.8.
![screenshot_6](https://cloud.githubusercontent.com/assets/10502380/19382195/c0bd1508-921c-11e6-9068-8e1d8ac45baf.png)

**Comment by Elshara** [comment]
I can confirm this issue exists on my end two.

**Comment by rkrathor** [comment]
Yas,
Its on the latest version (4.8.12) too, I guess?

**Comment by Khushboo016** [comment]
Hi @rkrathor , In case when a message is sent to more than one members, then only the number of people is shown in place of the names of all the receivers of that message in "Sent Messages" and the sender's profile pic is shown in place of receivers' profile pic. This is because, suppose if the number of people to whom the message is has been sent is 10, then there would be a long list of names to be shown in case if names are set to be shown and there would be 10 profile pics to be shown in place of receiver's pic. So, it would not look good if all those names would be listed there along with all the profile pics in the list of messages in "Sent Messages". So, this doesn't seem to be a good idea to show the names of all receivers along with their profile pics. The list of all the people to whom message is sent can be seen by opening that message as shown below:
![message](https://cloud.githubusercontent.com/assets/18209340/19473658/23651284-954a-11e6-8879-6133e6303900.png)

**Comment by rkrathor** [comment]
Hi @Khushboo016 ,
Thanks for your reply,
So can you tell how to achieve this? I mean what kind of code change required for this?

Thanks again !

**Comment by rkrathor** [comment]
Hi, @Khushboo016 ,
Still waiting for your reply??

Thanks
Rajesh

**Comment by Khushboo016** [comment]
Hi @rkrathor , First of all, we are sorry for delay in responding back to you. We have forwarded this to our development team to figure out a solution for this that can be implemented in future releases. But for now, you can get it customized at your end if you need it. You can refer to our third party developers for this customization from http://www.socialengine.com/customize/se4/developers section of our site.

Thanks!
