### ISSUE TITLE
Add spell checking

### ISSUE THREAD

**Issue by sunfellow** [SocialEngine/phpv4-issues#508]
I have two feature requests:
1. We desperately need a spell checker that automatically checks the spelling of forum posts, blog posts, private messages, and other comments on the network.
2. We also need a way to resize windows so more content can be seen while writing posts.

Any idea when these features might be included? Thanks!

We're using SocialEngine 4.8.12
https://nhne-nde-network.org

**Comment by Khushboo016** [comment]
Hi @sunfellow ,

Regarding 1.
I've added your suggestion at our end for internal team discussion regarding its implementation.

Regarding 2.
There is a Full-screen button available in the TinyMCE editors provided in SE using which the windows can be re-sized to full-screen while writing posts/text. Please see below screenshot for reference:

![resize](https://cloud.githubusercontent.com/assets/18209340/19957867/5e1bcec2-a1c0-11e6-9667-aefe2e975c49.png)



Thanks!

**Comment by sunfellow** [comment]
Thanks, Khushboo! I missed this! That solves my problem...

**Comment by smazurov** [comment]
What browser/operating system are you running that does not have built in spell check?

Both MacOS and Windows have had built in spell checking for a few major releases already.

**Comment by SpiritWolfie** [comment]
I can confirm this, I have the latest Firefox and Latest chrome, and spell check does not work with Social engine, Works in Joomla, Dolphin, facebook, oxwall etc though.

Tested on Clean install's on SE as well, problem seems to happen in forums and such as OP said.

**Comment by smazurov** [comment]
This is good info, we'll make sure spellchecking works in 4.9

**Comment by SpiritWolfie** [comment]
@smazurov 

for clarity sake, this has nothing to do with the browser or OS, more so about the platform not supporting the built in spell checkers, if I remember correctly you have to actually tell the platform to allow chrome or firefox the ability to use Spell check, (its like a google hook or something depending on what spell checker you wanna use)

but this is been a problem since I first bought SE, I'll do some more testing but I think its on all core features such as wall and what not but i'll double check and try to make a list where spell check has not been included.

**Comment by Elshara** [comment]
I two support my vote for a spell checker. It's easy to do in tiny mce. If it ever gets updated.

**Comment by shivani2910** [comment]
This has been implemented for 4.9 when it is released. We have upgraded TinyMCE Editor and added support for browser spell checker in 4.9.

**Comment by Elshara** [comment]
Awesome!
