### ISSUE TITLE
New Website

### ISSUE THREAD

**Issue by caseynally** [SocialEngine/phpv4-issues#512]
New website is showing not downloads for my already purchased licenses (4 seperate site licenses) and none of my purchased modules. (All modules except the Mobile module since I do not own that one)

Also your marketplace shows no entries for any listing type.

**Comment by shivani2910** [comment]
Hi @caseynally,

Sorry about the inconvenience caused to you. We're working on the fix and it would be fixed in a few hours. I'll notify you again once it's up and fixed.

Regarding Marketplace, we're in the process of reviewing apps from experts and that should also be up very soon.

Thanks for your feedback. Please share if you have any other queries or feedback.

Thanks & Regards,
Shivani

**Comment by mujaksaba** [comment]
Hi,
I have the same problem @caseynally , @shivani2910 . I hope that the problem will be resolved soon.
Regards

**Comment by eugene-wh** [comment]
As a developer, I have a problem with image uploads, email confirmation there.

**Comment by poeticjustice** [comment]
Hi 
Social engine solutions doesnt appear on the site, and they have been fantastic to me, i left them such positive reviews, i feel its a shame all my reviews have been wiped away, i left reviews to help future buyers

**Comment by Khushboo016** [comment]
Hi @eugene-wh  ,

Regarding "As a developer, I have a problem with image uploads, email":
Please attach a screenshot here showing exactly where you're facing issue in uploading images.

Thanks!

**Comment by eugene-wh** [comment]
Already sent details to support (when the beta period started).

**Comment by Khushboo016** [comment]
Hi @poeticjustice ,

Regarding "Social engine solutions doesnt appear on the site, and they hav":
You don't need to worry as we do have plans to migrate reviews of those experts who participated in the beta launch of our website that was an option open for all the developers. But currently, we're in the process of fixing a few small issues on our new site and after that's done, we'll soon be migrating the reviews. 

Thanks!

**Comment by poeticjustice** [comment]
@eugene-wh ohhhhh Eugene your from webhive, i dropped you a message if you can check it out soon matey

**Comment by Khushboo016** [comment]
Hi @caseynally , @mujaksaba , 

Regarding "New website is showing not downloads for my already purchased licenses":
This issue has been fixed, you would now be able to view all your purchased licenses and plugins in your client area on our website. Please check and let us know if you still face the same issue.

Hi @eugene-wh , 

Regarding "Already sent details to support (when the beta period started).":
We've received the details sent by you and as we've replied to your support query that we're working on this issue and will get back to you soon, once we get a solution to this.

Thanks!

**Comment by Vaibhavagarwal0807** [comment]
Hi @poeticjustice,

    We are here, but were busy with the new upcoming plugins and the new Responsive Vertical theme. Since, we are not clear of the review import process, we too are just waiting. Waiting for profile approval first and then will work for mods approval.

**Comment by eugene-wh** [comment]
@Khushboo016 thank you. I would greatly appreciate faster turnaround if possible. 

Our sales suffer while we are waiting for this problem to be resolved. I'm not sure I understand what takes so long to resolve considering the issue was submitted more than a week ago. 

I would already re-upload images (as support suggested), but it's impossible to do while account is 'pending'. Could you approve the account so we can fix this ourselves?

**Comment by Khushboo016** [comment]
Hi @eugene-wh , As I've already replied to your support query that your expert application has been rejected, so that you can submit it again with new images (of smaller sizes). This time, please make sure that you preview the application before you submit it, so if there would be any issues, then those can be fixed before submission.

Thanks!

**Comment by poeticjustice** [comment]
@Vaibhavagarwal0807 
OMG Social Engine Solutions i have just seen your Vertical Theme, I absolutely love it.

This is why you guys are the best Social Engine developers.

I love this theme.

**Comment by poeticjustice** [comment]
@Khushboo016 you also need to update the site where comments are left, i left a comment for the awesome Social Engine Solutions..... i made spelling errors and cant edit my post to correct it

**Comment by Vaibhavagarwal0807** [comment]
@poeticjustice : Thanks a lot for your appreciation.. some more exciting plugins of your interest are coming soon.

**Comment by poeticjustice** [comment]
@Vaibhavagarwal0807 happy to test anything you have upcoming :)

**Comment by Elshara** [comment]
Sounds like things are changing for the better. I will say the new website does look much better than the old one.

**Comment by poeticjustice** [comment]
Im curious to know, is there a way of customizing the admin backend, for a member level who i allow certain functions to, but dont want them access pages or edit custom css or plugin settings, nor let them see links they are restricted from?

**Comment by Elshara** [comment]
No there isn't. It's strictly there to give admins access only.
