### ISSUE TITLE
The subscription tab is not visible on My settings. 

### ISSUE THREAD

**Issue by smarty005** [SocialEngine/phpv4-issues#541]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

What happens?
-------------
…

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**SocialEngine PHP Version:** …

**Comment by Khushboo016** [comment]
Hi @smarty005, Please make sure that on your site there are such Subscription plan/plans available to which the members can upgrade and for which settings are done in such a way that the plan/plans are shown after signup. 

And please make sure that anyone Payment Gateway should be enabled on your site, otherwise Subscription plans will not be viewable to members.

Thanks!

**Comment by Elshara** [comment]
Also be sure that they are published.
