### ISSUE TITLE
The SE4 SEARCH feature does not search/find basic pages created via Layout Editor and blogs feature.

### ISSUE THREAD

**Issue by thespidirman** [SocialEngine/phpv4-issues#547]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Create a page via the SE4 'Layout Editor' including meta tags entries
2. …Save and then search for parts of page name, meta tags, etc.
3. …Also search for Parts and full user names of standard members

What happens?
-------------
Search will yield nothing found response.

What were you expecting to happen?
---------------------------------
Basic search should find users, pages, blogs etc. created via SE4 functions.
It appears to find pages created via groups, events, and some other plugins ok.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…Sadly this has been a bug for several years and while I was thinking we were not setting up correctly or that the issue was with a 3rd party plugin, turns out its the standard SEARCH functions of SE4.

What versions of software are you using?
----------------------------------------
We're currently using SE4.8.12. 
But this problem was reproduced in your Travel demo site. (see attached)

![se4usersearch-1](https://cloud.githubusercontent.com/assets/25298888/22532052/7a1fe05a-e8aa-11e6-82de-4f260c291c9b.png)
![se4usersearch-2](https://cloud.githubusercontent.com/assets/25298888/22532059/871289e8-e8aa-11e6-81da-e23e68b74fc9.png)

![se4blogsearch-1](https://cloud.githubusercontent.com/assets/25298888/22532063/8dd4956e-e8aa-11e6-886a-e32fe4d458f8.png)
![se4blogsearch-2](https://cloud.githubusercontent.com/assets/25298888/22532070/928fa83c-e8aa-11e6-9be2-431188612d69.png)

**SocialEngine PHP Version:** …

**Comment by DonnaScriptTechs** [comment]
@ staff, also see ticket 25047 in support.

**Comment by Khushboo016** [comment]
Hi @thespidirman, We have added this issue to our internal feature tracker that global search performed does not take into account the custom pages created via Layout Editor whenever the search is done and the search results exclude those pages. Hopefully, this bug will be fixed in our future versions. The feature would work as if a user has selected to show a custom page in search results from "Edit Page Info" section of Layout Editor, then the global search will take that page into account whenever a search is performed on the site and one more filter like "Site Pages" or "Pages" will also be included in the list of filters for global search.  

Thanks & Regards!

**Comment by Elshara** [comment]
Awesome. You do realize Social Engine a few versions back disabled include page in search results area.

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
