### ISSUE TITLE
Suggestion-New features for Share option

### ISSUE THREAD

**Issue by GabryNet** [SocialEngine/phpv4-issues#553]
Hello everyone, as we all can see the new 4.9 is coming with amazing new features and we are all grateful to SE Team. I have a suggestion that i think is too late to appear with 4.9 but maybe can be a feature for the next versions. I think the Share option is too simple as we can share only on the Wall again with a custom message ... it will be nice if we can have more options like share for all the friends, or only one friend ,something similar to facebook ... thank you SE Team !

**Comment by poeticjustice** [comment]
@GabryNet buy Social Engine Solutions advance feed, believe me its totally worth it, i only use SES and also Webhive for restricting pages....... but Social engine Solutions do all my custom work, and the share feature in their plugin is awesome

**Comment by GabryNet** [comment]
Thank you for suggestion ... i know that we can buy a lot of plugins to replace and improve the default SE options or plugins ... but this is the idea ... will be nice to come with more advanced features for default options on SE.
I just look it on SES demo and they are using the default sharing from SE and also SEAO  adv. wall that i have now they use the default option... you can only re-post with a custom message ... i am not talking about sharing on other platforms like facebook ,google, twitter etc. , i have this options now on my website ... but if you want to share to a page that you have or for a friend that you have on the website is impossible.Try to take like demo facebook , you will see how many options they have for share.

**Comment by socialengineaddons** [comment]
Hi @GabryNet, we will be releasing this feature soon using which you will be able to share the feeds the way you have mentioned above using our [Advanced Activity Feeds / Wall Plugin](http://www.socialengineaddons.com/socialengine-advanced-activity-feeds-wall-plugin) . We hope you will like it and we will make sure it comes out asap.

**Comment by GabryNet** [comment]
Hi @socialengineaddons  ... thank you for your reply , glad to hear about this great feature coming up. Take care and good luck !

**Comment by Khushboo016** [comment]
Hi @GabryNet, Thanks for your good suggestion! Currently we do not have any plans to implement this feature in core SE PHP, but I have added your suggestion at our end for internal team discussion regarding its implementation in future versions.

Thanks & Regards!

**Comment by Elshara** [comment]
I'm also in agreement to be able to share with individual friends. I also think a mentions feature would complement this very much to be able to tag someone in a post, not just share it to them.

**Comment by Elshara** [comment]
Off topic but related, to be able to add custom sharing buttons when you click on share would be awesome.

**Comment by socialengineaddons** [comment]
>  I also think a mentions feature would complement this very much to be able to tag someone in a post, not just share it to them. 

'Tagging in posts' feature is currently available in the [Advanced Activity Feeds / Wall Plugin](https://www.socialengineaddons.com/socialengine-advanced-activity-feeds-wall-plugin). You can check this on [main demo](http://demo.socialengineaddons.com/members/home) after logging in as a test user.

**Comment by Elshara** [comment]
Looks cool. A tag cloud would work great, if people actually used them.

**Comment by gsf00001** [comment]
I would suggest to consider another option: lists and then sharing with the lists.  Too much is based on 'friends' and many sites have many relationships besides friends (family, neighbors, coworkers, etc.) or even different 'levels/types' of friends.  Limiting sharing to 'friends' is extremely limiting.  I know, I know - for some people on FB they have 1000+ 'friends' (which I would argue are not friends at all since I doubt the User knows all names, spellings, birthdays, addresses, etc. - it's a general catchall of either 'friends' or non-friends).  So, rather than friends or friend lists, it should be contacts (or whatever is a preferred term) where the lists could be titled however the User desires.

**Comment by Elshara** [comment]
Yeah custom lists sounds like an awesome idea.

**Comment by GabryNet** [comment]
That's why i said we need to improve the Share option , and sharing to one or more friends it was just an example for what we can have like more features ... again like example, for me as a radio broadcaster , if i find a subject i will like to share only with my co-worker for streaming and for the moment is just copy link and share it to his wall or chat (this will be for friends) ... also sharing to a list is very good if for example i want to have a funny moment watching a video with 10 friends ... and regarding the lists, i think the ADD TO FRIEND LISTS option should be more VISIBLE on the website something like a left-right widget on the profile page or browse members ... i had some cases when the users ask it how to create a list and put friends ... thank you all for reply's and suggestions, wish you a good day !

**Comment by Elshara** [comment]
Seems like a cool idea. Something similar to how the suggestions
plugin works might be what you are looking for in core functionality.

**Comment by leandrotavaresrocha** [comment]
@socialengineaddons, I remember that we discussed about a custom work to add this type feature to your advanced feed plugin. This improvement will still with the restriction of not create notifications and mail notifications while we share some content in a group or page?

**Comment by Elshara** [comment]
You figure it isn't possible?

**Comment by poeticjustice** [comment]
Seek the services of Social engine solutions, they have made me things that other developers said was IMPOSSIBLE

**Comment by leandrotavaresrocha** [comment]
@Elshara why is not possible?

**Comment by Elshara** [comment]
I didn't say it wasn't. I was in fact asking you if it was?

**Comment by leandrotavaresrocha** [comment]
I thought that you are afirmating that is not possible.

Anyway I asked them for this feature as a custom work because some of my users usually share links for their blogs in several groups/pages and I would like that instead of share a link each time was possible to share the content directly. The problem of this feature is that: 1- A content shared in this way doesn't trigger any notification related with content shared in a group, so if you signed to receive notifications for a group and reshape you will receive no notification, what is different from the default 2- A content reshared never go to a content profile tab. If I as a user share a photo in a group this photo go to group photo tab, but if I reshare the content doesn't go to the same place.

**Comment by Elshara** [comment]
I know. The whole system is flawed at the moment. You can't use the
share feature in an ideal way. I don't even think third party
developers have found a use for sharing to other parts of the site.
There does exist recommendation and suggestion modules but I don't
know if neither they nor advanced group modules have the capability to
do what you are suggesting.
I did try to advocate for the feature to be improved on. So far I am
not sure if it will or not.

**Comment by gsf00001** [comment]
@leandrotavaresrocha  Would using hashtags be a work-around for this?  SEAO does a decent job of sharing with their own Plugins, but sometimes I want to do things across the site - and their hashtag Plugin helps.  I'm thinking of this as an outside-the-box solution, but it still may not have any benefit to you.

**Comment by Elshara** [comment]
Could you, say, mention an entire group of users using a specific hash
tag, to tag it in? This could work if so.

**Comment by leandrotavaresrocha** [comment]
@gsf00001, this question is a bit more complex and maybe we will change the objective of topic, but let me explain in general.

My users are organized in pages and groups like in facebook and google+. The notification system (emails and activity notification) are importante because they bring people back to the website, around 70% of my users visit the website after a couple of mail notifications.

The point is that users use pages and groups to promote their website and this is a small pain. They share manually links in several pages and groups what in one hand flood the main feed and in other is a laborous work. A reshare system similar facebook system would improve this problem because: I- is possible to reshare content in several pages/groups with a few clicks, II- when someone share  the same content in several pages/groups this content is grouped.

I was talking about with SEAO about an improvement in their advanced activity feed to allow the reshare to pages/groups feature some months ago, but the project didnt go ahead because they said that was not possible to trigger notification when using this new feature (note that when someone reshare something on facebook or google+ the notification is triggered), neither content shared using this feature would go to the pages/groups tabs.

As the mail notification is important to my website strucuture this is a bad deal, because I am exchanging a feature that maintain users in my website by another that will only help some users life.

**Comment by poeticjustice** [comment]
Good to see email notifications are good to some users,
I find email notifications to be annoying to some users and having them activated you have a higher chance to start hitting spam, and once your on them black lists it can cause sooooo much issues.

That's why I purchased Social engine solutions push notifications, as I use https I have better control, so users get notifications on mobile devices and also desktop, I find this much better than email notifications.

I moved away from SEAO products and now only use Social Engine Solutions, maybe look at their share functions

**Comment by poeticjustice** [comment]
@leandrotavaresrocha contact Social engine solutions, with same brief for custom work on a SEAO plugin, believe me they have no problem custom working others plugins, fair quotes and their support is the best.

They once made me a plugin after 7 months I noticed a weird bug, but the bug was found to be core...... they fixed it and gave me all 4 files that fixed an issue....... they didn't even charge me 

Great team, tbf tho I have spent a lot with them, and I have helped them with ideas for plugins and features soooo I feel like they are part of my team haha
Plus they gave me offer if I think of a plugin and they think it's great, they will discuss and if they make it, I'll get the plugin for free.

Others have option tho to sponsor a plugins development meaning you don't pay as much for custom work but also means they can sell it as their plugin rather than you fully owning

**Comment by leandrotavaresrocha** [comment]
@poeticjustice, don't get me wrong but please stop spamming here with Social Engine Solutions Products. This is the third thread/ticket where you start spamming about SES products. We are just discuss here about SEAO only because they replied this ticket saying that they are planning this feature.

**Comment by poeticjustice** [comment]
Wow @leandrotavaresrocha thanks for the telling off.

I've helped people on here and actively been trying to make SE take note, and re raise tickets they simply closed.

Plus identified loads of bugs that are now being fixed.

Glad you think I'm a spammer

Have a great day

**Comment by poeticjustice** [comment]
Was only making aware of options but we are in a world where you try to help others or give them options, they just take it the wrong way.

Have a great day

**Comment by gsf00001** [comment]
@Elshara ==>"Could you, say, mention an entire group of users using a specific hash
tag, to tag it in? This could work if so."
Well, sortof.  The point is if a hashtag was created for each desired group, then these could easily be searched/located.  But this wouldn't necessarily email or notify each person in the group that there's a new notification/message.

@leandrotavaresrocha ==>"The point is that users use pages and groups to promote their website and this is a small pain. They share manually links in several pages and groups what in one hand flood the main feed and in other is a laborous work. "
I have not done this using a Share function (but that seems to be a useful place depending on the need as I mentioned earlier using 'custom lists' rather than 'friends' lists).  For my purposes, using SEAO's D/Pages, D/Businesses, Groups/Communities they provide the ability for page-'members' to have different roles/hubs for each (each can be a member of multiple roles/hubs).  The customization I asked for allows emailing each hub.  This provides quite a bit of flexibility with what may be included in the message (well, as flexible as the editor is).  It obviously isn't a 'share to this or that group and only to their member's feeds' but a variation of it may work for you.   

And no, I'm not spamming about SEAO - just like @poeticjustice I'm simply sharing a solution that worked for me to help others think of possibilities of what might work for them.  I appreciate others sharing how they solved a particular issue - sometimes it's exactly what I need, sometimes it helps take me down a path to a solution that I never considered.  Other times it's not helpful at all of course - but I'd rather have suggestions (there seem to be more here than on community.onsocialengine) for me to read and decide the usefulness.  I appreciate input here by other ADMINs :)

**Comment by Elshara** [comment]
No I don't consider it spam either, it's an alternative. It's
competition and in a world with so many possibilities, sometimes, you
have options, it isn't always a cut and dry choice.
I personally prefer Radcodes but I'm open to anyone. I'm just thinking
code from their link share bookmark plugin might be of some help here.
It sounds like something you might be able to use rather well.

**Comment by Elshara** [comment]
Well it shouldn't be that hard to theoretically create a check box
that notifies every member of the group if a new post gets created.
That way upon posting a message, you could check the box to send it to
who ever the post was meant to be shown to.
Such a method could be useful for other modules as well.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#35

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
