### ISSUE TITLE
Storage Quota option - ability to enter a value rather than a picklist option

### ISSUE THREAD

**Issue by gsf00001** [SocialEngine/phpv4-issues#556]
(feature request - not a bug/issue)
There are only a few options in a picklist for this and having the ability to enter a value (MB,GB,TB - doesn't matter I suppose as long as the field is 'large enough' (ex. if MB) and has a decimal (ex. TB).

**Comment by Elshara** [comment]
You mean for member levels or for site wide?
I didn't know social engine had a pick list for storage management.

**Comment by Khushboo016** [comment]
Hi @gsf00001, If you do not want to have only a few options to select from for the storage quota of a member level and want to have the ability to enter a value for storage quota, then it requires small code level changes. So, you can do needed code customization at your end in order to achieve this feature.

Thanks!

**Comment by Elshara** [comment]
I don't mean to be critical here, but this feature has existed in
forum boards since 2000. It also exists in Cpanel so I suppose that
coupled with MYSQL won't really have much effect. Still, it would be a
cool software addition to an otherwise hardware limitation problem on
servers with few resources available. Which is why I support its
implementation.

**Comment by gsf00001** [comment]
@Elshara 
-->You mean for member levels or for site wide?
A: For MLs.  The point is there are only 10 options available in the picklist which provides very little flexibility (eg. the highest setting before unlimited is 10GB; so, after 10GB it's unlimited which I definitely NEVER EVER want to allow any User to have).

@Khushboo016 
-->it requires small code level changes. So, you can do needed code customization at your end in order to achieve this feature.
A: Do you have the code or do I pay a 3rd-Party Dev to do this?  Also, will this change SE Core (which I NEVER want to do - thus, it should be provided out-of-the-box by SE.  If it's such a small code level change then SE should be able to offer this standard.

**Comment by Elshara** [comment]
You'd think. But their Younet Masters probably have other plans.

**Comment by Khushboo016** [comment]
Hi @gsf00001,

Regarding "A: Do you have the code or do I pay a 3rd-Party Dev to do this":
This is a good feature that Admin of the site can enter a value as per his requirement for storage quota for the member levels and not have to select one value from the few options provided currently. We've added this feature in our internal feature tracker for its implementation in future releases. 

But we are sorry as we cannot provide you the required code changes to implement this feature now.

Thanks & Regards!

**Comment by Elshara** [comment]
I also look forward to its implementation as well because the
potential to use this feature will not go unrewarded. Thank you.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#37

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
