### ISSUE TITLE
[Suggestion] Add hyperlinking button

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#559]
Under Admin panel - announcements

when posting announcements you have to currently go into "Source" and use <Href= blah blah> to incldue a link in announcements, when almost every platform on the planet has a simple button you can click to turn it into a hyperlink, I think SE should have this button as well.

**Comment by Elshara** [comment]
This is an issue with the text editor version. I think updating the TinyMCE would fix this. PHPFox used to have an area where you could set the order of what buttons you wanted to control using the plugin interface on each tool bar. I think hyper linking is available in more html5 advanced versions of TinyMce than the one social engine ships with presently. I only mentioned PHPFox here because the entire product team left it to work in social engine.

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie, @Elshara, We are going to update TinyMCE Editor in the upcoming release 4.9 of SE PHP so that the editor would then be consistent all over the website. So, this issue will not be faced afterward.

**Comment by Elshara** [comment]
Thank you!

**Comment by Elshara** [comment]
I do know that PHPFOX recently updated their TinyMCE editor to
CKEditor. I don't know if that changes much in terms of features. Or
if it is more flexible or less usable.

**Comment by gsf00001** [comment]
4.9 has an update to TinyMCE - woo-hoo!! :)   Thanks very much.

**Comment by Elshara** [comment]
I know right?

**Comment by DonnaScriptTechs** [comment]
This is included in 4.9.0 via tinymce.
