### ISSUE TITLE
Language Member Level Selection

### ISSUE THREAD

**Issue by leandrotavaresrocha** [SocialEngine/phpv4-issues#583]
Hello,

Social Engine needs a setting to allow admin choose what member level will have access to select what language and if the auto language selection will work. The reason is quite simple:

I run a portuguese community, but I need to maintain the english package because developers frequently visit to fix bugs. In consequence several users from english language register in my website, but found no content in their language. 

I need a setting to allow me disable the auto language discover setting the portuguese language as the default and another setting to disallow certain member level to choose certain languages.

**Comment by Khushboo016** [comment]
Hi @leandrotavaresrocha, Thanks for your suggestion, but this feature seems to be useful for very few people because choosing a Language for use on the site should be mainly depended on the user that which language out of the available languages he would like to choose as per his convenience. So, we are not considering this feature for its implementation in the core module and we suggest you implement this at your end by doing code customization. 

Thanks & Regards!

**Comment by Elshara** [comment]
Actually, it would work out quite well if instead of the member level was implemented, if someone wanted to change the display language for their site, they are able to do it regardless of whether or not they are a member or visitor.
Similar to how PHPFox and Facebook do so currently, through ajax cookie implementation.

**Comment by leandrotavaresrocha** [comment]
@Elshara in this point phpfox has an advantage, because it has an option to disable languages for user selection, in other words some languages can be set to be selected only by admins.

**Comment by poeticjustice** [comment]
@leandrotavaresrocha I went into the file that controls language select on signup, and deleted all other entries forcing english to be only selected.

I also have social engine solutions activity feed, which has a translate feature.... mainly for wall contents only

**Comment by poeticjustice** [comment]
@leandrotavaresrocha you could do the same leaving only portuguese  or even portuguese  and only english

**Comment by poeticjustice** [comment]
@leandrotavaresrocha ill try locate the file and let you know

**Comment by Elshara** [comment]
It won't work that way.
The language selection tool is for iso codes to be formatted properly,
that's all it does. It doesn't actually alter the display of the
website. You have to actually purchase a language pack to do so. Even
then you're restricted by or with only one site language.
It's stupid. PHPFox only has one advantage here in that at the bottom
of all pages, you're given the option to change language packages like
Facebook. But even then, you're restricted as you can't use two
languages simultaneously.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#57

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
