### ISSUE TITLE
Profile photos and albums still showing on the Album(1) tab of the profile with the privacy setting to ME ONLY

### ISSUE THREAD

**Issue by Mthorganby** [SocialEngine/phpv4-issues#607]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Create two new profiles 
a... No friends, in or not in the same network, this doesn't matter (think standard is everyone can see each other, if this is not the case make sure everyone can see each other in the network)

2. …Create a new album "Test" and up load one or more photos

3. …Set the privacy to:
a....un-tick the box [ Show this album in search results ]
b...Set privacy to [ just me ]
c...Set comment Privacy to [ just me ]
d...Set Tagging to [ just me ]

4.... Login from the other new account

5... Go to members

6... Click the member ( new account with album "Test" just created )

7... Click on the Album(1) tab

What happens?
-------------
When you click on the Albums(1) tab the Test Album is showing with the first photo.
The album and definitely the photo should NOT show as the album is set to Privacy [ Me ONLY, Friend Only, Friends of Friends, Friends and Networks  ]
Even the the box [ Show this album in search results ] is un-ticked.

If you click on the photo or album, you do get a privacy warning and the album/photo will not show full screen; You do not have permission to view this private page. - go back.

In this way there is NO privacy at all as the Album and first photo is still showing.

Note: Super Admins, Admins, Moderators must see this album and photos.

What were you expecting to happen?
----------------------------------
This album should not show up at all and definitely not a private photo must be shown.

Any logs, error output, etc?
----------------------------
No error logs for this

Any other comments?
-------------------
none

What versions of software are you using?
----------------------------------------
OS version: PHP Version	5.6.30
SocialEngine PHP Version: 4.8.13

**Comment by gsf00001** [comment]
I am very curious/interested to find out the cause of this as this issue is throughout a 3rd-Party Dev's Plugins (i.e. although many of their plugins include various privacy settings including View Privacy which does prevent displaying the 'detail' page of a content item with a Privacy Message, the problem is the content still appears in 'main' page like home/browse/etc.  So, anyone can still see the image/title/etc.   This is like preventing phones/addresses from being accessible in my address book, but still letting you see all the images and names of the people.

**Comment by Elshara** [comment]
Well I can confirm this in the core modules as well. Also, search is performed on all member level based contents when ever browse pages are accessed. The just me privacy setting should not work like this. It effectively hides even admins from being able to see content only one person uploaded. I know the functionality should automatically involve admins and moderators, but it doesn't. And the issue here is with the widget itself not conforming to search rules as it is a separate means of accessing user generated content from the database. It is a very disturbing bug however because there is no way to control who is able to view or see widget content with respect to member level or member type settings. Presently this may mean all other widgets for privacy content concerns behave the same way. I assume widgets will be updated in the next release of social engine. However considering the possibility I reported about this issue some time ago, and social engine had no plans to allow member level addressed widgets to exist then, I wonder if anything has changed on the developers road map now.

**Comment by Mthorganby** [comment]
I have tested this on a blank SE php and with SocialEngine core module installed. Result: the same.
This is a problem in the core version of SE. The only thing I have installed is SocialEngineAddons core and a theme and all the core modules of SE php are original. 

The only way around this problem is if a customer creates a new album and set all the settings and uploads an image with a text like "Private photos" and set this as the Album main photo and keep adding photos to the album and keep the first image "Private photos".

From a customer point of view; Customers will forget this temporary solution!! 
IF you set something private you would expect it not to show. If this becomes a legal challenge, the site owner can/will end up with a very high bill.

OR the software sets an main photo on the album "Private photos" if the setting is  [Me ONLY, Friend Only, Friends of Friends, Friends and Networks] which can not be moved/deleted or edited. So admin can still see the album and moderate the content if it gets reported. When you click on it the security works as Me ONLY will give an error/warning to any regular member; This is a private page, no access.

This is a problem for anyone who is using SE php and must be solved in the new release.

**Comment by poeticjustice** [comment]
I used Social Engine Solutions advanced albums as it never required the SE default albums to be installed, so i cant confirm this sorry, ill try later on one of my staging servers. 
i know SES albums doesnt have this issue, and SEAO albums can also used independantly, but i havent used that for ages

**Comment by Elshara** [comment]
Yeah. It's a bug. It'll be fixed. When, I don't know.

**Comment by DonnaScriptTechs** [comment]
I've added this for our team to check, noting that staff (superadmin, admin and moderators) need to see private albums but other members do not (other than the one who made the album).

**Comment by Elshara** [comment]
Awesome.

**Comment by gsf00001** [comment]
Although I agree with a permission msg on all pages the User has no access to (as well as obviously not displaying the data on page) I would prefer the item not appear at all in home-type pages or widgets rather than a 'private icon' since this can get ugly quick.  

This should be a simple security/permission thing - either logged-in User is allowed to see it or not (and staff should be allowed to see it all).  What's the point of having Privacy settings that only make some of the private content private.

BTW - earlier I mentioned a 3rd-Party dev has this issue throughout their Plugins and has assured me they will resolve within about 7 wks.

**Comment by Elshara** [comment]
Yeah. Photos are things people seem to care most about being private
as opposed to any other content type. The problem is all the module
widget index files can be accessed directly if you know the path
names. Then you have the problem of the public user permission not
really being customizable in the first place to reenforce what people
can see and what they cannot.

**Comment by Mthorganby** [comment]
I am trying to set up a dating website.
So as you can imagine my customers don't want their private parts flying all over :)

At the minute it will have to be a "private picture" as first image and untick the box "Show in search" and visible "Only me" or "Friends Only". After this they can upload what they want.
So it is only visible on the users profile and not clog up the search/browse of albums.
If they click the picture on the profile it already says "you don't have permission" so at the minute this is the only way of working until this gets fixed in the core apps of SE PHP 4.
This also for the mobile core version, same problem.

Like @Elshara is saying people don't mind text flying about, but private picture "only me / friends only" is a no go on a dating site.

**Comment by Elshara** [comment]
I agree. Especially concerning, I find, is profile pics. When you set
a new one or upload a new one, your old one remains visible under its
own album. Most users won't know to even look for things like pictures
they've uploaded, because they won't recognize setting albums for
them. And they won't think to see that their intimate photos, say for
dating sites, could be located under an innocent, profile photos
album. And then when they go to delete the picture, they may just find
they have to remove the entire album. Unless there's a way to remove
the picture individually. Or set one as a cover photo. But it seems
both options don't exist.  I could be mistaken.

**Comment by gsf00001** [comment]
==>"Like @Elshara is saying people don't mind text flying about, but private picture "only me / friends only" is a no go on a dating site."

Some people may not care about text flying about, but others might.  This is why Privacy settings should control all access to the selected content - not just images or whatever.  I don't use SE Events or Groups, but I'm wondering how the Privacy works for that content?  

Even if there's a setting to include/exclude from search and Browse/Home type pages, this isn't enough - this is actually a separate function and should remain.  Privacy is privacy.  For example, if Privacy works properly, then I may wish to include all of my content in Home/Browse pages and Search because it's helpful to me (and since no one else 'should' be seeing it - I'm all set).  So, as I mentioned to the 3rd-Party Dev that's correcting their Plugins for Privacy to work properly, the Include Home/Browse/Search should still exist and work along with the Privacy Settings.

My thoughts:
- Selecting Content Link to non-allowed content: Popup message could appear stating content is Private (or whatever).  This prevents wasted page-load just to display a message
- URLs: Private Message should appear on page and no private content should be displayed
- Home/Browse/Search: Based on combination of 'Include' and Privacy settings; this should control all associated content - not just part of it (i.e. don't display the title or album name or image or event name or event date, etc. etc.).   

Since I use so little of SE, I didn't realize this bug was part of SE.  The existence of this bug surprises me that out of tens of thousands of ADMINs/sites, no one noticed this until now.  Privacy/Security is quite a major part of any CMS I would think.

**Comment by Elshara** [comment]
I do know that event and group privacy controls the entire item.
Including the visibility and ability for members to access any posts
contained within it. There's currently no way to have posts public in
a private containment item. AS in, 2 photos public and 98 photos
private in the same photo album. Same goes for groups. You can't have
1 discussion public, another one private for groups and events. You
can't have modules contain independent privacy settings by item.

**Comment by Elshara** [comment]
Mind you that is the way it is supposed to work. If it doesn't due to
bugs, I'm none the wiser.

**Comment by gsf00001** [comment]
Okay - this is scary, very scary and troublesome.  I just added an Event (using SE Events) and checked the 'People can search for this Event' and set the Privacy (who may see this event) = Just Me.  Guess what ... the event is displayed to a non-logged-in-User when viewing 'Upcoming Events'. 

So, basically the Privacy setting is meaningless.  And I don't want to hear about 'yeh - but you checked the 'search' box' :)   because as I mentioned in an earlier post - that setting is a separate function and should work with the Privacy setting (not override it), where the Privacy Setting is the primary control.  

It seems this wasn't caught until 15 days ago in this ticket (well, for Photo Albums - but now I'm asking about Events and possibly other content which I haven't tested yet), so this bug has been occurring at least since 4.8.13 and no one using SE Photo Albums or Events (or possibly other modules) realized the Privacy settings don't work in SE out-of-the-box?  

Should I create a separate Github ticket/issue for Privacy Settings that don't work, or just leave this alone since @DonnaScriptTechs is already aware of this issue, or does another SE staff member have to reply (I ask this because I'm confused why Donna seems to be posting as ScriptTechs and not as an SE staff member - and yes I understand what ScriptTech is, but that looks like a separate entity here rather than an SE Corporate User)?

**Comment by Elshara** [comment]
That's just her git hub name. Like my username here is Elshara I can't
exactly edit that. Or can I? I know I can transform my name into an
organization via profile alteration.
Like I said. Privacy controls are shot. Content appears in search
anyways so the check box probably overrides privacy anyways. Like it
used to for pages before 4.11 decided to actually cut the feature out
entirely. Now you can't have pages searchable even if you wanted to.
As for upcoming events, widget privacy is another story entirely. They
have none. Menus and widgets do not have privacy controls, so you have
no option but to display all content even stuff marked only me.
Yeah I'd raise another issue about widget privacy entirely as well as
the issue about search check box. I've raised way too many issues
here.
See issue 630. That one was closed but yeah it was too many even for
social engine to process lol.

**Comment by DonnaScriptTechs** [comment]
@gsf00001 this is my Github name. Look at the other staff and none have SE names. I'll change my icon if it helps though. :)

I'll raise the privacy issue amongst staff for this report. I did raise the issue for albums but will broaden it.

**Comment by gsf00001** [comment]
@DonnaScriptTechs 
I just wanted to be sure 'who' you were when posting - I didn't want to bother you with SE stuff if you were posting personally or as your own company, and vice versa.  Thanks for raising this privacy issue and broadening it since it seems to be a serious issue, even though it looks like very few people notice or care about privacy here :)

**Comment by DonnaScriptTechs** [comment]
@gsf00001 Not a problem :) btw, you can always contact me about SE stuff at any time. 

I think people care about privacy. Many haven't checked, similar to you finding it. It's good that we have the report though. Feel free to report any issues found via separate reports.

Thanks everyone!

**Comment by Elshara** [comment]
You're welcome. I'm glad to help where I can.

**Comment by Mthorganby** [comment]
It goes even as far. If you have created and private album (all done and dusted) you add new photos to the album. Guess where the end up? In the activity feed for everyone to see
Feed Content: 
• All Members
• My Friends & Networks
• My Friends).

Uploading photos to a private group, photos get stored into the category "All categories" 
If you upload a photo in Events, it creates a photo album "Group photos" is you delete the album, you photo is still visible in the tab Albums

In "Activity Feed Settings" --->"Activity Feed Item Type Settings" (/admin/activity/settings/types/type/album_photo_new)
This part is also not included in the privacy settings.
• If an album is set to private it still post on the activity feed. (Incorrect)
• If an album is set to network and friends or everyone, show the photo in activity feed (this is correct)

I think the whole privacy thing and were&how photos are stored in SE php 4.x need a complete overhaul

**Comment by gsf00001** [comment]
@Mthorganby 
==>"• If an album is set to network and friends or everyone, show the photo in activity feed (this is correct)"

Do you mean that when set to network/friends, it only shows to that particular network/friends, or does it show to everyone?

**Comment by Elshara** [comment]
IT shows to everyone because activity feed is set to show all content.
Activity feed content doesn't show the ability to hide private content
even if the content itself is private.
If the activity feed were set to friends or networks only, the same
problem occurs because it overrides privacy controls.

**Comment by RaymondBenc** [comment]
We are going to be looking over this issue today. We should have more info shortly. 

Thanks for bringing this to our attention and for providing additional feedback.

**Comment by DonnaScriptTechs** [comment]
We appear to have a fix for the photo album issue. Private photo albums are now not seen anyplace by those not allowed to see them. Admin can see them. 

Editing the private album and adding photos to it does not show them in the feed for those not allowed to see them.

I'll have to test events tomorrow.

**Comment by Mthorganby** [comment]
@DonnaScriptTechs 
Thanks for the update, I will try a few more steps on the Albums tomorrow.

In the EVENTS & GROUPS modules:
A user can upload a photo, but the same user can not delete or edit its own photo. (Permission denied or you have no option to delete at all)
You should be able to delete your own content, may you upload a wrong photo

I can not find the photos uploaded by user to the Events and Groups, they seem to disappear from the system. I don't see any Groups albums or Event albums not in the user account nor in the back office. They seem to disappear into thin air.
I have created a brand new regular user, but can not find any places where photos are stored.

**Comment by Elshara** [comment]
Awesome!

**Comment by DonnaScriptTechs** [comment]
The issue for photo privacy is fixed for 4.9.1 once we release it. Should you find the issue again, please post a new bug report. We will look at other modules for future releases as well.

**Comment by Elshara** [comment]
:)

**Comment by Mthorganby** [comment]
@DonnaScriptTechs Thanks for the update. Will have the mobile version the same update?

**Comment by DonnaScriptTechs** [comment]
You're welcome @Mthorganby  . This is a privacy fix. The mobile version should work fine. Our demo is upgraded to 4.9.1 if anyone would like to check things at https://demo.socialengine.com . 

Thank you!

**Comment by Mthorganby** [comment]
Thanks, I will check this tomorrow, I see you have updated all the files as well. Will download them tomorrow and install them and let you know the result

**Comment by DonnaScriptTechs** [comment]
Ok thank you! Have a good night. :)

**Comment by Mthorganby** [comment]
no problem, it is just gone midnight here :)

**Comment by Mthorganby** [comment]
@DonnaScriptTechs  

Hi,

The photos/albums are working correctly. Even when you set the privacy, it will stop showing the post/photos/album and it also stops showing in the activity feed and all network dependent, brilliant !! 

.... BUT....

I tested all the other modules too.
All the other modules have the same BUG, Nothing is private!

Modules: Videos, Events, Blogs, Forum, Polls, Classified, Music

The Video module, If set to private it is still showing the captured image anywhere, when you click on it it will give a warning " You do not have permission to view the content". But it is still showing the content. This is the same as all other modules. If it is set to Just Me it should be private.

Can this also be changed ASAP please, like how the Photo Albums are working now?

If you change this you will have a brilliant core version !!

**Comment by DonnaScriptTechs** [comment]
We mentioned in the above comment that we only fixed this issue right now as we have to do each one separately with more testing. We didn't have enough time to do the others for this release but are working on them. :)

**Comment by Mthorganby** [comment]
Brilliant, Thanks!! 
Look forward to the updates :)

**Comment by gsf00001** [comment]
@Mthorganby If you have any 3rd-Party Plugins, you may want to contact them to be sure they are doing this as well.  SEAO is currently integrating this into their Plugins (since I use so little of SE out-of-the-box, I never realized this issue existed with SE content until I read this post - just days after a ticket into SEAO).

SEAO was great (they're a great Dev) and got on this immediately (thank goodness) and I'm glad that SE will now be rippling this through the rest of their modules.  Donna has been a magnificent blessing here in recent months :)

**Comment by Mthorganby** [comment]
@gsf00001 
I do have 3rd party software, but I do not use all their modules, just a theme, community ads, advanced members and activity feed from SEAO. The rest of the module are the core versions of SE. I have no need to upgrade other modules. With a few changes in the CSS the ore modules look great within the SEAO themes.

**Comment by Elshara** [comment]
I'll let radcodes know since I bought some stuff from them. To be
honest, third party developers who sell plugins should all keep their
products up to date, and yet I understand it to be only the case with
some, not all developers.
Good to know though, and social engine add ons does sell the most
stuff out of everyone so yeah. Happy. And I also support the update
for all other core modules as well, including status updates and
comments.

**Comment by Mthorganby** [comment]
@DonnaScriptTechs 

 I am still testing, new release.

Shall I open a new issue for all the bugs I have found after a brand new install SE PHP 4.90 with patch Albums 4.90p1 installed or do you want me to create for each an issue ?
I have found a few :)

**Comment by Elshara** [comment]
I'd say open a new one for each.
