### ISSUE TITLE
Competitors Could Use Some Competition

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#611]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Specific competitors have a pretty significant lead in terms of getting people to sign up to their service (s) based on features and functionality lists alone. Without third party products to enhance augment the service (s) provided.
2. … Natural offering (s) such service (s) provide, appear to enhance the abilities of the product (s) offered in tandem with social engine. By comparison, features provided by such competing platform (s) may tend to have certain advantage (s), where social engine lacks in pure functionality.
3. … Due to such functionality applied during the initial installation of different software people buy into other than social engine, social engine may need to seek a reason to invest in the consideration of further updates to its core product.

What happens?
-------------
… Here are the pages I have found where direct competitors are offering effected products. https://www.phpfox.com/#features https://www.boonex.com/features https://www.jamroom.net/products https://tiki.org/Features http://www.onesite.com/social-software#features https://www.hoop.la/features.php https://elgg.org/plugins https://www.socibd.com/features https://www.oxwall.com/complete-feature-list https://www.socialgo.com/compare http://grou.ps/home/features http://spruz.com/?page=info https://codecanyon.net/item/sngine-the-ultimate-social-network-platform/13526001 https://phpdolphin.com/features https://www.opensource-socialnetwork.org/ https://www.ning.com/ http://www.vbulletin.com/ https://invisionpower.com/ https://vanillaforums.com/en/features/

What were you expecting to happen?
----------------------------------
… To review each platform in turn to decide if any core improvements should be made based on what other people are able to use if they went to such provider (s) and demo tried or purchased such functionality from the core product.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… This is not an indefinite list, however unlike platforms such as Joomla, Drupal, Wordpress and other such third party related mash up content mix and match places, the platforms I list here come with the advertised features by default. If social engine did so, by incorporating some of the listed features from any of the platform (s) mentioned here or by through similar design, by creating other modules or module enhancements for social engine specifically, there would exist better competition and social engine would only get better.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by poeticjustice** [comment]
This is a really great post and totally agree.

**Comment by Elshara** [comment]
Wow thank you. :) I feel it is time social engine step up the code
changes required to make online websites better successful. I felt
giving a taste of what already is possible and successful now, would
help drive such a mission along to a serious aim.

**Comment by gsf00001** [comment]
Good post - there are always areas where an app like SE may improve, and often they are not thought up until seen to exist elsewhere (i.e. what do they do that we don't and how and why, and should we do it too).

Sometimes though, it's not just the bulleted lists of items that need to compared (i.e. Product1 has feature A-E, product 2 has B-F) , but actually how the particular feature functions.  This can be seen in something as simple as various ADMIN discussions on Activity Feeds (i.e. any comment or like brings the item back to the top vs. keep activity feed in order based on newness of primary post not details within the post).  There may be many common features we all could use, and often times even the 'how the feature works' may be common, but there are obviously times different strokes for different folks applies.

My concern with including too much ('too much' is a subjective term of course) into the core of any platform is the cost shared to all purchasers.  It's like a car - not all of us need the same features/functionality, so most vehicles charge for additional features, packages, and/or levels of the same vehicle rather than incorporating 'everything' or 'too much' into only 1 model.  For me, this is where Plugins come in.  If I need something you don't, it costs me $$ not you.  

Back in 2013-4 when I began my search, I realized though that (at that time) no platform out-of-the-box would provide much of what I needed (primary functionality, or sub-functionality, etc.).  I created a spreadsheet (over 1000 rows and hundreds of columns) to compare core and Plugins functionality (and some sub-functionality) based on spec pages, reviews, discussions w/Devs, and demos.  Was it perfect/complete - of course not, but it did provide what I needed to allow the 'cream to rise to the top' which for my purposes was SE (in fact, another script seemed to be right which I purchased, but before installing I realized my mistake and switched to SE).  In my case, it was the 3rd-Party Plugins that directed me to my decision to purchase SE because only the 3rd-Party Plugins for SE gave me most of what I needed (which then still required several hundred hours of customization to make it unigue to the my niche/purpose).   In fact, I think I'm only using Core and Albums (and Albums only because a Plugin rides on top) - all other SE Modules I purchased are disabled and have been replaced by Plugins.  All of that to say that for some - they want the whole care to be as complete as possible.  For others, they just want a chassis & engine, and they'll add what they require to address their specific needs.

For any product, it's often difficult to develop the right balance/mix to address the largest group of Users.

Thanks for the post and quite possibly 'opening the eyes' of SE in case they haven't already been doing their own research/comparisons.

**Comment by Elshara** [comment]
I understand what you're saying.
My own thoughts on the matter are simply to get SE to recognize for
the price they are charging, other products offer all this for at
least the most expensive one being, $200.00 cheaper than SE. The
product back end of SE isn't the best, and I find many of the products
I've listed, have a simpler structure to manage content posted to
them. SE just groups items in an in your face type of way, but
everything SE does is plugin based. Where as products, which are
similar, tend to offer a better layout option with more features all
around.
The hardest part for me is for social engine to recognize you can't do
something, and for them to also see a third party can't do something,
for them to turn around to tell you nobody can do it. When I can think
of, and have used products in this time, day and age, for many years,
which has had such functionality and their core isn't half as good as
social engine. The issue is not, whether or not SE can support the
core change, but rather, whether or not if it will consider
implementing it at all. Which has been usually based on simple bug
fixes and tweaks to the filtering of data already in existence in the
database, the majority of such being conceived as an idea and then
implemented for about 5 or more years longer than SE was born. So the
ideas are nothing new. Forum boards and early blog sites back in the
day, made such things possible. Their code is so old now days, people
don't know what to do with such platforms, so people turn to platforms
under active development, to move on from the out dated code other
platforms have created in the early days of the public internet. This
leads me to believe using modern coding practices and standards, we
can achieve so much more, by implementing modern techniques with
modern back end and front end code. To do so, we have to look at
simplifying how data can be accessed using as few queries as possible
from its storage space, to display itself to users in a fast, easy to
use way, which can be customized as per the needs of the administrator
or company owner. Access is easy to implement, once such basic
principles has been established. The idea is to not over reach the
server resources, but by having fewer requests to deal with per query,
this wouldn't be a problem. One such way would be to limit how many
programs is needed to run a server anyways. Having a place to store
files is essential, but beyond the way they are accessed, it should
only require one type of program to access everything. If browsers had
php and html functionality built in, you would be able to utilize
server resources in a whole new way. And space now days, is very easy
to come by, as it is not difficult to buy a two TB hard drive for
about $100. Other options are also available and they will become
inexpensive as time goes on. At most you will spend about $2000 for a
storage option which could suit a very large website without problems.
Resources are practically limitless now days if you use cloud options,
so considering modern day advances in technology from the ground up,
will definitely not disappoint you. Server rentals must become
cheaper. And so must social engine in terms of its requirements just
to run it in its most power hungry mode, where resource utilization is
not devoted to ensure the program requirements are kept up to date,
but to rather ensure all the programs required to access the files and
connect them to the storage space where the information is stored from
one computer to another, remains efficient and is up to performance
standards.
Something we could work on together if we analyze how different
programs access data today. Perhaps it may be time to let php go in
favor of ruby on rails.

**Comment by poeticjustice** [comment]
@Elshara i really dislike that you posted this, because its infuriating how social engine are so far behind, but has the ultimate potential of being the best.
And as a supporter of SE its annoying to see this!

**Comment by Elshara** [comment]
I thought you liked this post. Sorry to disappoint. I'm only pointing
out the facts here.

**Comment by poeticjustice** [comment]
@Elshara i think you misunderstand what i meant.

What im saying above is, 
What you have posted, is a really good post, Its so good, but by posting this you have higlighted so much, and as Social Engine have seemed to not adapt or ignore certain things. 
When knowing the potential of SE, its annoying to see, even some competitors have better functions, even if them competitors are not as good.

Im saying the word dislike in a comical way, because you have raised a great post, but it makes me angry to see that social engine hasnt been adapting to change

**Comment by Elshara** [comment]
Well if you think that is bad. I just posted issue 612 which
highlights exactly this problem. And there's so many ways to prove
this new issue, it makes this one kind of worth holding off for. I
hate to say it, but the more I think about it, the more I am finding
social engine may be a deal breaker for me in its current state.
Yes I am happy for future versions and such. But right now, the past,
has to change and big time. I mean how much does it take to connect a
php file with an html file to a database? That's the questions I want
to have answered, because it seems social engine can't fix that basic
need, to be able to make new features and have them be stable as such.
I apologize for my misunderstanding buddy. You are quickly becoming my
new best friend on here. I've had a bit of an attitude adjustment. Not
because of anything you've necessarily said, but because Especially
given what I've just discovered 30 minutes ago, kind of making an
impact on my sentiments for different reasons, agreeing to the same
ideal more or less. I have to ask, did you see any competitor you like
or one whom you've particularly found interesting? I know there are
hacks for the well known platforms possible, joomla, drupal, wordpress
and such. But I mean I figured this post might gain some traction
because of what people could have from scratch if they applied a bit
of effort, making the web seem much better and friendly in my opinion
than such a limited focus view of seemingly silly issues in retrospect
to social engine's development during the past few years I've been
here.

**Comment by Elshara** [comment]
I've found a recent data export company willing to migrate import
social engine data to a new and free solution.
https://una.io/
As well as some other companies you might like to check out.
http://www.webs.com/
http://www.wix.com/
https://groups.io/
https://www.softaculous.com/
https://groups.google.com/forum/#!overview
https://ca.groups.yahoo.com/neo
https://appear.in/
https://tinychat.com/
https://www.cometchat.com/
https://www.arrowchat.com/
https://rocket.chat/
There are so many systems out there which is capable of doing this and
so much else is available using different key words on Google and
other search engines. I figured you may have come across several like
it with features you would appreciate, ported to your favorite content
management system, or data manager. I figured this may help further
such an aim.

**Comment by DonnaScriptTechs** [comment]
Thank you for your post. This sort of post would be best discussed in a community forum post and then one feature at a time submitted in an issue. Our developers are also adding features and looking at what to add for future improvements. We do know of our competition (especially phpFox since both Ray and I worked there before). 

We will need to close this as it is far to huge for our core developers to look at. What they need is one feature at a time submitted. Bearing in mind that we also have ideas and things we want to implement that none of our competition has (and for obvious reasons, we can't discuss yet or they will get them too lol).

We encourage you to continue discourse about this at the proper areas. Note that our company is very aware of competition though. :)  We do have to weigh the features vs the cost of implementation (not just production cost but weight to clients). 

I'll close this now as it's not following our guidelines for posting and will slow our team considerably in checking.

**Comment by poeticjustice** [comment]
This is a great post even tho closed to bounce ideas, like donna said, we can post individual requests.

I think the way forward is to make images comparing SE to other platforms, do it in photoshop comparing upto 3 comparisions.

The visual images will create a greater understanding to visually see.

PHPFOX has some nice touches, as do others, but i still believe SE is better, the devs seem better, producing great plugins, the other social network software has flimsy developers.

And i hate open source things that are free, thats why id rather pay for SE and pay developers

**Comment by Elshara** [comment]
Daniel got a community I could talk to you about such ideas you are
at? I'd be interested.

**Comment by Elshara** [comment]
I am sorry the issue was too broad. I'd like to point out though there
are more sites than just phpfox within the scope of competition. I
guess the point of this post was to let people know what those kind of
were at a glance.

**Comment by DonnaScriptTechs** [comment]
Yes there are a lot of competitors, which I acknowledged. I've used many of them. :) We want to focus on our product and do like feature requests that we can consider. Please feel free to post one at a time for us to look at and check the feasibility of adding them.

Thanks again!

**Comment by Elshara** [comment]
Anyone is welcome to join a google group I set up for this purpose,
for further discussion here.
The group called Comline allows posting both by email and on the web,
and you can optionally receive notifications for new posts as you
wish.
https://groups.google.com/forum/#!forum/comline
Join from your email address. Send an email to.
comline+subscribe@googlegroups.com
To post by email, the body of your email will be the main post and the
subject its title view able from the web as well as by optional
subscription via email to new contents posted either by email address
or on the web.
Once you are subscribed, to post a topic or question, send an email to.
comline@googlegroups.com
Comline is the name of the group I chose. I thought it fitting.
If you don't like it, you can remove yourself by sending an email to.
comline+unsubscribe@googlegroups.com
The subscribe and unsubscribe emails can have any or blank content.
The content you share in those emails does not get posted to the
group. But the email address must be the one specified to perform
either action. Note you must be unsubscribed to subscribe, and
subscribed to be unsubscribed.
You don't need a Google or Gmail account to participate to post. But
it is nice to have, as they let you create your own group. It's also
free to use.
Hope it helps. I figured it would be a bit easier to stay in touch.
