### ISSUE TITLE
Feature Request - No User image, as random colour block with users Initials

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#614]
Ive seen this feature on many sites like Oxwall, PHPfox, Google, Youtube, and loads more websites, instead of horrid default image, it produces a no photo colour block and overlays the users initials, which makes it look nice and random, rather than loads of default grey images 

![colour](https://cloud.githubusercontent.com/assets/19233272/24106353/81289992-0d7f-11e7-90c2-a494310cd041.jpg)

**Comment by Elshara** [comment]
What would be ideal is if there was a specific directory you could do that with. Just upload random images and gifs to it, and then it could just display one from any posted there for a profile photo.

**Comment by DonnaScriptTechs** [comment]
This was something I didn't like about the script you mentioned. Many didn't like it. It took away the ability to add our own default profile image for those that don't load an image. IMO, for my own sites I prefer to have my own default image as opposed to any standardly set one. That's my personal view of this request. I would prefer it to be a selection in admin to select our own default image.

**Comment by poeticjustice** [comment]
Yea Random images are cool too, similar to Github when users signup.

I just think the colour blocks with initials look nicer, especially when user dont upload a image, nice to see random things that are different rather than a wave of default images, maybe a setting to allow either.
Default image or Random Color Block with initials or as @Elshara suggested A random image choose for a image directory

**Comment by Elshara** [comment]
Thing is random images aren't something I particularly care for. Just
because you have to have control over how random they get. And you
don't want it to be anything located off site, but also, not to appear
as something someone already posted.
I think a slide show or an animated picture of images you set as site
default, though, that you could turn on or off, would suffice for
people interested. Then you just upload the desired image, or images
you want and then specify how you want it or them displayed.
Horizontal, vertical, tiled, with repeat or scrolling, or animated.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#64

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
