### ISSUE TITLE
Feature request - Facebook Pixel complete registration event on signup page

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#617]
Hi SE

I think this would be a great feature, I know there is a section to add scripts to the head of SE.

So pasting the code for Facebook pixel can be done there, 
Now im unsure how to, or if even possible to have but there is an additional script for tracking registration complete on submit buttons.

But SE singup page in layout editor that has the content placed, is only one page, that has sections, ie email, then profile Q, then photo and submit.

Is there a way to add in settings facebook pixel event section, that can be specifically linked to the registration being complete?

**Comment by Elshara** [comment]
I think in order to do so, what would need to happen is have the ability to create all profile data on one page. Including photo. Profile questions. And account fields for email, password and so on.

**Comment by poeticjustice** [comment]
Yea, Or SE add each stage of the signup to layout editor

**Comment by Elshara** [comment]
Yeah. Have a page for it in layout editor. Have the layout editor page
column based so anything that appears in one column, appears on one
page but the page uses full width like boonex dolphin pro does.

**Comment by poeticjustice** [comment]
Hopefully SE get round to seeing this and mark as enhancement, As FB is really taking over, SEO is dying now, FB tracking and targeting is way better on FB than google nowdays.

FB will soon take over google, till FB has the full functions of every website,

**Comment by DonnaScriptTechs** [comment]
I'm not a good one to ask about this as I disable social logins on my sites. I don't like how fb spies on everything, even when people are logged off. I'm not sure how many clients want this sort of intrusiveness from fb. It would be good if other clients would also provide their feedback.

**Comment by Elshara** [comment]
Want to bet?
Facebook doesn't have.
1. Music.
2. Polls.
3. Marketplace.
4. Personal ads.
5. In house coding experts.
6. The best data tracking system. Due to no public availability of it.
7. Adult content support.
8. Custom terms of service, rules and regulations.
9. Me as an active member.
10. Any educational value.
All Facebook has going for it is.
1. Games.
2. Corporate advertisements.
3. Bosses spying on your activity so as to censor you from having a social life.
4. The world's biggest outsourced ownership in any online company.5.
Money we'll never see due to private investors.
6. Celebrations we can never attend as we don't work for the company.
7. Friends, family and drama.
8. Lots of regulations and rules you must abide by or your account
gets locked and you have to share sensitive personal information with
Facebook support to get your account even reviewed for being
reinstated.
9. A glorified and confusing mobile interface as opposed to the
desktop cluttered one.
10. A spot in the list of fortune 500 companies.
Just because Facebook looks like a social network, it doesn't mean its
community base is anything but users for the most part. We're better,
because we have a brand to own.

**Comment by poeticjustice** [comment]
Ohhhhh @DonnaScriptTechs 

Facebook pixel isnt to do with social logins, that too i have disabled.

Facebook Pixel is to get conversions for Facebook ads you place on FB, so you can see who looked at the ad or signed up, and target people on facebook specifically.

Great for ecommerce, but there is a conversion pixel purely for signups, once someone completes a signup form, you connect it to the button for conversion

**Comment by DonnaScriptTechs** [comment]
Yes I know. I mean that as an example. There are many that don't allow anything fb on their sites. I guess this would be something good for a third party expert until we see if other clients want this and if it would be beneficial as an optional setting. It's definitely not something I would use on my own sites.

**Comment by Elshara** [comment]
Same here. It's not for me. Neither is vig link come to think of it.

**Comment by gsf00001** [comment]
Although I see the benefit to ADMINs, I personally have no use for it.  

My general thinking though is that many (most?) 'features' should be enable-able/disable-able.  Yes, there are downsides to the extra logic/step (such as adding to the decrease in site performance and adding more bloat to apps), but there are simply too many 'features' that are 'great' but even if not wanted they bloat code and slow things down.

**Comment by Elshara** [comment]
This is why we have member level settings and global settings.
Categories and appearance settings. We do need to streamline some
things, but feature filters shouldn't need to be one of them.
To be quite honest with you, custom data fields is all we are really
building here. Despite layout changes, or updates.

**Comment by gsf00001** [comment]
I used the generic term 'features' since what one person thinks is core functionality another may think of as a feature and another as a bug :)   I wasn't speaking of feature 'filters' per se but settings (in this post most likely a Global setting rather than ML).  But there is typically some type of logic in code (if...then, case, etc) to allow/disallow something based on a data field/setting somewhere.  

For numerous reasons, much custom code is often created to include/exclude certain 'features' rather than allow on/off options.  What I was getting at is my belief that generic scripts (such as SE) should seldom (never?) assume/presume that every 'feature' is useful or needed or wanted and that generic scripts should thus have the ability to turn on/off most 'features' (some globally, some by ML, some by various other criteria).  

There are many 'features' on github (or community.onsocialengine) that I find useful, others not at all.  I'm sure it's this way for most ADMINs.  I have to accept that a generic script will be slower due to the flexibility of more options than in custom code.  But the upside is that I'm not spending a gazillion$$ and hiring a team of coders to create and constantly update the custom code (that's SE's job in this case).  If my site ever acquires enough Users then my desire is to custom code everything - but that's not on the horizon at this point.

Sooooo... all I'm getting at is that rather than SE building in this (or any other suggested) 'feature', it should be option through a setting somewhere.

**Comment by Elshara** [comment]
I agree with the idea.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#66

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
