### ISSUE TITLE
Autoplay Music Playlist On Page Load

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#639]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … View a playlist through the profile player widget, the home playlist widget or through the music browse page.
2. … There is no option to auto play.
3. … Songs don't have individual URL's to comment on them individually.

What happens?
-------------
… Players usually activate on page load by default. Regardless of it being a slide show, video, song or photo compilation.

What were you expecting to happen?
----------------------------------
… Such to be possible.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Everything else apart from songs not having their own individual URL to comment on individually works quite well.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by Khushboo016** [comment]
Hi @Elshara, Autoplay of music on accessing the page can be made possible on the Member Profile Page because there is only a single music playlist on this page. But not possible in case of Music Browse Page because there are several music playlists listed on this page. So, I've added the suggestion for autoplay of music on Member Profile pages for internal team discussion.

Regarding "Songs don't have individual URL's to comment on them i":
We are sorry, but we do not any plans for implementation of this feature in our core module and we suggest that if you need advanced features for music module on your site, so please refer to the third party Advanced Music based plugins for this requirement.

Thanks & Regards!

**Comment by gsf00001** [comment]
==>"So, I've added the suggestion for autoplay of music on Member Profile pages for internal team discussion."
- Autoplay Optional via ADMIN setting please :)

**Comment by Elshara** [comment]
To be able to comment on an individual song is a must have for music
communities. I'm sure providing a link to the item, similar to how
photo albums are treated, can be arranged It's not that difficult.
Thanks for having auto play as a suggestion. The whole, can't view a
single song on one page idea, frustrates me though. Third party
plugins, just charge way too much money to not have this feature. They
don't play nice with existing content either.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#78

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
