### ISSUE TITLE
Create Privacy Controls For Widgets

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#647]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Add a widget to a page.
2. … Click on edit.
3. … Notice there are no privacy controls or the ability to customize the display of meta information, post title and description and post count of likes, views and comments.

What happens?
-------------
… Widgets display all items from the database without checking to see if private content is relative to the person viewing the widget itself.

What were you expecting to happen?
----------------------------------
… Privacy to be respected regarding all widgets.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… This causes concern for people.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
Do you mean there should be checkboxes to select the member levels allowed to see each widget? Another script has this feature and it's handy to disallow viewing. However, with hundreds of widgets on a site, it can be time consuming to have to set those permissions for specific modules. 

Perhaps a setting in each module for member level settings "can see widgets." Then, a way for custom widgets to allow controls (third party widgets that are small widgets, html block widget, banners, etc). Noting that this would add weight.

Is that what you had in mind?

**Comment by gsf00001** [comment]
@Elshara Or are you referring to general/overall Privacy as per #607 

But I actually find useful what Donna mentioned - widgets by ML.  To me this isn't necessarily a Privacy thing, but rather the ability to display different widgets based on ML.  I have wished for this in many instances - so a page may display different info based on ML - somewhat customized content.

**Comment by Elshara** [comment]
I was referring to direct widget control for privacy when clicking on
the edit button of the specific widget in layout editor.
This privacy functionality partially exists now, but it is very faulty
as privacy leaks occur where ever the widget is placed.
This makes the page itself responsible for having lots of extra over
head when trying to locate privacy settings. This is usually how
things work.
You load a page. The page loads all dependencies and then checks to
see what content to display.
But before it can do so, the content checks with the page to see who
is accessing it.
The page then has to go to member levels to determine what member
level is viewing it.
It sends the information back to the module if the page itself records
the member level as having either the permission to view the content
or not.
Having widget based privacy allows the page itself to have private
content, but allows the page to optionally be public, which would
eliminate the need to have a separate page just for private content.
But it is of course, optional.
So what I'm saying is, having both pages and widgets allow the freedom
of custom privacy per widget or page, gives you the freedom to block
access to certain widgets to certain people.
The appeal is despite many widgets being possible throughout the site,
privacy levels would usually have all content visible. If you wanted
to change this, there's no enforcement from the module side of things,
to enforce privacy remains what it is. AS it only effects the content
through the content module, and not any widgets like recent or popular
or profile content items, which also access such data.

**Comment by gsf00001** [comment]
@Elshara By page and widget 'privacy' are you referring to:
A) based on actual Privacy Settings of the content and logged-in-User?
B) based on ML of the logged-in-User?
C) Both?

I'm asking because I see both being useful - and actually quite separate items.

**Comment by Elshara** [comment]
Well lets go with both.
I was going to point out, they go hand in hand. Member levels should
regardless of what they are allowed to do, still have privacy controls
contained within them to let users customize who can see what they are
allowed to post within such limits.

**Comment by gsf00001** [comment]
So by hand in hand, I'm thinking the Widget would display based on it's ML, but then content would display based on the Privacy Settings of the content.  This:

Logged-in-User IS one of the allowed MLs
- Specific content that their Privacy is valid for IS displayed, other content is not

Logged-in-User is NOT one of the allowed MLs
- Widget is NOT displayed (regardless of whether or not the logged-in-User's Privacy is valid for the content that could display in the widget)

Are we thinking the same on this?

**Comment by Khushboo016** [comment]
Hi @Elshara, Creating privacy controls specifically and separately for all the widgets available in the Layout Editor is good, but at the same time, it would increase the complexity of the page. Because each page already has privacy settings for members of which member levels can access/view the page and also the content of the pages are changed according to the member level of the member. So, in case, all the widgets on a page will also have different privacy settings for different member levels, then this would need a lot of checks to go through before the page would be loaded and hence, it would result in poor page load time. Hope you understand my point here.

Thanks & Regards!

**Comment by gsf00001** [comment]
@Khushboo016 ==>" it would result in poor page load time. Hope you understand my point here."

I hope you don't mind me hopping in again on this, if so, just say so :)  With regards to the above point, extra time to load is expected (just like so many other controls/features/whatever on any page - it increases load time).  But shouldn't we ADMINs get to decide our poison?

Yes, Page settings are helpful for something, but not for others.  Here's an example:
- Let's say I have 10MLs, and want to display 1 different widget (due to settings or whatever) to each of these 10 MLs.  How can this be done currently - creating 10 separate Browse pages (1 for each ML)?  If so, how do I get the Menu Item to call the 'right' Browse page?  And I won't even begin to get into the complexity/hassle of managing many multiple pages for many Menu Items (along with figuring out which original pages have been 'fixed' in order to duplicate to recreate all over again, retest, etc.).  

Maybe as a compromize (performance-wise) would including an option for 'honour widget ML/Privacy Settings' on the Page Settings help?  This would also be great to allow us to turn on/off for debugging or whatever reason.  

So I'm not sure if 'undersand my point here' means this suggestion is out or if you're just reminding us that 'thinking/logic processes' on pages increase load times.

**Comment by Elshara** [comment]
The way I see it, here's a primary example of problems fixed using
this solution.
1. You create a private page, maybe call it, something only payed
members are allowed to see.
2. The only way for the page to remain public, but only have paid
members access it, is if widgets themselves using member levels for
privacy, are placed there.
3. Page privacy just applies to the page itself. It doesn't apply to
the content visible on it. There's no black and white, it's either on
it or it isn't. It's just not visible because the member level cannot
interact with it.
4. Imagine, if this page was the member home page. Perhaps you had a
module you wanted to show statistics to, for the particular member.
Say for instance, as they are a payed member, their posts get to reach
more people. Being able to view the statistics module, requires them
to be of the specified member level, so they can know, who has seen
their posts they paid to get promoted if the module had functionality
to accomplish it.
5. You wouldn't want to just not allow any other member level to
access the site home page. As it would deter them from coming back to
the site.
6. To avoid page overhead, an option for every page could be added to
allow modules set on that page, be it a core or custom page, to have
custom privacy levels. If so, that value would control the request of
where the member level matching would take place. Otherwise, it would
just be purely based on the information the page sends to the browser
from the server. Should the page have custom privacy settings which
are widget based, and the core functionality allowed that specific
page to have widget custom privacy levels, along with other values
like custom titles, custom description or whatever, then deeper
integration with the widgets of the page could be possible. You would
already have the settings loaded, so when the widget loads, it just
recognizes who is trying to access the content it fetches, saving time
on performance, instead of trying to search for it. Now, the page
itself controls what is possible for it to support. For instance, if
it has multiple columns, allowing the page settings to support this,
would just make query overhead less, not more time consuming. If the
page settings were to specify control be handed over to widgets
themselves, then you have extra overhead. Should the widgets be loaded
at just one query, then the page already has existing data to be able
to work with as a controller, rather than a model or viewer. IF it
could load existing language strings or data fields as a dependency or
an expected change, rather than not knowing if one is there, would
actually speed up performance, not slow it down.

**Comment by gsf00001** [comment]
This FReq is probably in my top 5 and most likely can only be done by SE since it seems to be so embedded into Core.  Oh I wish I wish I wish .... 

So much could be done with this - especially from a monetization standpoint.  Now I'm not so happy w/u Elshara :)  teasing with such a great idea that may never get developed.

**Comment by Elshara** [comment]
Thanks for the complement! I agree.

**Comment by DonnaScriptTechs** [comment]
There is a third party plugin for this, https://www.socialengine.com/marketplace/app/advanced-core and it is free. As there is a free product, we'll close this for now.

**Comment by gsf00001** [comment]
Donna - is this closed or still considered an Enhancement (due to both tags around the same time)?

Thanks for the info Donna.  Looks like a new Dev (just checked out the MarketPlace and they have this 1 Plugin listed, even though their website shows 3 Plugins).  I'll contact them since my concerns are: A) how new are they with SE; B) 'Free' always worries me; C) Does it require another Core.

I watched a video and it seems that if it does what it says, and is safe (i.e. doesn't interfere or negatively impact the rest of the site in any way), this is definitely a valuable Plugin.

**Comment by DonnaScriptTechs** [comment]
Regarding free stuff - nothing wrong with free products. All of the plugins I make in the store are free too. I don't know the developer of that plugin though. 

This is closed as I mentioned. I have been labeling each issue for better sorting. Things marked enhancement just mean that they are improvement requests and not bugs. It doesn't mean we are implementing them. 

Hope that helps.
