### ISSUE TITLE
Disable View More Feature

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#65]
In social engine, some features such as the activity feed and comments have a view more feature assigned. I believe this is bad for seo and users don't appreciate having to view more not realizing they need to in order to see the full post.

**Comment by smazurov** [comment]
SEO is fine because we still display the content in the html. You can also use css to control which one shows up. For variety of reasons, we'll be keeping default functionality. 

![screen shot 2015-06-23 at 11 34 51 am](https://cloud.githubusercontent.com/assets/21636/8312763/ea83370a-199b-11e5-8eff-7e376de40ac7.png)

**Comment by Elshara** [comment]
I'm sure there's ways to work around a lot of things. I'm not that
familiar with coding, I thought a simple means of allowing the script
to be customized to where people can select where the view more can
appear if desired, might be a compromise.
