### ISSUE TITLE
Chat bubbles in notification?

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#660]
4.9

![image](https://cloud.githubusercontent.com/assets/9712738/25009258/f2a69f76-201a-11e7-98ec-4bec4fb01350.png)

**Comment by poeticjustice** [comment]
That doesnt look good :S

**Comment by DonnaScriptTechs** [comment]
I had this when I upgraded mine. I had to fully clear browser cache, clear server cache and if that didn't work, click to Save the theme again. Is that the Insignia theme?

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

Donna, I'm really confused how you can't tell the theme you guys where promoting so heavily, and even used... Yes this is the Insignia theme, Yes I've done those steps before I wrote the ticket.

Can you please have someone get to my ticket and fix some of this stuff >.< specifically the inability to update activity's to 4.9 is causing allot of my users unable to upload photos right now.

**Comment by DonnaScriptTechs** [comment]
@SpiritWolfie It is much harder to tell with the vertical menu as there is a third party developer with the same sort of look. I was just asking if this was ours or a third party. Thanks.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs wasn't aware there was third party dev who did that, I only own the theme from SEAO and they don't do that...

**Comment by Elshara** [comment]
Possible rendering issue of CSS integration with an ajax update where
the notifications appear.

**Comment by SpiritWolfie** [comment]
Any ideas how to fix this or can support you know help me >.< I'm having all sorts of weird issues since upgrading.

**Comment by Elshara** [comment]
Try downgrading.

**Comment by DonnaScriptTechs** [comment]
I'm not able to reproduce this on a live demo site hosting with cazaratech on vps hosting. It's a pretty clean install other than the add ons I make (only 3 on it).

**Comment by Elshara** [comment]
I think I'm starting to see a pattern here.
I do regard you as being an honest person. Don't get me wrong. But
there's got to be an explanation for saying something like this. That
makes sense to anyone looking in from the outside. Or to anyone
looking out from the inside. That's what perfectly describes our
relationship, as a business.
Either a server extension isn't fully seated in social engine. Or
someone isn't telling everything.
I don't have 4.9 to test the theory so I can't and won't comment if I
can personally duplicate what Spirit Wolfie is talking about. But at a
wild guess, I'd reckon it's possibly one of two scenarios. There's
either a configuration of server specs not done properly. Or the issue
never really happened. What's also possible is when notifications
appear, to some browsers, they may appear differently.
I will say some aspects of responsive css may appear bothered if fixed
widths are being stretched upon the accommodation of animated text
being placed in preparation for something new to be added either via
an ajax call, or through a new interface which is being transformed
into something else.
I know some work was made to chat in some aspects of such regards. I
just don't know how extensive the work was in actual fact.

**Comment by DonnaScriptTechs** [comment]
@Elshara we are seeing that on the sites experiencing css issues, it has been related to plugins not being updated. Third party plugins. Most of these have been from younet but we cannot say it would only be those. Right now, that's where the issues have been so far, with sites with third party plugins. We are working on an improvement for our own product so that if a third party product is not updated it won't interfere with our own CSS rendering properly. 

As for why I posted that I wasn't able to reproduce the issue on my live demo, it is because we've been testing in various areas and have been unable to reproduce the issues. On clients in tickets, we found it to be third party plugin related so far. All of them. We are still checking though it is a holiday.

**Comment by Elshara** [comment]
I understand. Sorry if I made a miscommunication about the demo thing.
I didn't intend to mean there was a problem with what you did to
upgrade.
What I was trying to point out, somewhere, there is a problem. If
third party issues are to blame, then there's a reason for it. Some
vendors overlap core code, it can't be helped. I know of one provider,
Radcodes, which does this but they create hooks for their effected
plugins so as to not cause too much damage.
Maybe other providers could do the same. That way, their css class
could be enforced as something other than what social engine has,
unless it clearly states in their documentation, this plugin effects
core code and template files.

**Comment by poeticjustice** [comment]
@DonnaScriptTechs @SpiritWolfie there is a 3rd party dev who was first to make a vertical theme, social engine solutions...... their vertical theme is sexy as and similiar, thats why Donna may have been asking.

If these bubbles are a cached css issue, whats best way to flush it for all users who revisit the site?

**Comment by DonnaScriptTechs** [comment]
on my local I just delete stuff in the cache folder. I've not done that on my live as I have to do ssh and that's a bit of an adventure for me. 

Best way to test things to avoid cache is to enable development mode. Disable it after debugging.

**Comment by Elshara** [comment]
Cache when upgrading? I thought it cleared itself if packages were refreshed?

**Comment by SpiritWolfie** [comment]
Seems this is caused by SEO "Core"

**Comment by Elshara** [comment]
ok I'm so glad I never bought a thing from them. Younet suck just as
bad. All the providers with cores, ses, seao, younet, hire experts
etc.

**Comment by DonnaScriptTechs** [comment]
@Elshara yes, I clear cache if I see issues as one troubleshooting step to ensure there's not something funky in there. Never know if there could be an issue when cache fills in. Sometimes I clear it a few extra times or manually clear it.

**Comment by gsf00001** [comment]
@Elshara ==> "...All the providers with cores, ses, seao, younet, hire experts etc."

I wish others didn't have Cores (for many reasons), but can understand some of the reaons(s) why they need them.  Although I never used Younet for anything (purposely stayed far away), I've had great experience and incredible compatibility with all my Plugins from SES/SEAO/HE/Webhive/SEM/Radcodes/SEEs (I think 5 of those have Cores), along with the SpectroMedia Theme by SES.  Maybe I've just been lucky, but these Devs have done a wonderful job (and I've used 5 of them for custom work ranging from several hours to several hundred hours, depending on the Dev).  Part of that I believe is in building a relationship with each one and being fair and not nickle-and-diming Devs or expecting them to do 'everything' for free.  

No, I haven't upgraded yet to SE4.9, but have a plan in place that will be modified as necessary based on when all 3rd-Party Plugins I have installed are updated/compatible.  Part of this plan includes any special instructions/procedures/sequencing from each Dev, as well as most of them performing the updates for me (and paying them to do so - the price is worth my peace of mind and preventing finger-pointing for the most part).  It's my way of saying 'thanks' for updating your Plugins and for taking care of any possible issues that arise.   

So, all of that to say that taking a chance on some Devs with Cores isn't a bad thing :)

**Comment by Elshara** [comment]
Notice, I didn't include radcodes in the list?
There's a reason for that. Radcodes I trust a lot more than any of the
other developers. Sometimes I swear, the others just copy code from
one another and sell the same base stuff without the extra hundred
widgets seao puts up for grabs. I wouldn't be surprised if that was
the case. Radcodes just seems to integrate things better, and doesn't
try to make you feel like an idiot. But Vincent is extremely by the
book. HE means it, if you pay for one month of support, he won't even
contact you back if you don't pay past the allotted time frame if you
wanted to reach out. But on the other hand, he's still and is the only
developer who does this, sells social engine 3 plugins. There's a few
of them on his list, so I think he genuinely cares about the customer
base he has. If it's a bit commerce driven.
I've heard stories that social engine add ons does do discounts based
on specific needs, but I haven't had the time to really test out the
theory. No, not all developers are bad, but not everyone of them can
give you a decent value for your service. Finding someone who takes
into account the need of being reliable on a moments notice, is a rare
quality in developers. It's something I've grown to seriously admire
and appreciate in a company, because they put your needs, a priority.
I hesitate to even ask what your experience with custom jobs are. But
I'm interested to hear it.
As for the cache issue, clearing your computers dns cache might help two.

**Comment by gsf00001** [comment]
==> "I hesitate to even ask what your experience with custom jobs are. But
I'm interested to hear it."

For the most part, my experience has been okay to good with the 5 or so that have performed customization, but one truly stands out:
-  SocialEngineMarket has done such an amazing job that has exceeded my hopes and dreams on what they've customized.  My goodness - if you can dream it they can build it.  They ask the right questions during analysis and development and final code is extremely close to perfect on the first try.  In my close to 3 decades of developing software I have never experienced this level of overall thoroughness and mind-boggling ability to produce something that's somehow better than what's spec'd and envisioned and requiring so very few revisions.  

As far as value, all of the Devs I've been fortunate to work with have provided value equal to or exceeding the compensation. 

Quick response - there are at least two things to consider here:
a) do such a good job to begin with that little to no support is required (SEM is a prime example of this)
b) quickly resolve issues (resolution is key here, not just response time)

**Comment by Elshara** [comment]
Wow! I've not heard of them before. I also don't see them in the
official se marketplace. I'm going to check them out. thanks!
