### ISSUE TITLE
Multiple star icons on vertical menu

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#663]
4.9

On the vertical menu their seems to be missing icons? I have like 5 stars as icons. 

![image](https://cloud.githubusercontent.com/assets/9712738/25009753/a229abea-201c-11e7-8dad-5d6950f89baa.png)

According to the update theirs suppose to be new fancy icons etc?

**Comment by DonnaScriptTechs** [comment]
We have font-awesome support for themes that support that. Please test with the default Insignia theme to rule out issues with the icons, just to see if they load with that.

**Comment by SpiritWolfie** [comment]
This is the default Insignia theme >.> just the black variation of it.

**Comment by DonnaScriptTechs** [comment]
Ok did you click Save theme and clear cache after upgrading? Also clear browser cache?

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs Yes donna... I tend to trouble shot and test my stuff before opening up tickets...

lets just assume when I open a ticket that I have already done all the "standard step" that every company in existence has drilled into our brains, such as resetting the router, Powering the pc off and back on... 

Not trying to get snippy here, but 4.9 is buggy, I can confirm these issues repeatedly on my dev site as well.

**Comment by Elshara** [comment]
Simple answer. It's a rendering display problem due to a css fault.
Either they are there, invisible, or haven't loaded on the page at
all.

**Comment by DonnaScriptTechs** [comment]
@SpiritWolfie We ask the questions as a standard practice as not all clients know this. If someone has the same issues, they can sometimes be fixed by some of the steps we mention. It is for that reason that you will see the same questions being asked as a troubleshooting measure and also to gather information. We realize that some of our clients are knowledgeable but we still need to ask for those that aren't and read this too.

We are checking all issues and will respond soon.

**Comment by DonnaScriptTechs** [comment]
I forgot to ask if those are custom menus. If they are, then it will show a default star icon until you change it. You can use font-awesome or css based icon. Our tutorial mentioned how to change the icons, http://support.socialengine.com/php/customer/en/portal/articles/2771313-enabling-vertical-menus?b_id=14386 . Please test and see if that fixes it for you.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs Default...

Also when we try to change anything in the new themes constraints, it wont apply, I've put a support ticket in about all these issues, and included the FTP info in the support ticket, I'd be very grateful if someone could just fix these issues as a favor for me or whatever

I and my coder don't have time to debug this update and our landlords are being jerks with us right now.

**Comment by DonnaScriptTechs** [comment]
They are checking things We are finding that all issues so far have been due to third parties not updating their products which has caused our CSS not to load. We are working on improving that part of things on our end to avoid those issues and recommending to disable all third party products until each developer confirms they work in this version. I'm not saying this issue is definitely that but our team is checking each issue and a technician will be on this bug report soon.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs I've disabled almost all my plugins when I did the update, so these are the icons i'm getting on default stuff from the default menu

I still need the fix for the sql thing too, and need the constraint issue where making changes to it doesn't do anything looked at as well. (i'll write a bug report about that too)

**Comment by DonnaScriptTechs** [comment]
You mention almost all. If you try without any plugins as we've found many that are not updated, you might find this clears up as it has with others. 

The sql thing has a fix posted in that bug report with the explanation from our team. You should find it resolved if you do that step mentioned due to the issue with the server during upgrade. We are also looking at improvements for that process due to server issues. I'm on skype if needed.

**Comment by Elshara** [comment]
Progress is a wonderful thing.
I thought you could change the star icon for default areas.

**Comment by DonnaScriptTechs** [comment]
@Elshara you can change the icon. I have a tutorial linked above if you would like to try it. It allows font-awesome or css icons.

**Comment by Elshara** [comment]
Awesome! That's what I thought, you could do so.

**Comment by DonnaScriptTechs** [comment]
@SpiritWolfie did you get this same issue on your other installs that didn't have third party products?

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs This seems to be caused by plugins, Will close.

**Comment by DonnaScriptTechs** [comment]
Thank you and we do have an improvement to keep third party plugins from causing this sort of issue in the future. We also posted a patch that fixes these issues for other sites. I will grab that and link it.

**Comment by DonnaScriptTechs** [comment]
https://github.com/SocialEngine/phpv4-issues/issues/688 this might solve a lot of your issues you have been having. We felt we needed to make this improvement for our clients. The patch in that bug report seems to fix it for that client and it's been tested on other clients' sites as well.

**Comment by Elshara** [comment]
:)
