### ISSUE TITLE
Social engine documentation 

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#677]
This page is lacking and I would like to ask it be extended on, or get a question I have answered here.
http://support.socialengine.com/php/customer/en/portal/articles/2019547-moving-your-website-to-another-server?b_id=14386

What about those of us who want to wipe all custom code from our software and start fresh but not lose any of our users profiles/content/pms/photos etc?

What database and such would we need to export and import, The documention above just has you move 'export' everything but doesn't mention what does what, or affects what

Lets say I put up a Dev site with a fresh install of 4.9, I have it on php7.1 and everything seems to be working, I want to make that my new live and just keep all of our content and settings for all the base SE stuff, What would we need to do to do this .

**Comment by DonnaScriptTechs** [comment]
Please ask questions like this at our community. The bug tracker is for bugs with the script. Documentation requests should be done via our community or via a ticket to our sales department.

**Comment by Elshara** [comment]
Well you could either create a social engine migration script to
migrate instances of default user content from one place to another.
Or backup your database prior to installing third party code. If you
wanted to truly start fresh, you could just migrate user content and
profile tables so long as the data you require to import, doesn't come
with physical files. Otherwise, if it does, you'll lose content unless
you monitor what files go where. Usually they would exist in the
temporary or public folders.
