### ISSUE TITLE
Feature enhancement: Advanced Share Plugin

### ISSUE THREAD

**Issue by ritika-saini-bs** [SocialEngine/phpv4-issues#679]
1) A notification is sent out when an item is shared. We need to work on sending emails also for this action.

2) For a 'Share Type' under it's settings >> Notifications >> Create a new option 'None'.

Support Ticket: https://www.socialengineaddons.com/support/viewthread/42836 

Point 5 B & 5 C in the support ticket.

**Comment by DonnaScriptTechs** [comment]
We can't see your private support tickets with third party experts. If this is a feature request for a third party product, please close it and please go to the expert and submit it to their team as our github is not for third party feature requests.

**Comment by gsf00001** [comment]
@DonnaScriptTechs 
Uh, that's weird.  Although that specific text isn't in my ticket, that link and ticket# is actually one of my support tix with SEAO (and the points they are referencing exist in my ticket).  So my hunch is probably someone from SEAO accidentally posted that to github.

BTW - their Share Plugin is fantastic - not only the 'usual' social sharing (similar to addthis/sharethis) but ADMIN may also configure what may be shared where into your SE-based site (ex. allowing you to share something specifically to a Group or Event you're Owner of, or to their Plugins as well).  Anyway, great Plugin.  I'll be replacing my Addthis soon with this after further testing.

**Comment by DonnaScriptTechs** [comment]
Ok I'll close this as they must have had our github open and their own at the same time and maybe posted in the wrong window.

**Comment by Elshara** [comment]
Nice idea though. That's not the only type of responsive issue I've
seen posted to git hub.
Yesterday, since I was just testing out some features of Dolphin Pro
for laughs and giggles, I came across their embed.ly integration which
didn't happen until recently. Since it's no longer free as of today,
last night, I mentioned in a forum topic over there, that they should
try iframely since it's free and we have it here at social engine. I
kid you not, within 2 hours, both dolphin pro git hub and una.io had
full support issues linking to the thread for iframely and all their
lead developers, Alex, Nathan and Andrew were on board with the idea.
And yet I didn't receive a notification about any replies to the
discussion I made yet. That's fascinating!
Good morning people! loll
