### ISSUE TITLE
Activity wall photos

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#681]
4.9 php 7.1 All permissions set correctly, requirements of SE met

I have installed 4.9 on a completly different Os at this point and can not upload photos, on my other install on SE (differnet OS but meets requirements) I sorta can upload photos just fine but get a error 500 even know permissions are all set correctly, and the thumbnail multi select bugs out

On one of my dev sites you click the wall, click add photo and it does nothing, when you click it the box pops up and vanishes and just gives you cancel button.
![image](https://cloud.githubusercontent.com/assets/9712738/25106104/b435f83a-237c-11e7-881e-d0cb11fc8183.png)

on my other dev site it does this, in this image you can see the thumbnail listing it twice and the 500 error and the others basically just keep showing the spinning symbol.

![image](https://cloud.githubusercontent.com/assets/9712738/25106128/d8fc9f0c-237c-11e7-9b3a-5e8d959e3bab.png)

No plugins, Fresh install of 4.9, with 7.1 php, All permissions are set in accordance to the install instructions and documentations, we have double/triple checked (we've went as far as to change OS etc, and these are Dedicated server, not vpn's not shared etc. >.<

We get these issues regardless of our server configuration/OS or setup.

Under the inspect menu this is what we see

![image](https://cloud.githubusercontent.com/assets/9712738/25106271/75ac3c04-237d-11e7-8259-27dd25b8b731.png)

I'd like to Re-state that any other platform we use I can upload photos to without 404 or internal server issues just fine, I know SE isn't "Other platforms" but I just don't understand why I can install anything else regardless of what platform and have zero issues like this, no 404's, no 500's, etc.. Everything just works for the most part. It's just "Odd"

**Comment by Elshara** [comment]
I had trouble uploading on the demo two. No files would work. The
uploader wouldn't even display itself.

**Comment by SpiritWolfie** [comment]
I would also like to point out its not working at all on mobile period... Mobiles don't Support flash, most browsers don't support flash and have flash blacklisted these days, (chrome does and if I remember correctly so does firefox)

**Comment by nizhnyk** [comment]
I didn't even bother updating to multi photo uploads, just removed everything related to it. It doesn't work without flash, nobody is using flash. What's the point, why even waste time developing it? It's not like old days when it was a norm and everyone expected to have it. Would you recommend me to write a guide on my website for users on how to install/re-enable flash in their browsers and make them vulnerable to attacks, just so they can upload multiple photos on my website?

**Comment by Elshara** [comment]
Yup they won't even make an html5 uploader and just use as the damn
default. That's the problem. Flash is history and the more browsers
who blacklist it, the sooner se will have no choice but to change
their minds about it.

**Comment by DonnaScriptTechs** [comment]
Does this work now after you changed permissions for application/modules?

**Comment by DonnaScriptTechs** [comment]
I'm able to upload from an iPhone 5c at the demo in photo section. For the feed, I don't have a small image to test on my phone.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

All permissions are set in accordance to the documentation and what we know is needed personally, on both test sites, i'd also like to point out both of those are new sub domain's, on completely fresh OS's, on completely different side of the linux family, No firewalls or nothing on these dev sites to interfere with anything, I'd also like to remind SE that Flash is blocked in allot of browsers these days and barely functions correctly with any browser, Heck the admin control panel was complaining about flash at the package manager. And please don't suggest I don't have flash installed correctly >.> just to state this before its asked or said.

With as much testing as we've done countless times with 3 different server boxes, I am now 100% positive it is not on our end, I have 2 server boxes IN HOME and 1 at a data center.

**Comment by DonnaScriptTechs** [comment]
I'll have to test on local as the demo has file size restrictions. I'm using an iPhone 5c which works to upload to photo section and to upload a video on my local. I'll try feed and see. I have local at php 7.1 also.

**Comment by DonnaScriptTechs** [comment]
I've added this for our team to check as I'm getting odd results from tests.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs see my last post too please

Also flash doesn't work correctly on everyones pcs as well, I've got allot of users who can upload and allot of users who can't, yet those who can't can use other sites to upload photos just fine

(Mobile doesn't work on my s5 android at all) for photo uploading.

**Comment by DonnaScriptTechs** [comment]
We need to separate issues but will try to check the other issue.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

This is all related o.0, We're discuss the photo upload and flash, Thats what this bug report is about... That includes mobile photo uploading, not sure how its a separate issue... as far as I can see its all related to the same thing from my testing.

**Comment by DonnaScriptTechs** [comment]
Duplicate feed issue and 500 internal server issue look to be different issues. As for flash, there is a built in fallback to use something else when flash is not available. We are still looking at this though.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs no one I know will touch edge, (I wont eve use edge to test)

Chrome (Latest update) and Firefox Latest update, WaterFox (latest update) chromeium (Latest update) Neon Browser (Latest update)

I keep -everything- on my pc updated and manually check with stuff like Ninite.com and what not for updates

They all show the double images and the 500 error.

**Comment by DonnaScriptTechs** [comment]
I'll fire up my win pro pc and test.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

The step I used was

Set album to handle a limit of 15 photos uploaded
Click Wall
Click upload photo
Upload like 10 or so images by ctrl+ Clicking

**Comment by DonnaScriptTechs** [comment]
I'm only able to reproduce the original issue I mentioned. I tested on my win10 with chrome and firefox and all images loaded with the above settings as mentioned.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

if this is the case then you guys really need to go over your documentation and what not, because as I stated I have tested this on 3 different 'dedicated servers' 2 in house, (no host) and 1 at a data center, we have manually configured these machines from scratch, the one in the data center has had 3 different OS's placed on it to test this, no firewalls, or control panels, All permissions and your documantion followed to a T and I can repeatedly reproduce this on a fresh install each time

So ether you guys have things configured not according to your documentation, or we are doing something completely different. Because no matter how many hours I pour into this, Almost everything I've brought up as a bug I can reproduce over and over.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

So if its a issue with our Configuration, Then theirs a issue with the documentation at hand, because thats what we're following, the install script and the documentation listed on the website, which has already been proven by myself to be 'inaccurate and missing' info. Which makes me wonder what else may be missing that 'is needed' to run Social engine correctly

I am sorry, but I am not 'paying' someone to do something "WE" Know how to do, we can install countless other platforms zero issues, countless game servers, no issues, I know you keep saying that shouldn't be used in comparison but I am going to keep comparing it to my other testing, When Something A doesn't work you load something B up to see how it functions and see if you get the same kind of errors, 500, gateway, 404 etc... this is normal testing standards, 

I have like 4 Devs now, and 1 live site, and they all have the same issues, All are on different OS'es and different configurations in regards to server setup, but all ALL have been configured to meet SE requirements and even optional stuff has been installed

Ray has even confirmed that my list checks out for loaded modules in a Email exchange, this is a issue with Platform.

**Comment by Elshara** [comment]
Something is the underlining cause of everything here I can just feel it.

**Comment by SpiritWolfie** [comment]
@Elshara 

I agree, but I can rule out our server box and said configurations when we're legitimately using different boxes and different configurations, so ether they are setting their stuff up with permissions we're unaware of or something along those lines, I will no longer accept "The root lies with server configuration" etc at this point, Me and my server tech spent a entire day going over the list of requirements/permissions to a T and we can still reproduce these issues... I seriously own 2 boxes in person, I've even ruled out distance by testing it in house, Ruled out 'host' by running it in house, ruled out firewall/control panel by making sure none of that was installed when I did the dev, No proxy's nothing

yet I kid you not, Druple, oxwall, joomla, elgg, dolphin, word press, 7days to die, ark, terriara, minecraft, space engineers, I have NEVER had any 404, 500, gateway issues, time out issues on any of this stuff

All of those install fresh and will not give me 500 errors when uploading photos, etc... my users who can't upload photos to my SE live site 'can' upload photos on my other test sites.... The only difference in any thing is the engine/platform thats IT, same configuration, etc. just follow the documentation when setting them up, nothing else nothing less, 

The issue has to lay's somewhere in Social engine. We've poured more hours testing this repeatedly then we should have, and everyone on my team is sick of the support tickets telling us to pay them to have it looked at, We KNOW how to run servers x.x which is proven by my other installations that work fine!

**Comment by SpiritWolfie** [comment]
Now.. On a side note...

If one of the devs/techs/staff want to come into this thread and tell me Precisely what OS, what configuration and what permissions 'they' are using where they are not having these issues, I will happily set one of my boxes up to match their settings, and I would almost say 99% I'll still have issues

**Comment by Elshara** [comment]
Silly question, but have you tried making file and directory
permission changes to 777 for shits and giggles? The issue simply is
that the info.php file is basically what social engine is using to set
itself up in terms of what modules the info.php file can actually see.
It can't see mod rewrite on my server even though it is enabled. It
can see it on other servers just fine.

**Comment by SpiritWolfie** [comment]
@Elshara Yes I believe we have done that, we've poured probably a hundred + hours into testing this  on multiple occasions, Not just 4.9 but the previous vers as well, they can't sit here and keep telling me its my configurations when I've changed the configurations and the server on 3 different boxes and get the 'same results' each time... 

I'm so sick of that excuse "its your server/configurations" I pay for a server tech and he's very good at what he does... heck even Ray has confirmed our loaded modules checked out... we've tried apachi and nginix and get the same issues >.<

**Comment by DonnaScriptTechs** [comment]
Regarding my own set up since you mentioned "so ether they are setting their stuff up with permissions we're unaware of or something along those lines"

I'm not a server person. I have about 7 installs of SE on my local and 2 installs on live. For local, I downloaded Mamp pro and used that out of the box. No changes other than changing which php version to use to test with. I did add ffmpeg but that wasn't a server change. It's just an out of the box set up.

Regarding live. I'm using cazaratech's VPS for one and Cloud for the other. Neither of these are set up for SE (they have the base requirements but nothing extra as they were set up for a different script). You can see my demo works but it's on php 5.6.23. Try that php version for now.

We are looking to see about issues for 7.1 and 7.0 to improve any issues with that. Our own demo is running PHP 7.1.

**Comment by Elshara** [comment]
I'm not a server person either. I've tried unsuccessfully to install a
localized based server package and install something like social
engine or even phpfox on it, and no real luck. I know packages like
wampp and xampp are out there for windows, and I thought about making
a basic installation of one of those to see if, it would fix my
curiosity to have a localized installed version of social engine. I
just haven't done it yet. I know my home based laptop won't be nearly
as adequate as the server box I rent from name cheap. I've tried on a
local linux machine and well it was always a problem getting kurl
installed for instance. Ion cube and apache seemed to load okay for
the most part. Mysql and php my admin, same idea. It loaded okay but I
actually had a friend do that with me as I was just only testing
things for shits and giggles, for the fun of it essentially.
I wish I could be better at coding, but I kind of lost interest when
ssh got involved and I feel embarrassed and ashamed to admit it but,
I'm learning and that's as far as I kind of got. The whole command
structure, specifically, remembering the punctuation and spacing with
the connector syntax always through me off, for a loop of errors most
likely. And I just don't have the type of long term memory like that,
most developers actually seem to. Even my own personal friend uses
tutorials from digital ocean to do most ssh access things since, he
didn't have anyone either to help teach him. Now days, you can just
get commands to have linux packages belonging to the Debian Ubuntu
package manager installed usually without a hitch, so that's what we
used. Default was php7 and it seemed to come with the default php
extensions but, getting them to recognize the file structure and then
file permissions, was another story entirely. Info.php proved as much.
Even when things like Mysql and such were already available and
working, by doing manual configuration requests via php my admin.
I totally understand your frustration. I get it. I've been there
personally and gave up a long time ago because there's just too much
modern programs especially paid cms ones require for a web server box
to handle, that say, word press doesn't. That's why people choose it.
Instead of paying someone else, they just host their own and then it's
only a matter of time before they get real traffic associated with it.
And they don't need to worry about their IP getting banned because
well it's not commercial, it's dynamic. They change their status and
the ISP usually does all the work if they assign you a new dynamic IP.
As for DNS, it's all done through domain providers. So no need to
worry. It's easy for a home developer to get online, but it becomes
very difficult to challenge yourself to stay online, if what you wish
to use to do so, is not playing well with things you don't know, you
need to have set up a certain way.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs I'll ask my server tech to drop the php vers to 5 and see if we have the same issues.

I know we tried php 7 and 7.1 got the same results on both.

**Comment by DonnaScriptTechs** [comment]
We've improved compatibility issues for php 7 and also fixed an issue with photo uploads. Please test after we release 4.9.1. If you still have the same issue, please post a new report. Thank you!

**Comment by Elshara** [comment]
Thanks for doing so. It's appreciated greatly. :)
