### ISSUE TITLE
Admincp Break When in Maintenance Mode 

### ISSUE THREAD

**Issue by leandrotavaresrocha** [SocialEngine/phpv4-issues#688]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Enable Maintenance Mode

What happens?
-------------
1. The admincp layout break as if it was not loading any CSS

What were you expecting to happen?
----------------------------------
1. That the website being loaded normally

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** Centos OS 6

**SocialEngine PHP Version:** 4.9.0

**Comment by Elshara** [comment]
Used a private installation to test this and it seems this is true.

**Comment by DonnaScriptTechs** [comment]
I don't see this on any of my upgrades. My demo site was in maintenance mode for days while I reapplied customizations. Please try enabling Insignia theme and click Save Theme and fully clear all cache. See if that helps your issue. We do have improvements coming for those with third party products that may have broken sites.

**Comment by gsf00001** [comment]
==>"Please try enabling Insignia theme and click Save Theme and fully clear all cache"

My apologies for being confused, but this is to resolve an issue in ADMINcp?  I ask because my fear is that if a theme or .css is causing (or solving) an issue in ADMINcp, that's a danger to ADMINcp access.  I always hoped I would be able to access ADMINcp regardless of theme and/or .css issues.  Am I missing something here?  If so, again, my apologies.  Thanks.

**Comment by DonnaScriptTechs** [comment]
No I'm trying to rule out CSS not loading due to the issue we mentioned in our blog. It doesn't impact admin working, but if no CSS loads, it looks bad. Noting that none of my upgraded sites have this issue.

**Comment by DonnaScriptTechs** [comment]
I meant to also say to please enable development mode to see if things clear up.

**Comment by leandrotavaresrocha** [comment]
Yes, I am not facing a issue in the frontend, but in the backend. When I enable maintenance mode my backend appear like if no CSS is being loaded. Opening the developer tab from chrome, I see that I am receiving a Error 500 related with /application/css.php?request=application/modules/Core/externals/styles/admin/main.css&c=2582. 

This is the error: Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by DonnaScriptTechs** [comment]
Well that is odd. I cannot reproduce this. Can you check permissions? 

I tried Maintenance mode with development mode and with production mode and am not able to get that error. Perhaps one of our team can check on a different set up.

**Comment by DonnaScriptTechs** [comment]
Do you have third party plugins?

**Comment by gsf00001** [comment]
==> "No I'm trying to rule out CSS not loading due to the issue we mentioned in our blog. It doesn't impact admin working, but if no CSS loads, it looks bad."

Thanks for clarifying that Donna - much appreciated.

Ah - okay, now I get it.  Is there a way to load ADMINcp with a 'default' .css (i.e. to prevent or override any possible interference)?  Basically, my concern is that if a .css issue makes ADMINcp difficult to see/use, is there a way to prevent this to begin with?  I'm obviousy no SE expert - I'm just used to the ability in many software products having a 'load in plain-vanilla mode' method.

**Comment by DonnaScriptTechs** [comment]
We have already made improvements for a 4.9.1 coming within the next week that will address these sort of concerns. We did not like clients being impacted when CSS would not load due to third party issues we encountered this time around. As such, we've improved things so that our CSS will load in the case of issues from non-updated third party modules that override our CSS.

**Comment by Elshara** [comment]
What about the possibility to upgrade all existing themes to a unified
core so they can be separate from one another, but have the same core
base?

**Comment by DonnaScriptTechs** [comment]
@leandrotavaresrocha we have zipped the files that fix this for other sites and for our tests. Would you be so kind, and anyone else with the issues with css, to test the fix as well? We can attach it here for you.

**Comment by DonnaScriptTechs** [comment]
[testfiles.zip](https://github.com/SocialEngine/phpv4-issues/files/936621/testfiles.zip)

The above is from Ray. Unzip it as it is not an installable file. Make a backup of any of the files you will be replacing. Once you have a backup copy of those, upload the files to your server, overwriting originals (that you made a copy of). You may want to have development mode enabled to avoid cache issues or clear cache after.

**Comment by DonnaScriptTechs** [comment]
How did it work?

**Comment by leandrotavaresrocha** [comment]
I uploaded and now it is working. I upgraded all my 3rd party plugin to a version that work with 4.9, so in theory this issues should be a problem with third part plugin, but not a problem with outdated plugins.

**Comment by DonnaScriptTechs** [comment]
Thanks for testing and letting us know it works fine.

**Comment by DonnaScriptTechs** [comment]
This is improved for 4.9.1 when it is released.

**Comment by Elshara** [comment]
:)
