### ISSUE TITLE
Hide widget on mobile site doesn't work

### ISSUE THREAD

**Issue by angelinfante** [SocialEngine/phpv4-issues#706]
What are the steps to reproduce this issue?
-------------------------------------------
1. Configure a widget to be hidden on mobile phones.
2. From a mobile phone, visit the page with the widget previously configured to be hidden on mobile.

What happens?
-------------
The widget is displayed.

What were you expecting to happen?
----------------------------------
Don't see widgets expected to be hidden in mobile devices.

What versions of software are you using?
----------------------------------------
**Operating System:** Linux, Apache, PHP7

**SocialEngine PHP Version:** 4.9.0

**Comment by poeticjustice** [comment]
Is this hidden on a mobile, for mobile plugin?
And not meant to be displayed, or hidden based on being responsive for mobile?

**Comment by angelinfante** [comment]
I always thought that the purpose of that feature was to hide the widgets when the page is opened from a mobile device in a browser, reducing the amount of HTML or automatically hidden without custom CSS. So would be useful for the responsive design.

**Comment by Elshara** [comment]
Does mobile plugin show compatibility with responsive theme?

**Comment by DonnaScriptTechs** [comment]
I can't reproduce this on my 4.9 site. I have the mobile plugin (Mobi in the plugin manager) installed, which is required. I'm viewing the site from an iPhone 5c and viewing in mobile view (not full site view). I chose to hide the Banner widget from the blog browse page on mobile and the widget does hide.

**Comment by angelinfante** [comment]
So, that feature only works with Mobile Plugin? I thought its purpose was avoid rendering the widgets when the site is accessed from a mobile device, even using responsive theme.

**Comment by DonnaScriptTechs** [comment]
The mobile plugin is what does that sort of stuff. Please test with it enabled and let us know if it works for you.

**Comment by angelinfante** [comment]
Thank you Donna. I don't have that plugin, does it actually work with the responsive theme? I have the mobile plugin from a third party and it works with its own layout and theme...

**Comment by DonnaScriptTechs** [comment]
It's enabled on our demo with the Insignia theme. If you have a mobile plugin from a third party, please contact them and let them know it has a bug with the widget display settings. It's possible that their plugin also requires our plugin or that they need to fix their plugin to work with the settings.

**Comment by angelinfante** [comment]
Ok Donna, I'll check your demo, but I don't mean it's a third party issue. As I told, the plugin I used has it's own layout and theme builder and I'm not using it anymore in favor of responsive theme. 

I think this feature should be a core feature compatible with responsive themes, without any plugin. It doesn't make sense to show the option "Yes, do not display on mobile site" if a plugin is needed.

Thank you!

**Comment by Elshara** [comment]
I'm all for getting rid of the mobile plugin personally.

**Comment by adira-g** [comment]
Hi @angelinfante 

to answer your question with my words: using the full-site theme (like insignia) always renders as full site, even you are using a mobile device. If you want to use the mobile functionality including the option "hide on mobile site", this only works by a mobile plugin like "mobi". In this case, users are redirected to the mobile template, which is different from the main full site theme. You can however customize the mobile settings and pages in the layout editor and additional in the mobile.css, though to achieve certain features like IM or chat rooms, additional plugins or coding is required.

It does make sense, to have the option "hide on mobile site", since you can use the same widgets either on the full site and on mobile sites.

If you prefer to use the full site responsive theme for mobile devices, you need to disable mobi (or other mobile plugins) and do it without the extra option for mobile (like hide on mobile site), because then it will show the full site only.

It might be an idea to create a plugin, which uses the mobile settings to hide certain widgets in order so safe traffic on mobile devices, which then automatically uses a "light mode" if mobile device is detected and people may switch from "light mode" to "normal mode"; this while always using the full site theme. I think, this is what you expected to be default, didn't you?

**Comment by angelinfante** [comment]
Yes @adira-g, that's what I would expect by default.

**Comment by Elshara** [comment]
That functionality has always confused me as well. It is too dependent
on the mobi plugin. I only wish it would auto detect settings based on
user agent while using the main site.
