### ISSUE TITLE
FollowSymlink creates a potential vector of attack

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#727]
4.9.1

As it stands SE uses FollowSymlink, this is something most platforms have gotten away from about 5-6 years ago give or take... 

it allows anyone on the server to use this to link files, this means another user on the server if its shared could link to the passwords files etc.. on the server box.

Please see - 
https://www.google.com/search?q=Followsyntex+dangers&oq=Followsyntex+dangers&aqs=chrome..69i57.5544j0j7&sourceid=chrome&ie=UTF-8#q=Danger+of+FollowSymlinks

This should be done by group ownership in permissions, not "anyone"

This IS a security issue I and my server tech has checked into this.

**Comment by SpiritWolfie** [comment]
Other SE owners can easily confirm this by checking their Htaccess list and see that its using "FollowSyntex"

If anyone else wants to confirm our findings.

**Comment by DonnaScriptTechs** [comment]
We haven't ignored this. Our developers wanted to double check things before responding.

**Comment by SpiritWolfie** [comment]
Now that an attacker can create files and symlinks inside your web root, it can let those symlinks point to arbitrary files on your webserver (/etc/passwd, config files with clear text passwords, ...) which finally could mean that an attacker can download all these files and use the gathered information for further attacks, like dictionary attacks on SSH password, simple authorized access to your database, ...)

Taken from a security thread about this.

As it stands the way it is set up doesn't use group ownership (we've checked that) it completely ignores the server boxes group ownership and is set to 'all'

Druple, etc has used the new way since 5-6 years ago meaning they patched this issue that many years ago.

I keep seeing a pattern with SE and I keep seeing its using OLD ways of doing things, which is probably why I'm having so many issues with it, Just like how hard it is to move it from one server configuration to another because its files doesn't tell itself where the stuff is etc...

**Comment by smazurov** [comment]
Not a direct security issue. Unless you can demonstrate a way that SE PHP creates a symlink (please do so privately to us!) via an unprivileged action (i.e without admin login), this is only a vector for potential attack, not a direct security threat. 

We're checking to see whats involved in removing that htaccess directive nevertheless, as eliminating potential vectors for attack is good for everyone, thanks for bringing it up.

**Comment by tossican** [comment]
First the solution (since it's pretty simple).. Change all instances of "FollowSymLinks" to "SymLinksIfOwnerMatch" in all .htaccess files... While the end user can accomplish this task themselves, there's no particular reason why this shouldn't be done on SE's end, pre-distribution... Not to mention, if this change is made by the end user, and then SE releases an update which overwrites the user edited .htaccess, the site goes down until the fix is reapplied, which is a hassle! ... Additionally, if as you say, SE doesn't make use of SymLinks, there's no reason to even have the directive in the first place.

Secondly, the clarification... Using FollowSymLinks on a site is not a security risk in and of itself...  However, in order for it to work, the server must allow it's use. This in turn opens the door for someone with malicious intent to make use of it... While SE may not be the security threat itself, it's requirement that a layer of security be crippled for its sake is indeed an increased threat for it, and other users.

Saying "It's not a direct security threat" is akin to your apartment complex requiring you to leave your door unlocked. They may say "It's ok, our staff isn't a threat. They won't come into your apartment without permission". While this may be true, it does nothing to prevent your neighbor coming in and rummaging through your dresser while you're at work.

Pure and simple, by blocking/disallowing the "FollowSymLinks" directive at a server level, administrators provide another layer of security for their users.. However, without manual intervention, this breaks SE.

The symptoms ... Any site using "FollowSymLinks" on a server with this directive disallowed will not load, throwing a 500 error instead. Additionally, server logs will report "Option FollowSymLinks not allowed here".

**Comment by DonnaScriptTechs** [comment]
We are still testing this internally. Thank you for your report.

**Comment by SpiritWolfie** [comment]
If this has been added to the 4.9.3 milestone 
Might want to add the label Issue or bug or whatever :)

**Comment by DonnaScriptTechs** [comment]
Technically, it's an improvement but we didn't want to move it to feature requests so we left it here and updated the milestone.

**Comment by DonnaScriptTechs** [comment]
We've added this to our list to fix and scheduled it for 4.9.3. As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).
