### ISSUE TITLE
Theme Bug / issue

### ISSUE THREAD

**Issue by mikelmajuuna** [SocialEngine/phpv4-issues#754]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …visit site landing page
2. …www.majuuna.com
3. …full site observe 'latest groups' , mobile site observe 'recent videos'.

What happens?
-------------
On landing page (  www.majuuna.com  ) full site Border / boxes 'latest groups' is more narrow than other borders / boxes even though settings are not changed or different. On mobile site the same issue but with ' recent videos'.…

What were you expecting to happen?
----------------------------------
…all borders / boxes to be same width as pre-set according to SE theme settings and design.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…I have checked all other SE themes that are part of SE v4.9.2p1 and same issue with all themes.
There are no function errors. only error with width.
I have checked on several independent devices and same issue on all.

What versions of software are you using?
----------------------------------------
**Operating System:** …
SE v4.9.2
**SocialEngine PHP Version:** …
php5.6

**Comment by DonnaScriptTechs** [comment]
Hi Mikel,

I'm not having issues with the blocks or I'm not looking in the right place. They all have padding set to 15 px.

The issue I do see with videos is the image doesn't go full width of the block. It makes it look odd. With videos that have long titles, I can see that the block is the proper size by looking at the text. Noting that a word that is too long will drop down to the next line and could make it look like it's not the proper size due to the thumbnail issue I mentioned above.

Following are from Insignia theme.

Recent Videos
<img width="248" alt="video block" src="https://cloud.githubusercontent.com/assets/6908282/26788667/ff1e0010-49db-11e7-88b2-dfd0563cb547.png">

Recent Groups
<img width="252" alt="groups block" src="https://cloud.githubusercontent.com/assets/6908282/26788672/02701d48-49dc-11e7-8e28-f3ff72b93f2a.png">

Recent Groups Mobile
![groups mobile](https://cloud.githubusercontent.com/assets/6908282/26788785/54f50286-49dc-11e7-8450-86d1917ee8d6.PNG)

I think if we improve the size if the thumbnail, that will help for the video block. Your thoughts? If not that, would you please post screenshots of what you mean? I did see your site but didn't see the issue when I looked.

**Comment by DonnaScriptTechs** [comment]
Woops, here's the mobile video shot:

![video mob](https://cloud.githubusercontent.com/assets/6908282/26788928/becb52d2-49dc-11e7-90b0-3d1602540c17.PNG)

**Comment by DonnaScriptTechs** [comment]
Closing as issue was caused from customizations.
